### ISSUE TITLE
Not working - "Reason: image not found"

### ISSUE THREAD

**Issue by skamsie** [coderholic/pyradio#100]
I just installed this and when I select any station from the default ones I don't get any sound and see "Reason: image not found" at the bottom...

I just installed with `pip` I see version `0.5.2`

**Comment by s-n-g** [comment]
Hi @skamsie 

The version that's on pip is very, very old.

Please do uninstall it, and then refer to the instructions found here: https://github.com/coderholic/pyradio/blob/master/build.md
