### ISSUE TITLE
Installation failure, permissions issue? unavoidable err no 13  or err no 2 (Windows)

### ISSUE THREAD

**Issue by Ddubs97** [coderholic/pyradio#101]
Hello, I followed the windows installation guide meticulously and despite attempting to install with and without Git and with MPlayer in either `C:\mplayer`, `%USERPROFILE%\mplayer` or `%APPDATA%\pyradio\mplayer` (tried all 3) I still run into EITHER

'The system cannot find the path specified.' When trying to run:
`cd pyradio-0.8.6` 
`cd pyradio` 
`devel\build_install_pyradio`

(tried this with multiple versions of pyradio including the latest.)

This seems to be due to the folder structure as the folder 'devel' is in the 'pyradio-0.8.6' folder AND NOT in pyradio-0.8.6\pyradio

However, when I execute:

`cd C:\Users\Dan\pyradio-0.8.6` 
`devel\build_install_pyradio`

This usually returns:

```
[Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\\Lib\\site-packages\\test-easy-install-5344.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    C:\ProgramFiles\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\Lib\site-packages\
```

But weirdly, has also sometimes returned 'python3 err no 2 cannot import --version --build etc. from pyradio'  - But i'm guessing this error may have been caused by me trying to rearrange to folder structure to make build_install_pyradio execute properly.

So far I have tried:

1.  Manually giving 'full control' to all users on this machine to the folder `Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\Lib\site-packages\` 
I did this by editing properties>security settings on the folder, and this *should* allow all users read/write permissions to that folder.... it didn't work.

2.  Running the commands from elevated Command Prompt  (run as administrator)... didn't work

3. Deleting all pyradio assets and trying with different versions... didn't work.

Yes I am sure my account is the administrator of this machine and has administrative privileges... at least control panel says so.

I must admit i'm a total newbie but trying to learn. Maybe I made a mistake somewhere? I have gone through the Windows installation walk-through several times. If anyone has any pointers it would be much appreciated!

**Comment by s-n-g** [comment]
Hi @Ddubs97 

Sorry it took me so long to replay...

May I ask, what whidows version are you on?
I will assume it's windows 10

So, see the attached file; it's the output of *devel\build_install_pyradio* on windows 10
[pyradio-install.txt](https://github.com/coderholic/pyradio/files/4746023/pyradio-install.txt)

Can you please post your output of the execution of this file?

Also, can you open a terminal and execute *python*, just to make sure it is correctly installed and functional?

**Comment by Ddubs97** [comment]
Hi s-n-g

Yes, I'm on Windows 10 Home.

Here's the output when I execute devel\build_install_pyradio 

```
running build
running build_py
running egg_info
writing pyradio.egg-info\PKG-INFO
writing dependency_links to pyradio.egg-info\dependency_links.txt
writing entry points to pyradio.egg-info\entry_points.txt
writing top-level names to pyradio.egg-info\top_level.txt
reading manifest file 'pyradio.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '*.pyc'
warning: no previously-included files found matching '*.orig'
writing manifest file 'pyradio.egg-info\SOURCES.txt'
copying pyradio\__pycache__\__init__.cpython-38.pyc -> build\lib\pyradio\__pycache__
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\\Lib\\site-packages\\test-easy-install-16724.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1008.0_x64__qbz5n2kfra8p0\Lib\site-packages\

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.



###############################################
# The installation has failed!!!              #
# This is probably because PyRadio is already #
# running, so files cannot be overwritten.    #
# Please terminate PyRadio and try again.     #
###############################################

C:\Users\Dan\pyradio>
```

Also, here's cmd output upon executing _python_
```
C:\Users\Dan>python
Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

```
Thanks for the assistance!

**Comment by s-n-g** [comment]
Hi again @Ddubs97 

It seems a lot of people are having the issue you have - at least according to google.

The only thing I can think of is this: uninstall python altogether and install it again on a custom folder which is writable by you. For example, create *C:\Python*, make sure you can write to it (create a dummy text file or something in there), and then install python.

I got this idea from https://www.youtube.com/watch?v=4Rx_JRkwAjY

The video demonstrates how to install python 3.7 (that's irrelevant, any version will do) in *C:\Python\Python37*

**Comment by s-n-g** [comment]
Closing this one since it seems it is a non pyradio problem
