### ISSUE TITLE
build requires root

### ISSUE THREAD

**Issue by 532910** [coderholic/pyradio#104]
I'd like to try pyradio, but it requires root to build.

**Comment by s-n-g** [comment]
Hi @532910 

What is the problem with that?
No access to *sudo*?

**Comment by 532910** [comment]
I'm not going to run build as root.

**Comment by 532910** [comment]
I'm not going to install pyradio.

**Comment by 532910** [comment]
I don't trust it.

**Comment by s-n-g** [comment]
ok, you don't trust it...  :)

If you are on a Linux distro, you can use the file found here: [https://pastebin.com/wx1jUbqx](https://pastebin.com/wx1jUbqx) to install it as a normal user.
Just replace **devel/build_install_pyradio** with this file, and then install it using the command:

```
devel/build_install_pyradio --user
```

and tell me if that works for you.

If you are on a mac, please do tell me which version you are running

**Comment by 532910** [comment]
I don't want to install it. I'd like just build it and run in a separate folder: `/tmp/pyradio`.

I'm on linux.

**Comment by s-n-g** [comment]
There's no way to run it unless you install it first.

The only thing you can do is create a Virtual Environment, which put simply, is an isolated working copy of Python which
allows you to work on a specific project without worry of affecting other projects.

There is a tone of info on the net about [virtualenv](https://pypi.org/project/virtualenv/), so...

**Comment by 532910** [comment]
crap
