### ISSUE TITLE
Audio sounds bad

### ISSUE THREAD

**Issue by baruchiro** [coderholic/pyradio#111]
I'm trying to listen to this station:
https://kanlivep2event-i.akamaihd.net/hls/live/749627/749627/master.m3u8

But the sound is "broken".

Any help?

**Comment by s-n-g** [comment]
Same here with mplayer

```mpv``` and ```vlc``` are ok though.

You can either use one of them, i.e.

```
pyradio -u mpv
```
or
```
pyradio -u vlc
```

or set one of them in the configuration (open ```pyradio``` and press "*c*")

**Comment by s-n-g** [comment]
It seems this is a "problem" with mplayer (well, actually ffmpeg), based on this discussion:

https://mplayer-users.mplayerhq.narkive.com/RcyysSDP/there-is-no-cache-when-playing-m3u8-stream-hls-protocol

So, it is what it is...

**Comment by baruchiro** [comment]
I'm running on Windows, why I can't use `vlc`? :-(

**Comment by s-n-g** [comment]
That is because mplayer is the only player supported on Windows.
So, unless you can get a normal (i.e. playlist) URL for this station, you are out of luck.

**Comment by baruchiro** [comment]
And what about [this](https://wiki.videolan.org/VLC_command-line_help) document of `vlc`? Seems it have a CLI for Windows...

**Comment by s-n-g** [comment]
I know about it, but I was not able to get it to work on Windows...

```mpv``` works with named sockets, which I haven't tried on Windows, but I will, eventually...

**Comment by s-n-g** [comment]
@baruchiro I just added **VLC** support for Windows

Do have a look: https://github.com/coderholic/pyradio/releases/tag/0.8.8-beta5

**Comment by baruchiro** [comment]
I can't change the player by `-u vlc`, but after changing the player from `config` to `vlc`, it works! Thanks!

Now the problem is with the original link: https://kanlivep2event-i.akamaihd.net/hls/live/749627/749627/master.m3u8
If I'm opening this link from VLC (actually clicking that link downloads a file that opened by VLC), it works.
But from `pyradio`, it stopped after 10 seconds.

**Comment by s-n-g** [comment]
ok, done!

Please update to **0.8.8-beta6** and enjoy (hopefully :) )

**Comment by baruchiro** [comment]
But do you know what is the problem with the streaming stops after 10 seconds?

**Comment by baruchiro** [comment]
Now both working! I can use VLC by `-u vlc`, and the stream is not stopping after 10 seconds!

Thanks a lot and sorry I didn't fix that myself. I tried...

**Comment by s-n-g** [comment]
Well, it was a bit tricky :)

If you are interested, the trick was to add ```' Segment #'``` here: https://github.com/coderholic/pyradio/blob/master/pyradio/player.py#L1758
after inspecting the log file produced by vlc, looking for "*headers*" that would indicate that playback is on

This is what I got:
```

adaptive debug: Updated playlist ID https://kanlivep2event-i.akamaihd.net/hls/live/749627/749627/kanclassical_mp3/chunklist.m3u8, next update in 10s
adaptive debug: Representation https://kanlivep2event-i.akamaihd.net/hls/live/749627/749627/kanclassical_mp3/chunklist.m3u8 [mp4a]
adaptive debug:  Segment #113186 url=https://kanlivep2event-i.akamaihd.net/hls/live/749627/749627/kanclassical_mp3/b13q6ote/00000059/media_113185.ts duration 1000
adaptive debug:  Segment #113187 url=https://kanlivep2event-i.akamaihd.net/hls/live/749627/749627/kanclassical_mp3/b13q6ote/00000059/media_113186.ts stime 1000 duration 1000
adaptive debug:  Segment #113188 url=https://kanlivep2event-i.akamaihd.net/hls/live/749627/749627/kanclassical_mp3/b13q6ote/00000059/media_113187.ts stime 2001 duration 1000
adaptive debug: Retrieving https://kanlivep2event-i.akamaihd.net:443/hls/live/749627/749627/kanclassical_mp3/b13q6ote/00000059/media_113185.ts @0
```

**Comment by baruchiro** [comment]
It's too deep for me. I guess after starting to use this very cool radio, I will have needs and bugs and I will try to contribute.
