### ISSUE TITLE
HTTPS-only stations don't work

### ISSUE THREAD

**Issue by bkryza** [coderholic/pyradio#113]
Latest version of `pyradio` does not support stations, which publish PLS only through HTTPS, e.g.:

https://www.wqxr.org/stream/wqxr/mp3.pls

This is due to the fact that for each URL, scheme is unconditionally reset to `http` in `player.py`, for instance here:

https://github.com/coderholic/pyradio/blob/master/pyradio/player.py#L1097

Without these replacement HTTPS stations work fine. I'd be happy to submit a PR with a fix but I'd like to understand why `http` is forced/preferred anyway?

**Comment by s-n-g** [comment]
Well, that's not always true, it seems...

As I have seen from previous issues (#86 , #96) converting https to https is the only way to make some stations work...
Now, with your issue, I see this is not true either, so I'd say it depends on the station (redirecting to http or https, for example) and on the player used.

I am working on a workaround; adding a configuration option to either use http only or use whatever protocol the url proposes.

So, hung on...

**Comment by bkryza** [comment]
Great, thanks!

**Comment by s-n-g** [comment]
Done.
Please do have a look at **0.8.8-beta4**.
These is a configaration option regarding forcing http only, which can also be changed using "z".
Documentation in the README, section **Player connection protocol**

Hope that fixes it...

**Comment by bkryza** [comment]
@s-n-g Yes, it works fine now - thanks!
