### ISSUE TITLE
importlib.metadata.PackageNotFoundError: pyradio

### ISSUE THREAD

**Issue by HanaO00** [coderholic/pyradio#114]
Hello, i have this error
![alt text](https://files.catbox.moe/0lcolo.png)

**Comment by s-n-g** [comment]
Hi,

Can you please reinstall ```pyradio``` and post the messages shown during installation?
Also tell me what os/distro you are on.

**Comment by HanaO00** [comment]
Hello, I am under Archlinux, I reinstalled and I no longer have the error message, is it normal?

**Comment by s-n-g** [comment]
Yes, this can happen if you have updated **python** (e.g. 3.8 -> 3.9).
In this case, you have to reinstall all manually installed packages (unless installed using pacman).

**Comment by fabianski7** [comment]
@s-n-g are you the maintainer of the aur package? you should change `pkgrel` to 2, so that the user will be notified about this change

**Comment by s-n-g** [comment]
@fabianski7 done
