### ISSUE TITLE
Feature request: schedule, notifs, keybindings, and theme.

### ISSUE THREAD

**Issue by bnsv** [coderholic/pyradio#116]
Hello! I have some interesting ideas:
1. It would be really nice if there is any kind of scheduler that automatically change or play some station in certain time and day or at least throwing a notification to the desktop/menubar about incoming schedule. Example:  ~/.config/pyradio/schedule.csv
```csv
day, 24h-time, station(number/name), auto-change/notif-only
monday, 13:30, Some Station FM; auto
monday, 21:30, 23, notif-only
friday, 9:10, 3 #radio number 3; auto
```
2. Alternatively showing the notification of incoming shedule in title-bar or running-text, below the current playing like below (the "Stereogum" line in cmus player).

![Screenshot from 2020-12-11 03-33-22b](https://user-images.githubusercontent.com/25299811/101829892-4e391980-3b66-11eb-85f3-207d9848c352.png)

3. I hope pyradio binding keys is editable. I plan to replace the default binding keys to match with the cmus player. Actually I prefer pyradio binding than cmus, but cmus binding is offers much more options.

4. Last, I hope to have that green "Gruvbox" cmus theme available as an option in pyradio.

Thank you very much and sorry for my bad english.

**Comment by s-n-g** [comment]
Hi @bnsv 

Thank you for taking the time to make all these suggestions!

So, let’s see… Number 4 first…

4. Ok, I would give it a try if I could understand which theme you are referring to… There is a “green” theme, there is a “Gruvbox” theme, but a “green Gruvbox” theme, I don’t have it.

Is it one of the official themes or is it a custom one?
If it is a custom one, can you point it to me?

1. I like the idea of some kind of a scheduler, it would be nice to automatically listen to the news every hour or my favorite broadcast!

But I am afraid this is something for the future; there are other thing to be done

2. The notification will not be a problem; a “pop up window” can be used for that

3. No, the key bindings are not editable. I  suppose it could be done, but I’m not so crazy about the idea. Sorry :)

All in all, everything you have suggested are “advanced” features, way beyond **PyRadio**’s current maturity level. I mean, we don’t even have access to an online stations’ directory yet…

**Comment by bnsv** [comment]
Thank you @s-n-g 
4. Custom one, not the default pyradio green, but 'gruvbox' theme, like my cmus theme above. https://github.com/morhetz/gruvbox
1. Great! Yes we can set to automatically or manually switch station according to the schedule.
2 & 3. That's is fine.

Oh there is another. It will be great if there is an option to make pyradio automatically running (in the background; but without playing any station/stream. ie stand by) after booting/login. So the scheduler will run without manually turning pyradio on manually.

**Comment by s-n-g** [comment]
> Thank you @s-n-g
> 4. Custom one, not the default pyradio green, but 'gruvbox' theme, like my cmus theme above. https://github.com/morhetz/gruvbox
> 

Great!
I will look into it

> 1. Great! Yes we can set to automatically or manually switch station according to the schedule.
>    2 & 3. That's is fine.
> 
> Oh there is another. It will be great if there is an option to make pyradio automatically running (in the background; but without playing any station/stream. ie stand by) after booting/login. So the scheduler will run without manually turning pyradio on manually.

This will not work, I'm afraid...
Running **PyRadio** as a background process is of course possible, but then no playback is possible (the player stops when in background and resumes when coming to foreground).

That said, any scheduler would have to be running within **PyRadio**, while **PyRadio** is on the  foreground

**Comment by bnsv** [comment]
Alright then. Thank you @s-n-g . Nice work!
