### ISSUE TITLE
Mpv Not Supported

### ISSUE THREAD

**Issue by djungelskoder** [coderholic/pyradio#120]
I can't get any sound out of Pyradio.   Running it in debug mode, I see the following in the log file:

_"class pyradio.player.MpvPlayer" not supported_

I have verfied that Mpv works directly from the command line (for both Radio Paradise and CeltCast).

I have also tried installing MPlayer, but whilst I get no error messages in the log, if I try to play a station Pyradio just informs me in the status bar it can't start the player, and asks me if I've installed it.   Yes, I have, and it works from the command line.   I also rebooted after I had installed it, just in case that made a difference (it didn't).

Can you tell me what's wrong, please?   I'm running it on Ubuntu 18.04, and installed pyradio with snap.

**Comment by s-n-g** [comment]
Hi @djungelskoder 

Please do uninstall the snap you've are using and install the program from source.
Then if you still have a problem I will hopefully be able to help you

**Comment by djungelskoder** [comment]
That has fixed the problem, thank you.   But having installed it this way, how are removal and updating to later versions achieved?

**Comment by s-n-g** [comment]
Yes, I have had reports about snaps not working before...

To uninstall it, go to **pyradio** directory and execute ```devel/build_install_pyradio -u```
When a new version is available, you will be notified by the program, but you will still have to manually update.

That means that at any case you will have to get an updated copy of **pyradio** and either install (update) or uninstall it.
I would suggest you use ```git``` to install it, keep the **pyradio** folder at some place where you keep code stuff and use it to update or uninstall.

To update, it only takes this:
```
cd pyradio
git pull
devel/build_install_pyradio
```
