### ISSUE TITLE
Bluemars

### ISSUE THREAD

**Issue by djungelskoder** [coderholic/pyradio#121]
Whilst trying to solve a problem with playback, I noticed that older versions of PyRadio included Bluemars in the supplied station list.   I assume it was removed because Bluemars left the known universe.   So you might be interested to know it's been resurrected at http://echoesofbluemars.org/.   The Bluemars station list in PyRadio format is:

Echoes of Bluemars,http://streams.echoesofbluemars.org:8000/bluemars.m3u
Echoes of Bluemars - Cryosleep,http://streams.echoesofbluemars.org:8000/cryosleep.m3u
Echoes of Bluemars - Voices from Within,http://streams.echoesofbluemars.org:8000/voicesfromwithin.m3u

**Comment by s-n-g** [comment]
Thank you very much for this!
I am adding them to the playlist
