### ISSUE TITLE
Updates to stations.csv 

### ISSUE THREAD

**Issue by nrichw-eta** [coderholic/pyradio#123]
**Changes to Existing Entries**
Ragga Kings is now streaming at https://raggakings.radio:8443/stream.ogg. The M3U no longer connects.
Tag's Trance Trip - Soma FM has been renamed to The Trip. The old URL still works but it should probably be replaced with https://somafm.com/thetrip.pls in future releases.

**New(er) Soma FM Streams**
Groove Salad Classic (Early 2000s Ambient) https://somafm.com/gsclassic.pls
Heavyweight Reggae https://somafm.com/reggae.pls
Metal Detector https://somafm.com/metal.pls
Vaporwaves https://somafm.com/vaporwaves.pls
n5MD Radio (Ambient and Experimental) https://somafm.com/n5md.pls
Synphaera Radio (Space Music) https://somafm.com/synphaera.pls

**Comment by s-n-g** [comment]
Hi @nrichw-eta, thanks for the update.
Sorry it took me so long to reply.
Been super busy at work; I will have a look as soon as possible.

**Comment by s-n-g** [comment]
Done in **0.9.1**.
Thank you for the suggestions!
