### ISSUE TITLE
Low sound quality

### ISSUE THREAD

**Issue by robson-66** [coderholic/pyradio#125]
After today's update `pyradio` is playing sound very quietly. Will you take care of it?

**Comment by s-n-g** [comment]
Hi @robson-66 
I do not have any sound (quality or volume) problem here...

Maybe try a ```pyradio -d```, adjust the volume a couple of times (pressing "*,*" and "*.*") and save it (pressing "**v**")  and see if that fixes the problem.

If it does not, please do post the file created (**~/pyradio.log**) and do please clarify: do you have a poor sound quality issue or a low volume one?

**Comment by robson-66** [comment]
Thank you very much, the volume control "," helped. Now it is OK.

**Comment by s-n-g** [comment]
Ok, glad it's resolved.
Cheers!
