### ISSUE TITLE
Curses Error WMOVE

### ISSUE THREAD

**Issue by v00v** [coderholic/pyradio#128]
I've accidentally found this bug, while trying to resize a terminal in i3wm so pyradio would only take few lines. See screenshots, they are self-explanatory. But I also included the full error message bellow.

This is the smallest terminal can be, before crashing pyradio. It would be nice to have even one-line if we wanted and still see useful info like title. Oh yeah, and it wont even start pyradio if the terminal is too small.

Before Resizing Terminal:
![ss1](https://user-images.githubusercontent.com/40022654/114378632-22926400-9b45-11eb-8659-166e977302c1.png)

After Resizing Terminal:
![ss2](https://user-images.githubusercontent.com/40022654/114378629-21f9cd80-9b45-11eb-8926-96108bd8c073.png)

```sh
$ pyradio
Reading config...
Reading playlist...
Traceback (most recent call last):
  File "/usr/bin/pyradio", line 33, in <module>
    sys.exit(load_entry_point('pyradio==0.8.9', 'console_scripts', 'pyradio')())
  File "/usr/lib/python3.9/site-packages/pyradio/main.py", line 375, in shell
    curses.wrapper(pyradio.setup)
  File "/usr/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python3.9/site-packages/pyradio/radio.py", line 533, in setup
    self.run()
  File "/usr/lib/python3.9/site-packages/pyradio/radio.py", line 872, in run
    ret = self.keypress(c)
  File "/usr/lib/python3.9/site-packages/pyradio/radio.py", line 3871, in keypress
    self._normal_mode_resize()
  File "/usr/lib/python3.9/site-packages/pyradio/radio.py", line 3530, in _normal_mode_resize
    self.setupAndDrawScreen()
  File "/usr/lib/python3.9/site-packages/pyradio/radio.py", line 568, in setupAndDrawScreen
    self.initBody()
  File "/usr/lib/python3.9/site-packages/pyradio/radio.py", line 643, in initBody
    self.refreshBody()
  File "/usr/lib/python3.9/site-packages/pyradio/radio.py", line 669, in refreshBody
    self._redisplay[self._redisplay_list[n][0]]()
  File "/usr/lib/python3.9/site-packages/pyradio/radio.py", line 6076, in _redisplay_stations_and_playlists
    self.bodyWin.move(1, 1)
_curses.error: wmove() returned ERR
```

**Comment by s-n-g** [comment]
hi @v00v 

Yes, I see what you mean...
But the thing is, ```PyRadio``` was never intended to be executed in this way... It's not supposed to be a "status line" of some program or daemon running in the background.
Now, I can fix the crash, but the minimum height should be: 1 line for the header + 1 line for the status bar + 2 lines for the box + 2 lines for the stations = 6 lines. That's the bare minimum at this point.

I'm currently working on ```Radio Browser``` support, but that would add an extra line for the fields' title, so we go up to 7 lines...

Going below this, would disable much of the functionality and even make it unusable...
Changing this layout (even if it was possible to achieve what you are asking) would take too much work, which I am not prepared to do at the moment, sorry...

**Comment by v00v** [comment]
@s-n-g, I apologize if my post was confusing. But I never run it as a background process or in "status bar or "status line". I simply run it from terminal, to be more specific from Terminator (terminal). Then simply resized the height to see only few lines of pyradio so it would not take up so much room. As for how many lines, I think you should allow 1-2 lines so only title and radio channel will be visible. Because some of us prefer to see pyradio all the time while working and not send it to another workstation. And I do not care about Browser support. I really hope you make this optional and not force it. Alternative if nothing improves in pyradio in height I can just ust use nvlc <link> with that I can just do 1 line even ^_^ I really hope you allow the smallest amount of lines possible to be an option.

**Comment by s-n-g** [comment]
ok, I get your point
I will leave this issue open and look into it in the future

**Comment by s-n-g** [comment]
@v00v I got on it... :wink: 

Can you please test my devel branch?

If you have built from source, executing ```pyradio -U --sng-devel``` should install it.
If that fails, just go to https://github.com/s-n-g/pyradio anf get my ```devel``` branch.

What have I done?
PyRadio can go as low as to 1 line (showning only the status bar).
2 lines: 1 station and status bar
3 lines: playlist name, 1 station and status bar
and so on...

Give it a try and tell me how it feels

**Comment by s-n-g** [comment]
And I think I have the final version.
Simple and clean. Hope you like it
![Listener's mode](https://user-images.githubusercontent.com/5807638/114627056-4aa4d300-9cbd-11eb-8dc7-92dcee48a274.jpg)

**Comment by s-n-g** [comment]
Closed in https://github.com/coderholic/pyradio/commit/036c340b29566f8ea0442b920d02b4f0fef38c25 (Version **0.8.9.1**)
