### ISSUE TITLE
Crash on edit station

### ISSUE THREAD

**Issue by OriginalBootZ** [coderholic/pyradio#131]
When editing a station when pressing Shift + Left Arrow on either name or stationlink the edit screen is crashing the interface. In my case MPV keeps playng but I cannot control Pyradio anymore.
After a while (on new number to play) the interface is restored but rendered onusable not reacting to keys or mouse.

Regards,

BootZ

Version: 0.8.9.1 on Mabox.

Sample output on "crash".

File "/usr/lib/python3.9/site-packages/pyradio/main.py", line 375, in shell
    curses.wrapper(pyradio.setup)
  File "/usr/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/lib/python3.9/site-packages/pyradio/radio.py", line 542, in setup
    self.run()
  File "/usr/lib/python3.9/site-packages/pyradio/radio.py", line 939, in run
    ret = self.keypress(c)
  File "/usr/lib/python3.9/site-packages/pyradio/radio.py", line 4611, in keypress
    ret = self._station_editor.keypress(char)
  File "/usr/lib/python3.9/site-packages/pyradio/edit.py", line 602, in keypress
    ret = self._line_editor[self._focus].keypress(self._win, char)
  File "/usr/lib/python3.9/site-packages/pyradio/simple_curses_widgets.py", line 1664, in keypress
    char = self._get_char(win, char)
  File "/usr/lib/python3.9/site-packages/pyradio/simple_curses_widgets.py", line 1741, in _get_char
    if is_wide(out) and not self._cjk:
  File "/usr/lib/python3.9/site-packages/pyradio/cjkwrap.py", line 46, in is_wide
    return unicodedata.east_asian_width(char) in ('F', 'W')
TypeError: east_asian_width() argument must be a unicode character, not str

**Comment by s-n-g** [comment]
Hi BootZ!

I am afraid I cannot reproduce this crash...

Does this happen with every station you try to edit?
Can you please execute the following and post the file `~/pyradio.log` here?

```
cd
rm -rf pyradio.log
pyradio -d
```

BTW, why are you pressing Shift-Left Arrow? Is it a terminal shortcut?
If yes, can you please try running **PyRadaio** on a different terminal and check its behaviour?

You see, the crash happens on the **cjkwrap** library:  https://gitlab.com/fgallaire/cjkwrap/-/blob/master/cjkwrap.py#L46 not on **PyRadio**'s "own" code...

Regards
S.

**Comment by s-n-g** [comment]
Hi again BootZ

I think I got it, so please disregard me previous post and just go on and execute

```
pyradio -U --sng-devel
```

and check if you still have the crash

**Comment by OriginalBootZ** [comment]
> Hi again BootZ
> 
> I think I got it, so please disregard my previous post and just go on and execute
> 
> ```
> pyradio -U --sng-devel
> ```
> 
> and check if you still have the crash

Hi,

That's not possible because I installed it via the Mabox repo so upgrading is not possible via this way.

Regards,

BootZ

**Comment by s-n-g** [comment]
Yes, sorry, my bad...

Ok, so you just

```
sudo pacman -R pyradio
cd
curl -L https://raw.githubusercontent.com/coderholic/pyradio/master/pyradio/install.py -o install.py
python install.py --sng-devel
```

When you are done with testing, you just re-install Mabox package

```
pyradio -R
sudo pacman -S pyradio
```

And you are back to where you started :)
S.

**Comment by OriginalBootZ** [comment]
Hi,

Sadly I'm not able to test at the moment as I'm on Ubuntu 21.04 testing that. However I installed pyradio from the snap store and it has the same behavior. If I can test on Ubuntu for you then please let me know.

**Comment by s-n-g** [comment]
Ok then, on ubuntu, you just uninstall the snap you have already installed.

Then on a terminal:
1. if you have `curl` installed

```
cd
curl -L https://raw.githubusercontent.com/coderholic/pyradio/master/pyradio/install.py -o install.py
python install.py --sng-devel
```

2. or if you have `wget` installed

```
cd
wget https://raw.githubusercontent.com/coderholic/pyradio/master/pyradio/install.py
python install.py --sng-devel
```

Then you just test it and when you are done, you just uninstall it

```
pyradio -R
```

and install snap again

**Comment by OriginalBootZ** [comment]
Hi,

Had to install a bunch of dependencies to install (wget, python3 setuptools) but got it to work. The "crash" behavior is indeed fixed.
I'll keep on using this for a while as the snap version doesn't want to play on the installed player engines (none)
Thanks for the help in this!

Regards,

BootZ

**Comment by s-n-g** [comment]
Ok BootZ

thank you for testing this one out!

Yes, you just keep this version until you get a notification on `mabox` about a new version released.

Thanks
S.
