### ISSUE TITLE
Stations play while connecting then drop out after retry time

### ISSUE THREAD

**Issue by nrichw-eta** [coderholic/pyradio#132]
OS: Linux Mint XFCE 20.1 
Arch: x86_64
Kernel: 5.4.0-72-generic 
Pyradio Version: 0.8.9.1

I've been encountering a peculiar problem since last week. The first station I play when I start up pyradio works fine, but if I switch to another it starts playing while the "Connecting to:..." status is still displaying. Pyradio doesn't seem to recognize that the station is there, so it times out, at which point the audio stops playing. It keeps doing that with each new station I switch to until I restart the program where the cycle begins anew.

**Comment by s-n-g** [comment]
Hi @nrichw-eta 

Now, that's a very strange bahaviour you have over there :)

May I ask? How did you install `pyradio`?

In any case, please do run the following:

```
pyradio -d
```

Play around with it a bit (start and stop playback) and exit it.
It will create a file called `~/pyradio.log`
Please do post it here; it may help us to find out wht's wrong.

S.

**Comment by nrichw-eta** [comment]
My first pyradio installation was from source, thought I did reinstall pyradio to if updating to 0.8.9.1 with `pyradio -U` caused the issue in the first place. It doesn't seem to have solved the problem at all.  However, installing and switching to mplayer so far has seemed to have cleared up the issue.


[pyradio.log - taken before installing mplayer](https://github.com/coderholic/pyradio/files/6446510/pyradio.log)
[pyradio.log - includes sessions after installing mplayer](https://github.com/coderholic/pyradio/files/6446535/pyradio.log)

**Comment by nrichw-eta** [comment]
I've found the problem! The mpv add-on scripts I downloaded for my Celluloid installation were messing up mpv's ability to notice the stream, especially a Lua one called MpvSockets. Thank you for helping me!

**Comment by s-n-g** [comment]
You are welcome @nrichw-eta 
Glad I could help and you finally figured it out!
