### ISSUE TITLE
Can not update from 0.8.9.8 to 0.8.9.9...

### ISSUE THREAD

**Issue by dl9sec** [coderholic/pyradio#136]
Hi,

I tried to update pyradio:

    # pyradio -U
    Released version   :  0.8.9.9
    Installed version  :  0.8.9.8
    Updating PyRadio...
    Using directory: "/tmp/tmp-pyradio"
    Downloading PyRadio source code...
    Extracting RyRadio source code...
    Uninstalling PyRadio
    ** Removing executable ... done
    ** Removing help files ... done
    Looking for python installed files...
    PyRadio successfully uninstalled
    Traceback (most recent call last):
      File "setup.py", line 5, in <module>
        from setuptools import setup, find_packages
    ModuleNotFoundError: No module named 'setuptools'
    
    
    PyRadio updated to the latest release!
    Thank you for your continuous support to this project!
    Cheers!

setuptools-44.1.1 is installed.

Any ideas, what happened?

TIA

Regards, Thorsten

**Comment by s-n-g** [comment]
That's strange...

Have you updates python lately?

**Comment by dl9sec** [comment]
> Have you updated python lately?

Just regular updates via apt update...
 
> ```
> wget https://raw.githubusercontent.com/coderholic/pyradio/master/pyradio/install.py
> python install.py
> ```
> 
> Depending on your situation, you may have to add `--force` to the last command...

Python 2.7.16 and Python 3.7.3 are installed and the corresponding setuptools 44.1.1 (for 2.7) and 58.0.4 (for 3.7).
When I execute the install.py (without or with `--force`, I get

    Traceback (most recent call last):
      File "install.py", line 28, in <module>
        except ModuleNotFoundError:
    NameError: name 'ModuleNotFoundError' is not defined

> Also, if you are on a Debian based distro, you may have to check which version of python your installed `setuptools` corresponds to...

Yes, I am on a Debian Buster. setuptools version see above...

**Comment by dl9sec** [comment]
Ok, followed the "Preparing for installation" and executes `python3 install.py --force`.
That seemed to work:

    ...
    Finished processing dependencies for pyradio==0.8.9.9
    
    
    PyRadio succesfully installed!
    Hope you have a lot of fun using it!
    Cheers!

But if I start pyradio it shows 0.8.9.8 in the upper left corner.

Can I manually delete all the pyradio stuff to start a clean installation again?

**Comment by s-n-g** [comment]
You'd better go with 
```
python3 install.py -R
```
first and then check 

    ls -d /usr/lib/python*/site-packages/pyradio
    ls -d /usr/lib/python*/site-packages/pyradio-*

shows nothing.

If anything is there, delete them

Then 

    python3 install.py --force

Hope that helps

S.

**Comment by s-n-g** [comment]
On Debian 11, here's where the package is installed

    /usr/loca/lib/python3.9/dist-packages/pyradio-0.8.9.9-py3.9-egg
    
You should replace **3.9** with **3.7** and **2.7.** and check there's nothing there

**Comment by dl9sec** [comment]
Ok, solved. Uninstalled and deleted all pyradio stuff and made a clean install. Now it works fine.
Seems, that there was a mix between an installation from the sources and an installation through installer script (to be honest I can't remember, how I did the first installation...).
Thank you very much for the assistance...

Regards, Thorsten

**Comment by s-n-g** [comment]
ok, glad you figured it out!
S.
