### ISSUE TITLE
feat: remember last opened playlist upon Pyradio exit

### ISSUE THREAD

**Issue by jirikrepl** [coderholic/pyradio#138]
Hello, I think it would be nice if Pyradio remembered the last open playlist.
In my use case, I have 4 playlists and I use one the most.

This might be added as a configurable option.
If this option is enabled. then Pyradio will always start with the last opened playlist.

**Comment by s-n-g** [comment]
I like this idea!
Yes, a config option will be the way to go, working on it
Thsnks!

**Comment by s-n-g** [comment]
hi again @jirikrepl
I have just uploaded the "last opened playlist" functionality.
Can you please check it out and report back?
S.

**Comment by jirikrepl** [comment]
Great! thanks, I tested it today with `python3 install.py --git` which installed 0.8.9.9-r11.
I enabled the option in the config, and it seems to be working fine:)

**Comment by s-n-g** [comment]
Great @jirikrepl 
Closing this one then...
