### ISSUE TITLE
cannot edit theme from tui

### ISSUE THREAD

**Issue by mariorossi77** [coderholic/pyradio#141]
open the theme editor with T
press E to edit a theme
tui asks to press Y to proceed
*press Y*
nothing happens

**Comment by s-n-g** [comment]
Hi @kusky3 

Yes, this one somehow slipped in there when I stopped working on theme editing...

So, theme editing (and creating) is disabled for now; actually the whome theming scheme will probably change in the future, so...

I will just disable the whole thing with my next commit.
Thanks fore reporting it!

**Comment by s-n-g** [comment]
Disabled in https://github.com/coderholic/pyradio/commit/6a123a2b09b8907170d7f1e1b3359575f1b46e67
