### ISSUE TITLE
problem with play of NDR 2

### ISSUE THREAD

**Issue by jirikrepl** [coderholic/pyradio#143]
Hello @coderholic , I cannot play NDR 2 radio stream in my Pyradio.

I took a link from network tab from my browser on TuneIn radio page
https://tunein.com/radio/NDR-2-Niedersachsen-962-s56857/

This is the radio link:
http://f121.rndfnk.com/ard/ndr/ndr2/niedersachsen/mp3/128/stream.mp3?aggregator=tunein&sid=21wv6GtqbgqcjhD3kqcJKuljR3u&token=hZcMpEWoSwNAIM_u80TTUy0mo9qHB6OV6ATya4ik0m8&tvf=SDJYJHx-vhZmMTIxLnJuZGZuay5jb20

Link works fine in browser and also in standalone VLC player (if I add it via file -> add network)

But if I add it into Pyradio all 3 players cannot play this url, is there some maybe to enable debugging in Pyradio?

**Comment by jirikrepl** [comment]
Maybe isn't Pyradio stripping the url parameters (aggregator, sid and token in this case)? The stream needs all 3 of them, otherwise it won't play

**Comment by s-n-g** [comment]
Hi @jirikrepl 
Before you paste the URL, please press \p
Then paste the URL and save the station.

Now it should be playing ok

**Comment by jirikrepl** [comment]
Hi @coderholic,

thank you for your answer. Got it, now I see this also in Readme.md https://github.com/coderholic/pyradio#line-editor

Maybe it would be a good idea to put some note about this paste mode \p in a help of stations editor

**Comment by s-n-g** [comment]
Yes, that's not a bad idea actually!
Cheers!
