### ISSUE TITLE
Many stations have a slight distortion to their audio

### ISSUE THREAD

**Issue by jim3** [coderholic/pyradio#144]
I am not sure if this is a mplayer setting within the app or not. I have tried simply mplayer by itself, Shortwave which uses a gui for the same radio api (it has an issue as well, stuttering audio every minute or so) and they are not producing the slight distortion I am hearing on many/most of the tracks. I wonder if this is an radio-browser api thing? Especially since I have issue with Shortwave as well? Mplayer alone isn't having the issue that I can tell. It's weird...

What are some things I could try to see if this can be fixed. I waited 2 weeks before I wanted to post anything b/c I was thinking it was something with the soundcard but so far I cannot find anything liek that on my end. If I listen to the same audio on another app I am not experiencing this.  

FWIW, this is one of my favorite music apps so I am determined to figure out whatever might be causing the issue.

**Comment by s-n-g** [comment]
Hi @jim3 

Stations' playback is done solely by the selected player.

**PyRadio** has no code to reproduce music

Furthermore, any api used (either a local playlist or RadioBrowser) will essentially just provide a URL to be passed to the selected player. Nothing to do with sound manipulation; it's all up to the player to get the data and produce sound.

You say you are using `mplayer`; why don't you try using a different player?

For example: `pyradio -u mpv` or `pyradio -u clv`

You can see the command executed when you start playing a station like so:

1. Start by executing `pyradio -d` (or `pyradio -d -u mpv` or `pyradio -d -u clv`)
2. Open a new terminal and execute `tail -f ~/pyradio.log`
3. Start playing a station

You will seel a line like this one:

**mpv**
```
2021-12-16 11:28:54,488 - pyradio.player - INFO - Executing command: mpv --no-video --quiet http://ice64.securenetsystems.net/WKHR --input-ipc-server=/tmp/mpvsocket.19563 --profile=test
```

**mplayer**
```
2021-12-16 11:29:45,902 - pyradio.player - INFO - Executing command: mplayer -vo null -quiet -profile pyradio http://ice64.securenetsystems.net/WKHR
```

**vlc**
```
2021-12-16 11:31:20,463 - pyradio.player - INFO - Executing command: cvlc -Irc -vv http://ice64.securenetsystems.net/WKHR
```

4. If using `mpv` do not close `pyradio`
5. execute the command found in a terminal and check to see what happens

**Comment by jim3** [comment]
mplayer is the issue. I should have thought to use a different player. :/ Using mpv cli and the streams are flawless and crystal clear. That being said, pyradio isn't recognizing mpv or vlc, only mplayer. I installed via snap so maybe that could be the issue as it can cause issues with paths I think. 

I'll close this though and do some searching on why and how to fix it. Thanks for help, I finaly have proper audio again! 👍🏻
