### ISSUE TITLE
Installation fails on first attempt in Windows

### ISSUE THREAD

**Issue by naryfa** [coderholic/pyradio#145]
The first installation attempt fails with the below, saying that the PyRadio is still running. If I start the installation again it completes successfully.

Defaulting to user installation because normal site-packages is not writeable
Collecting windows-curses
  Downloading windows_curses-2.3.0-cp310-cp310-win_amd64.whl (88 kB)
     |████████████████████████████████| 88 kB 3.7 MB/s
Installing collected packages: windows-curses
Successfully installed windows-curses-2.3.0
Defaulting to user installation because normal site-packages is not writeable
Collecting pywin32
  Downloading pywin32-303-cp310-cp310-win_amd64.whl (9.2 MB)
     |████████████████████████████████| 9.2 MB ...
Installing collected packages: pywin32
Successfully installed pywin32-303
Defaulting to user installation because normal site-packages is not writeable
Collecting requests
  Using cached requests-2.26.0-py2.py3-none-any.whl (62 kB)
Collecting charset-normalizer~=2.0.0
  Downloading charset_normalizer-2.0.9-py3-none-any.whl (39 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.3-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB ...
Collecting certifi>=2017.4.17
  Using cached certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2021.10.8 charset-normalizer-2.0.9 idna-3.3 requests-2.26.0 urllib3-1.26.7
PyRadio is still running. Please terminate it to continue ...
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Python\Python310\Scripts\install.py", line 266, in WindowExists
    win32ui.FindWindow(None, title)
NameError: name 'win32ui' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Python\Python310\Scripts\install.py", line 894, in <module>
    uni.update_or_uninstall_on_windows(mode='update-open')
  File "C:\Users\admin\AppData\Roaming\Python\Python310\Scripts\install.py", line 450, in update_or_uninstall_on_windows
    isRunning()
  File "C:\Users\admin\AppData\Roaming\Python\Python310\Scripts\install.py", line 92, in isRunning
    while WindowExists('PyRadio: Your Internet Radio Player') or \
  File "C:\Users\admin\AppData\Roaming\Python\Python310\Scripts\install.py", line 267, in WindowExists
    except win32ui.error:
NameError: name 'win32ui' is not defined

**Comment by s-n-g** [comment]
Hi @naryfa 

Happy New Year!

Thanks for reporting this one

I will test this on a fresh windows installation and see what's wrong...
It seems `win32ui` is not installed?

**Comment by s-n-g** [comment]
ok, got it...

I will leave this open though untill the next release is up, just for reference

Tahnk you again for reporting it!

**Comment by naryfa** [comment]
I'm sorry I am late to reply.  All Python options were selected during the installation, so I'd assume win32ui got pulled in as well. Perhaps I'm incorrect, or my setup is somewhat unique.

**Comment by s-n-g** [comment]
Hi @naryfa 

No, it's not your problem.

What happens is the installation scripts tries to import the module before it is installed, and silently fails.
The fix is to insert it right before using it (which happens after it is installed)

So, this will hopefully fix this issue once and for all :wink:

**Comment by naryfa** [comment]
Sounds good. Thank you for checking it out.

**Comment by s-n-g** [comment]
This one has been fixed for some time now.
Closing it...
