### ISSUE TITLE
Compiling/build error with arch

### ISSUE THREAD

**Issue by weirdo67** [coderholic/pyradio#146]
I've got all the required dependencies installed, I've tried compiling it myself but got same issue
`Installing PyRadio...
Using directory: "/tmp/tmp-pyradio"
Downloading PyRadio source code...
  url: "https://github.com/coderholic/pyradio/archive/0.8.9.9.zip"
  filename: "/tmp/tmp-pyradio/pyradio-0.8.9.9.zip"
Extracting RyRadio source code...
Uninstalling PyRadio
which: no pyradio in (/home/fuck/.local/bin:/home/fuck/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
** Removing executable ... which: no pyradio in (/home/fuck/.local/bin:/home/fuck/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl)
done
** Removing help files ... done
Looking for python installed files...
PyRadio successfully uninstalled
running build
running build_py
creating build
creating build/lib
creating build/lib/pyradio
copying pyradio/radio.py -> build/lib/pyradio
copying pyradio/window_stack.py -> build/lib/pyradio
copying pyradio/themes.py -> build/lib/pyradio
copying pyradio/simple_curses_widgets.py -> build/lib/pyradio
copying pyradio/player.py -> build/lib/pyradio
copying pyradio/main.py -> build/lib/pyradio
copying pyradio/log.py -> build/lib/pyradio
copying pyradio/install.py -> build/lib/pyradio
copying pyradio/encodings.py -> build/lib/pyradio
copying pyradio/edit.py -> build/lib/pyradio
copying pyradio/del_vlc_log.py -> build/lib/pyradio
copying pyradio/countries.py -> build/lib/pyradio
copying pyradio/config_window.py -> build/lib/pyradio
copying pyradio/config.py -> build/lib/pyradio
copying pyradio/compare_files.py -> build/lib/pyradio
copying pyradio/common.py -> build/lib/pyradio
copying pyradio/cjkwrap.py -> build/lib/pyradio
copying pyradio/browser.py -> build/lib/pyradio
copying pyradio/__init__.py -> build/lib/pyradio
running egg_info
creating pyradio.egg-info
writing pyradio.egg-info/PKG-INFO
Traceback (most recent call last):
  File "/tmp/tmp-pyradio/pyradio-0.8.9.9/setup.py", line 45, in <module>
    setup(**meta)
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 46, in run
    self.build_package_data()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 113, in build_package_data
    for package, src_dir, build_dir, filenames in self.data_files:
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 55, in __getattr__
    self.data_files = self._get_data_files()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 67, in _get_data_files
    self.analyze_manifest()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 131, in analyze_manifest
    self.run_command('egg_info')
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 292, in run
    writer(self, ep.name, os.path.join(self.egg_info, ep.name))
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 656, in write_pkg_info
    metadata.write_pkg_info(cmd.egg_info)
  File "/usr/lib/python3.10/distutils/dist.py", line 1117, in write_pkg_info
    self.write_pkg_file(pkg_info)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 167, in write_pkg_file
    write_field('Summary', single_line(self.get_description()))
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 151, in single_line
    raise ValueError('Newlines are not allowed')
ValueError: Newlines are not allowed

PyRadio succesfully installed!
Hope you have a lot of fun using it!
Cheers!
`

It says succesfully installed, however its not and does not work.
The AUR has same issue, however does not say its been successfully installed.

**Comment by s-n-g** [comment]
Hi @weirdo67 

I have just installed it from AUR, no problem there...
Have a look: https://u.pcloud.link/publink/show?code=XZU6e3XZX5q77AfcPJhmNpRoe3xuG44AJgmX

I will check it on a fresh installation on libvirt, but I don't think this is a `pyradio` problem...

Are you sure your `python` installation is correct?

**Comment by s-n-g** [comment]
Hi again @weirdo67 

On a fresh arch installation, I have the same error as you...

**Comment by s-n-g** [comment]
I am currently not at home, so I cannot test this, but...

I found a similar issue: https://github.com/pypa/setuptools/issues/2893

So, can you please try replacing

```
meta = dict(
    name=__project__,
    version=version,
    license=__license__,
    description=read('DESCRIPTION'),
    long_description=read('README.md'),
    platforms=('Any'),
    author='Ben Dowling',
    author_email='ben.m.dowling@gmail.com',
    url=' http://github.com/coderholic/pyradio',
    packages=find_packages(),
    include_package_data=True,
    entry_points={
        'console_scripts': [
            'pyradio = pyradio.main:shell',
        ]
    },
    install_requires=install_requires,
    test_suite = 'tests',
)
```

with

```
meta = dict(
    name=__project__,
    version=version,
    license=__license__,
    description=read('DESCRIPTION'),
    platforms=('Any'),
    author='Ben Dowling',
    author_email='ben.m.dowling@gmail.com',
    url=' http://github.com/coderholic/pyradio',
    packages=find_packages(),
    include_package_data=True,
    entry_points={'console_scripts': ['pyradio = pyradio.main:shell',]},
    install_requires=install_requires,
    test_suite = 'tests',
)
```

in setup.py and try to build it again?

**Comment by willemw12** [comment]
It builds when commenting out `description=read('DESCRIPTION')` in the original setup.py file.

(
As a general comment: there is a deprecation warning:

    /usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.

)

**Comment by willemw12** [comment]
Adding `.strip()` or `.rstrip()` is a possible fix:

    description=read('DESCRIPTION').rstrip(),

**Comment by s-n-g** [comment]
> It builds when commenting out `description=read('DESCRIPTION')` in the original setup.py file.
> 

It seems this is a problem of setuptools 59.1.
The **error** went back to a *warning* in 59.4


> ( As a general comment: there is a deprecation warning:
> 
> ```
> /usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
> ```

Thanks for reporting this one!
I have never noticed!
I will look into it

Cheers!

**Comment by s-n-g** [comment]
> Adding `.strip()` or `.rstrip()` is a possible fix:
> 
> ```
> description=read('DESCRIPTION').rstrip(),
> ```

Yes, I was thinking of something like that too.
I will test it when I get home

**Comment by willemw12** [comment]
It is a possible solution that has been tested and works, if that was not clear.

**Comment by s-n-g** [comment]
Just checked it on a fresh `arch` installation and it's now ok!
Closing...
