### ISSUE TITLE
Cannot type letter 't' in radio browser search form

### ISSUE THREAD

**Issue by RaeedAhmed** [coderholic/pyradio#147]
Entering the radio browser with 'O' form the default menu and then searching with 's', under "Search for [Name]", typing the letter 't' causes the themes menu to pop up. Every other letter works. I also tried copy/pasting my search query and the theme menu would pop up regardless, with the search entry incomplete. The example query being 'Newtown Radio':
![View](https://user-images.githubusercontent.com/47267335/151010845-f3486158-aab0-46a9-b9c0-1f64d658289d.png)

**Comment by s-n-g** [comment]
Fixed in https://github.com/coderholic/pyradio/releases/tag/0.8.9.11

Thank you for reporting this!
