### ISSUE TITLE
Flags -p and --play don't work in latest pip version (0.5.2) for running a specific station

### ISSUE THREAD

**Issue by taoteh1221** [coderholic/pyradio#149]
v0.5.2 installed via pip on "Raspbian GNU/Linux 11 (bullseye)" (raspi os lite...pyradio installed as user, not root).

pyradio --play 1 or pyradio -p 1 doesn't work. It will always play any random station in the playlist. 

Additionally, i does not work for station info, and the info section at the bottom just says "starting playback" even though playback already successfully started a long time before:
![Screenshot from 2022-03-15 00-11-00](https://user-images.githubusercontent.com/1760489/158305626-06939aad-a03b-4f28-948b-fe5f239e5c8a.png)

**Comment by taoteh1221** [comment]
Funny thing is, if I set it to pyradio --play 0, it loads the first playlist every time.

**Comment by taoteh1221** [comment]
Sorry, forgot the python version: Python 3.9.2

**Comment by taoteh1221** [comment]
Just realized I had previously installed via install.py. That version works great. The pip version not so much.

**Comment by s-n-g** [comment]
Hi @taoteh1221 

Please do not use the **pip version**, it is very old and not updated...
Just follow the instructions on https://github.com/coderholic/pyradio/blob/master/build.md

**Comment by taoteh1221** [comment]
Will do, thanks very much @s-n-g ! 🙂

**Comment by taoteh1221** [comment]
@s-n-g I figured maybe you'd find it interesting I'm using your pyradio app as the player for this automated bash script I built (fully headless bluetooth radio setup from a fresh OS image on SOC devices): https://github.com/taoteh1221/Bluetooth_Internet_Radio

You all are doing a great job on pyradio, it was a no-brainer picking it for my automated setup script.

**Comment by s-n-g** [comment]
@taoteh1221 This sounds really interesting!
I will surely have a look at it!

**Comment by s-n-g** [comment]
Just a couple of suggestions (I just had a quick look):

It'd be better to use **python3** for PyRadio (I believe Debian still uses *python2* for *python* by default, correct me if I'm wong here).

You probably should chage this one
```
sudo pip install setuptools requests dnspython psutil
```
to
```
python3 -m pip install wheel setuptools requests dnspython psutil
```
(adding **wheel** to installed modules)

If you have to have these modules installed system-wide, use **sudo apt install ...** (using *pip* with *sudo* is not a good practice, and will create problems along the way; conflict between distro packages and pip packages)

**Comment by taoteh1221** [comment]
Thanks @s-n-g, I appreciate the insight here. I had just made this commit guessing at this before reading your response, because I'm getting BIGTIME python error issues with dietpi on a radxa zero, testing SOCs (raspi os handles this alot more gracefully): https://github.com/taoteh1221/Bluetooth_Internet_Radio/commit/5c0921a5723cedc5b9ddeda51b4895bc50b4e5bb

I'm guessing it's flipping out because I'm unknowingly calling python2. Will change to you suggestion after some rest, thank you again. I don't have a clue about python.

**Comment by s-n-g** [comment]
Hi @taoteh1221 

I have just created a PR for you converting everything to **python3**

I have also changed to [MPV](https://mpv.io) as I think it's more stable than mplayer for **PyRadio**

The only thing you have to do is make sure no system-wide modules are left installled in your system

## For python (python2)
```
python -m pip list
```

will show you all pip installed modules, and

```
python -m pip list --user
```

will show you all pip installed modules as **user**

For any module that is not in the **--user** command output, you should

```
sudp python -m pip uninstall [module] -y
```

## For python3

Same thing, just replace **python** with **python3**

**Comment by taoteh1221** [comment]
Sweet, thanks so much @s-n-g , just merged it.

I just checked, I installed alot of python3 modules as system-wide. lol I had no idea user install was preferred, good to know.

![Screenshot from 2022-03-19 18-06-14](https://user-images.githubusercontent.com/1760489/159140038-b9c9263f-91f0-4186-bc37-63e4488b2a32.png)

**Comment by taoteh1221** [comment]
I noticed you removed the chmod +x for install.py after the wget download in my install logic. Do python files run ok not set as executable?

**Comment by s-n-g** [comment]
> I noticed you removed the chmod +x for install.py after the wget download in my install logic. Do python files run ok not set as executable?

No you do not when running `python install.py`; python is already executable and knows how to open the file passed as an argument.

Now, if you have a single script, you can add "**#!/usr/bin/env python3**" (shebang) at the begining of the file; this is when you have to make it executable.

Hope this is clear :)

**Comment by taoteh1221** [comment]
> When running `python3 install.py` you do not have to make it executable; python is already executable and knows how to open the file passed as an argument.
> 
> Now, if you have a single script, you can add "**#!/usr/bin/env python3**" (shebang) at the begining of the file; this is when you have to make it executable.
> 
Ah, I see now. :+1: Makes sense.
