### ISSUE TITLE
Connection fails with mpv, but works fine with mplayer

### ISSUE THREAD

**Issue by taoteh1221** [coderholic/pyradio#150]
OS: Raspberry Pi OS lite (latest, on a pi zero w)

Pyradio v0.8.9.16

All dependencies installed that you included in your PR ( https://github.com/taoteh1221/Bluetooth_Internet_Radio/pull/2 ), using that script.

If I run pyradio, it says its using mpv, additionally `which mpv` tells me the binary exists OK on the system. But pyradio says `connecting to...`, and then it says `connection failed` when using mpv.

If I remove mpv from the system, and install mplayer instead, pyradio works OK, everything plays as expected, no problems.

Additionally (before un-installing mpv with apt), when I was in pyradio, I hit the `c` key, unchecked `mpv` checkbox, hit the `s` key, closed and restarted pyradio, but `mpv` was still selected with a checkmark when I opened the config window?

**Comment by taoteh1221** [comment]
Additionally, this was done on a brand new install of Raspberry Pi OS lite. I did not do any customization to this operating system besides install all pulseaudio and pyradio packages and dependencies.

**Comment by taoteh1221** [comment]
One other thing, I had mplayer AND mpv installed at the same time. I don't know if that could have affected anything. When I uninstalled mpv everything worked ok.

**Comment by s-n-g** [comment]
> OS: Raspberry Pi OS lite (latest, on a pi zero w)
> 
> Pyradio v0.8.9.16
> 
> All dependencies installed that you included in your PR ( [taoteh1221/Bluetooth_Internet_Radio#2](https://github.com/taoteh1221/Bluetooth_Internet_Radio/pull/2) ), using that script.
> 
> If I run pyradio, it says its using mpv, additionally `which mpv` tells me the binary exists OK on the system. But pyradio says `connecting to...`, and then it says `connection failed` when using mpv.
> 
> If I remove mpv from the system, and install mplayer instead, pyradio works OK, everything plays as expected, no problems.

Hm, I think I may have an idea...
Get into the setup (press **c**) and increase "**Connection timeout**".
I think this will fix it

**Comment by s-n-g** [comment]
> Additionally (before un-installing mpv with apt), when I was in pyradio, I hit the `c` key, unchecked `mpv` checkbox, hit the `s` key, closed and restarted pyradio, but `mpv` was still selected with a checkmark when I opened the config window?

This should not be happening...
Have you pressed **c** once or twice?

**Comment by taoteh1221** [comment]
> Hm, I think I may have understood what's happening... There is a 10 seconds timeout (7 seconds countdown), right? Get into the setup (press **c**), increase "**Connection timeout**" and press "**s**". I think this will fix it
> 
> BTW, since you are on a Raspberry, can you please execute the folowing and send me the output?
> 
> ```
> for n in s n r v m p i o;do echo -n "$n : "; uname -$n;done
> ```
> 
> If we can detect it, I can change the default connection timeout during installation (or first run)...

```
s : Linux
n : raspberrypi
r : 5.10.103+
v : #1530 Tue Mar 8 13:00:30 GMT 2022
m : armv6l
p : unknown
i : unknown
o : GNU/Linux
```
Yes, setting the timeout to 20 seconds solved the problem, mpv now works. mpv volume is low compared to mplayer though, I wonder how mpv sets its volume?

**Comment by taoteh1221** [comment]
> > Additionally (before un-installing mpv with apt), when I was in pyradio, I hit the `c` key, unchecked `mpv` checkbox, hit the `s` key, closed and restarted pyradio, but `mpv` was still selected with a checkmark when I opened the config window?
> 
> This should not be happening... Have you pressed "**s**" once or twice?

Ah, sorry. Yes, pressing `s` twice does work. I did not notice this before (that it did not save since I was just back to the main config window after pressing `s` once).

**Comment by taoteh1221** [comment]
> Yes, setting the timeout to 20 seconds solved the problem, mpv now works. mpv volume is low compared to mplayer though, I wonder how mpv sets its volume?

I found the problem with mpv volume, looks like it set to 50% as the default setting in ~/.config/mpv/mpv.conf on raspberrypi os:

![Screenshot from 2022-03-20 16-28-10](https://user-images.githubusercontent.com/1760489/159184731-60aa3890-5722-4d22-ade0-23e157821110.png)

**Comment by s-n-g** [comment]
You can adjust the volume with **+** / **-** (or **,** / **.**) and press **v** to save it...

Pressing "**?**" wil display the help, it's all there :)

**Comment by taoteh1221** [comment]
Thanks for the info. I fixed mpv default volume to 100 everytime my script runs pyradio:
`sed -i 's/volume=.*/volume=100/g' ~/.config/mpv/mpv.conf`

**Comment by taoteh1221** [comment]
And default timeout to 20:
`sed -i 's/connection_timeout = .*/connection_timeout = 20/g' ~/.config/pyradio/config`
:)

**Comment by s-n-g** [comment]
Yes, that's just what I had in mind... but I'd like to do it in pryradio installation if I can safely detect I'm on a Raspberry.

So I see that `uname -m` gives me `armv6l`. But tht's not enought to be sure I'm on a Raspberry...
Can you think of anything else I could check to make sure I'm not on some other type of arm machine?

**Comment by s-n-g** [comment]
BTW, please make sure that these `sed` commands are executed **after** the files are created (after pyradio has been executed at least once).

**Comment by taoteh1221** [comment]
> 

Yes, this is a sure way to check for raspi-config, located here: `/usr/bin/raspi-config`

**Comment by s-n-g** [comment]
> > 
> 
> Yes, this is a sure way to check for raspi-config, located here: `/usr/bin/raspi-config`

This is great!
Is this the case for every distro?
Please keep in mind I know absolutely nothing about the Raspberry world :)

**Comment by taoteh1221** [comment]
> BTW, please make sure that these `sed` commands are executed **after** the files are created (after pyradio has been executed at least once), or exist beforehand.

:+1: https://github.com/taoteh1221/Bluetooth_Internet_Radio/blob/main/bt-radio-setup.bash#L1151

**Comment by taoteh1221** [comment]
> 

raspi-config is a part of all "Raspberry Pi OS" distro versions: https://www.raspberrypi.com/documentation/computers/configuration.html#:~:text=The%20raspi%2Dconfig%20Tool,-Edit%20this%20on%20GitHub

As for alternative distros that run on a raspberrypi, I don't know how easily you could tell.

**Comment by taoteh1221** [comment]
@s-n-g I just realized that mpv crashes a raspberry pi zero (leaving it completely unresponsive) after running for a few hours. This happened a couple times in a row. mplayer in pyradio does not crash the device though (I have run it all day for weeks without a problem). So here is some logic you could port to python for raspi devices: https://github.com/taoteh1221/Bluetooth_Internet_Radio/blob/main/bt-radio-setup.bash#L1169

**Comment by s-n-g** [comment]
Hi again @taoteh1221 

No, I think it's not worth it...

I am sorry I lead you astray on this one...

It seems you should dump `mpv` alltogether, and stick to `mplayer`, since it does not cause you problems.
So, I would suggest reverting everything related to `mpv` to what it was before I gave you my "wise" :cry: advice.

Just keep the stuff about `python 3` though...

Sorry again...

**Comment by s-n-g** [comment]
Yeah, I updated the comment, after you read it (it seems)...

**Comment by taoteh1221** [comment]
> It seems you should dump `mpv` alltogether, and stick to `mplayer`, since it does not cause you problems. So, I would suggest reverting everything related to `mpv` to what it was before I gave you my "wise" cry advice.
> 
> Just keep the stuff about `python 3` though...
> 
> Sorry again...

Ok, no worries I appreciate your help! :smile: I was just giving you some feedback to help with pyradio UX on raspberry pi devices. I do not think there is anyway you could have known a tiny computer like this would not run mpv well: https://www.raspberrypi.com/products/raspberry-pi-zero/

pyradio does run very well with mplayer on the raspberry pi zero though, I have been using it that way for weeks. :smile:

**Comment by s-n-g** [comment]
> I am curious as to why the issue

The only reason I can think of is that maybe this particular board is not strong enough to handle constantly opening and closing pipes... IDK...

I've had other people asking about rasberry and `mpv` (facing problems with the timeout value), but never anything like crashes and such...

Anyway, I think I'll be closing this issue now, feel free to contact me if anything else pops up :smile:

**Comment by taoteh1221** [comment]
Ok. Thanks for the PR and insight, it was very helpful! :smile: Most people may use a more powerful pi, the zero model is the weakest chipset...maybe why you never heard of mpv crashing before. Take care, thanks again! :smile:
