### ISSUE TITLE
upgrade from 0.8.9.7 to 0.8.9.16 fails

### ISSUE THREAD

**Issue by PhilT001** [coderholic/pyradio#153]
(Nokia-N810-43-7) pyradio $ sudo pip install .
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
WARNING: The directory '/home/user/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /Diablo-tablet-chroot/home/user/builds/source/pyradio
Using legacy 'setup.py install' for pyradio, since package 'wheel' is not installed.
Installing collected packages: pyradio
  Attempting uninstall: pyradio
    Found existing installation: pyradio 0.8.9.7
    Uninstalling pyradio-0.8.9.7:
      Successfully uninstalled pyradio-0.8.9.7
    Running setup.py install for pyradio ... done
Successfully installed pyradio-0.8.9.16
(Nokia-N810-43-7) pyradio $ pyradio
Traceback (most recent call last):
  File "/usr/bin/pyradio", line 11, in <module>
    load_entry_point('pyradio==0.8.9.16', 'console_scripts', 'pyradio')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/pyradio/main.py", line 462
    print('\nPress any key to continue...', end='', flush=True)
                                               ^
SyntaxError: invalid syntax
(Nokia-N810-43-7) pyradio

**Comment by s-n-g** [comment]
Hi @PhilT001 

Actually, the installation has been successful, but then running `pyradio` breaks...
That is my bad; I did not test this release with python2 as Ishould, it seems...

Now, what can you do?
Open the following file (with sudo):
```
/usr/lib/python2.7/site-packages/pyradio/main.py
```
Go to line 462, and change 
```                
		print('\nPress any key to continue...', end='', flush=True)
```
to
```
		#print('\nPress any key to continue...', end='', flush=True)
```
Then go to line 595 and repeat the above

Finally, save the file

**pyradio** should be running ok now

**Comment by PhilT001** [comment]
Thank you, now fixed. 

And yes it is a chrooted Diablo tablet :D

**Comment by s-n-g** [comment]
> And yes it is a chrooted Diablo tablet :D

Nice!

I will include the fix to the next release
Closing...
