### ISSUE TITLE
Is there anyway to pause the stream?

### ISSUE THREAD

**Issue by hmm5** [coderholic/pyradio#154]
Hi, I believe there used to be a way to pause a stream, just in case you want to step away from the computer for a moment.  However, I don't think there's any key assigned to pause a stream anymore.  If I use 'p', it simply asks to paste something.  

I'm using mpv, anyway to reenable support for pausing again?

Thanks.

**Comment by s-n-g** [comment]
Hi @hmm5 

No there is no way (and never have been) to pause a stream.

What I do when I have to step away from the computer is I just mute it (pressing `m`).
That works for me, hope it works for you too

**Comment by hmm5** [comment]
Can't you just let mpv buffer the stream for a little bit while it's paused, until you get back to the computer?  The reason why I'm asking is that sometimes I want to listen to the stream, but I have to step away for e.g a minute or so, and don't want to miss what is being played or said.  I don't think there's any need to create extensive timeshifting capabilities.  

Under player.py, there does seem to used to be a pause function.  

        commands = {
                'volume_up':   b'{ "command": ["cycle", "volume", "up"], "request_id": 1000 }\n',
                'volume_down': b'{ "command": ["cycle", "volume", "down"], "request_id": 1001 }\n',
                'mute':        b'{ "command": ["cycle", "mute"], "request_id": 1002 }\n',
                'pause':       b'{ "command": ["pause"], "request_id": 1003 }\n',
                'quit':        b'{ "command": ["quit"], "request_id": 1004}\n',
}

...
    def pause(self):
        ''' pause streaming (if possible) '''
        self._send_mpv_command('pause')


Thanks.

**Comment by s-n-g** [comment]
> Can't you just let mpv buffer the stream for a little bit while it's paused, until you get back to the computer? The reason why I'm asking is that sometimes I want to listen to the stream, but I have to step away for e.g a minute or so, and don't want to miss what is being played or said. I don't think there's any need to create extensive timeshifting capabilities.

Yes, I see what you mean...

And I would have no problem to implement it (using ths space key for example), but my concern to start with is what would happen If the user keeps the player paused for 15 minutes for example. How would that play out? I will have to test this and make sure nothing "catastrophic" happens (in terms of memory usage or something)


> Under player.py, there does seem to used to be a pause function.
> 
> ```
>     commands = {
>             'volume_up':   b'{ "command": ["cycle", "volume", "up"], "request_id": 1000 }\n',
>             'volume_down': b'{ "command": ["cycle", "volume", "down"], "request_id": 1001 }\n',
>             'mute':        b'{ "command": ["cycle", "mute"], "request_id": 1002 }\n',
>             'pause':       b'{ "command": ["pause"], "request_id": 1003 }\n',
>             'quit':        b'{ "command": ["quit"], "request_id": 1004}\n',
> ```
> 
> }
> 
> ... def pause(self): ''' pause streaming (if possible) ''' self._send_mpv_command('pause')

Sure, the command is there, but cannot be used because it is not bound to a key, due to the concerns above...

As I said, I will have to test and see what happens...

**Comment by hmm5** [comment]
Hi, thanks for looking into the feature.

I've done a little testing with mpv to see what happens.  

I used the mpv option --demuxer-max-bytes=512KiB, I tried to set the max amount of buffer space to a very small 512KB, after the buffer size is reached, it basically disconnects and stops downloading, while paused, you can unpause, and it will play through the cache, but after playing through the cache mpv will throw an error like "[ffmpeg] http: Stream ends prematurely at 1071705, should be 18446744073709551615" and mpv will simply quit.

So I think you can allow a pyradio user to configure the buffer max buffer size with demuxer-max-bytes which should allow pause with no real issue, which would be helpful for people using a raspberry pi with small amount of ram.  Since radio audio streams typically aren't huge e.g. 128kbit/sec stream would mean about a minute per 1MB of buffer space, so even 20MB of buffer seems like plenty, and wouldn't be burdensome even with a raspberry pi zero with only 512MB of ram.

I'm not sure if necessary, but if there's a pause button, should there also be a fast foward, e.g. if you want to fast forward through any commercials that may have been buffered while paused?

Thanks.

**Comment by s-n-g** [comment]
Hi again @hmm5 

I have tested pausing all the players and this is what I've found

1. `mpv` will pause and resume the stream, no problem. \
I have paused for 1 hour and the cache went up to about 100MB for a 2 chanel, 44100, 128kbps station. \
Pausing and resuming for 1 minute will just keep playing (even after the 1 minute mark) \
This is like the player will keep playing with a delay which is equal to the time paused

2. `mplayer` will pause and resume, but will only play as much time is in its buffer (a few seconds), then it will just keep downloading, so there will be a "jump" in time of a sort (best way I can explain it)
3. `vlc` has the same behaviour as `mplayer`

To conclude, `mpv` is the only player able to pause and resume without problems and without medling with command line parameters and settings (I don't want to go down that path).

What I'm thinking is to have a config option to permit **space** to pause `mpv`

Can you confirm mplayers' behaviour as I have described above?

**Comment by s-n-g** [comment]
Pausing for ~ 5 minutes
![Mabox_2022-04-07-09-17-1649312222](https://user-images.githubusercontent.com/5807638/162132836-f2d94e77-e7b3-457c-8fbc-0ec886af1d8d.png)

**Comment by hmm5** [comment]
I tried testing with mplayer, where I used a small cache, using the -cache 512, which equals 512KB.  mplayer will pause, but once the buffer fills up, it appears to disconnect, and unpausing will only play what's left in the cache and then quits without throwing up any errors.  

I think it's actually fine to allow pausing for mpv, mplayer, and vlc, and just put something like a experimental warning up.   I think it's actually good to have a max buffer options for mpv and mplayer (don't know if vlc has the same option, since I rarely use vlc for anything), so that if you accidentally forget that you paused something, it doesn't just keep buffering more and more content forever.  I think a good size is about 100MB, which should be plenty for most people.   Also make sure that a user knows that they have paused, and it's not playing a radio station.  

Thanks again.

**Comment by s-n-g** [comment]
It seems like the disconnections depend on the station...
I have executed the following, played like 1 minute and then paused for 2 minutes.
Then I unpaused and played for 5 more minutes, no problem, no disconnection...
```
mplayer -v -playlist http://somafm.com/folkfwd.pls -cache 100000 -cache-min .2
```
Can you please try out a similar scenario using this command and tell me if it does discoccect or not?

Thanks

**Comment by hmm5** [comment]
Yes, I believe you're right that it depends on the stream itself, whether or not it disconnects.  With the soma.fm stream, it jumps ahead after the buffer runs down.  It does the same with mpv if I set a cache limit.  

Either way, I think that's fine, as long as the user knows that may happen, therefore should be asked to set a reasonable cache size if they enable the feature to pause with no skips or disconnects, either that or simply use mpv, with no cache limit if they have no fears of running out of memory.   Personally, I mainly use pyradio with a raspberry pi zero with only 512MB of memory, so I would be setting a cache limit as I don't want it to either crash due to lack of memory or having to use swap which is basically an SD flash card.

**Comment by s-n-g** [comment]
ok then, I will leave this open and look at it at a later time

Thanks for the recomendation and helping out with tests!

**Comment by s-n-g** [comment]
Hi again @hmm5 

It's been a while :)

But I haven't forgotten this issue that you submitted, so here it is (well, partially)

The only reliable way to pause a station is to have it written (downloaded to a file) and play it from there. Then pausing the station just means pausing the playback of a file, which is very easy to do.

I have looked into it for a while, and I found out that **mpv** can play a station and record it to a file at the same time. So, this is what I have implemented (for the time being).

So, select **mpv** as your player, press **|** to enable recording, start the station's playback and then you can pause it using the **Space** key and then resume it with the same key.

I know this is not perfect, but it's the best I can think of.

Next step is to try to implement the same functionality for **mplayer** and **vlc** :wink:

**Comment by s-n-g** [comment]
Time to close this one...
