### ISSUE TITLE
Cannot change volume

### ISSUE THREAD

**Issue by tamasborsos** [coderholic/pyradio#156]
Neither +/- or ,/. does anything, cannot change. Tried with main main keypad and numeric as well.

**Comment by s-n-g** [comment]
Yeah...
It seems I screwed up; I enabled global functions everywhere but the main windo...
Working on it...

**Comment by tamasborsos** [comment]
Thank you @s-n-g for this and for this great stuff of yours! Just love pyradio!

**Comment by s-n-g** [comment]
Done with https://github.com/coderholic/pyradio/releases/tag/0.8.9.19

Closing...

**Comment by tamasborsos** [comment]
Thank you much! Works perfectly.

**Comment by s-n-g** [comment]
You are welcome!
Thank you for reporting it
