### ISSUE TITLE
pyradio theming

### ISSUE THREAD

**Issue by s-n-g** [coderholic/pyradio#159]
This is a call to help, primarily intended for users @edunfelt and @OpenBSDGuy who have submitted personal themes to pyradio  (here https://github.com/coderholic/pyradio/issues/60#issuecomment-833287617 and here https://github.com/coderholic/pyradio/pull/158), and any other user who has created a personal theme for pyradio

I have started working on pyradio theming; trying to use CSS colors instead of color numbers.
This is still at a very early stage and I would like to see your color settings based on your palette :)

So, can you please downaload this script: https://gist.github.com/s-n-g/eefd2307ae9713c7a6c707c096995077

and execute it, like so

```
python pyradio_themes.py [path to your theme]
```

This will create a file `~/pyradio_themes.log`; can you please post it here?

Let me remind you these are the themes submittted:

**pink_by_edunfelt.pyradio-theme**
```
PyRadio URL = 2,0
Messages Border = 2,0
Status Bar = 0,1
Stations = 7,0
Active Station = 1,0
Active Cursor = 0,1
Normal Cursor = 0,3
Edit Cursor = 0,8
```

**classic_by_obsdg.pyradio-theme**
```
PyRadio URL = 0,0
Messages Border = 15,0
Status Bar = 16,4
Stations = 7,0
Active Station = 1,0
Active Cursor = 0,1
Normal Cursor = 0,4
Edit Cursor = 7,4
```

**Comment by OpenBSDGuy** [comment]
Hi

This is the result for `classic_by_obsdg.pyradio-theme` [pyradio_themes.log](https://github.com/coderholic/pyradio/files/8839565/pyradio_themes.log)

**Comment by edunfelt** [comment]
Hi!

Completely forgot about this, although I still use the radio all the time. Thank you for keeping the project floating! CSS would probably lend much more flexibility and predictability to the theming. 

Here's the output for `pink_by_edunfelt.pyradio-theme`: [pyradio_themes.log](https://github.com/coderholic/pyradio/files/8840099/pyradio_themes.log)

**Comment by s-n-g** [comment]
> Hi!
> 
> Completely forgot about this, although I still use the radio all the time. Thank you for keeping the project floating! CSS would probably lend much more flexibility and predictability to the theming.

Well, i did not forget our last conversation, and here it the time has come to put it to action :smiley: 

Thank you both for your input!

I have been working on it the last couple of days (I have already converted the internal themes to CSS).

I will convert the external ones and prepare a test package for you to test your themes and fine-tune if needed. Then I will release them as part of pyradio (the external themes I have created are horrific :wink: )

Later!

**Comment by s-n-g** [comment]
Hi guys!
I have just pushed the changes to my test repo, here's how you get it

```
python -m pip install https://github.com/s-n-g/pyradio/archive/devel.zip
```

This is just a test package you are going to use (I have kept the same version as the released one, so you will be able to update whenever the next official release is out)

Now, about the themes...

@edunfelt's theme should be correctly converted; I already knew the palette she was using when she created the original theme.

@OpenBSDGuy 's theme is different; I do not know the original palette used, so I had to guess the colors from the color value and screenshot, so the theme may be a bit off (the URL color, for example).

Things to consider:
1. I have added a **Extra Func** color. It is the text color for extra function indication and jump numbers within the status bar (background color will come from Stations).
2. I have discovered that **xterm** and **xterm based** terminals have a problem updating the colors on the fly. \
\
I believe I have fixed this issue, but I have found at least one terminal (**roxterm** on *MX Linux Fulubox*) which still does not behave :smile: \
\
So, if you do find one, please do report!
3. Please do also check the "**Edit cursor**" color (just press "*e*" and see the cursor in the line editor).

I have attached the "*converted*" themes for you to test, plus a **pastel** theme I've put together (too dim I think, but I still like the colors)

[themes.tar.gz](https://github.com/coderholic/pyradio/files/8869082/themes.tar.gz)

**Comment by OpenBSDGuy** [comment]
Thanks @s-n-g - I'll check it out and share it

**Comment by OpenBSDGuy** [comment]
I've tested it and did a bit of adjustments on colors and opened a PR. However, during the testing process, I've realized that Pyradio is not working within Tmux anymore. I've got this error:

```python
TERM = tmux-256color
Reading config...
Reading playlist...
Traceback (most recent call last):
  File "/home/kixz/.local/bin/pyradio", line 8, in <module>
    sys.exit(shell())
  File "/home/kixz/.local/lib/python3.9/site-packages/pyradio/main.py", line 452, in shell
    curses.wrapper(pyradio.setup)
  File "/usr/local/lib/python3.9/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/home/kixz/.local/lib/python3.9/site-packages/pyradio/radio.py", line 550, in setup
    ret, ret_theme_name = self._theme.readAndApplyTheme(self._theme_name)
  File "/home/kixz/.local/lib/python3.9/site-packages/pyradio/themes.py", line 107, in readAndApplyTheme
    self._update_colors()
  File "/home/kixz/.local/lib/python3.9/site-packages/pyradio/themes.py", line 140, in _update_colors
    curses.init_color(
_curses.error: init_color() returned ERR
```

I'm running OpenBSD btw. Prior to that it was working fine.

**Comment by s-n-g** [comment]
This is a TERM issue...

Can you please execute

```
TERM=xterm-256xolor pyradio
```

within `tmux` and tell me if ti still crashes?

[quote]
I'm running OpenBSD btw. Prior to that it was working fine.
[/quote]

Yes, I know!
I've also seen your youtube channel!
You got me to try and test OpenBSD on `virt-manager` :wink: ; I will tell you how it foes when i do it

**Comment by s-n-g** [comment]
Just one thing though...

The URL color... look at this screenshot (right top corner of pyradio's window)

![Mabox_2022-06-12-22-47-1655063253](https://user-images.githubusercontent.com/5807638/173250687-6b2bf4d7-1822-4f43-86a5-60652f1a650b.png)

This is on `tmux` (on Mabox Linux)

**Comment by s-n-g** [comment]
Hi again guys!

I have just pushed new changes to `master`.

The way to get the changes is this. Get into your fork

```
cd pyradio
git remote add upstream https://github.com/s-n-g/pyradio.git
git fetch upstream
# keep local changes
git stash
git merge upstream/master
```
(hope I got these instructions right...)

Now for the changes...

1. This should be fixing @OpenBSDGuy crash \
TERM is set to `xterm-256color` if original TERM is `tmux*`
2. @edunfelt  themes updated :)
3. `pyradio` is now watching a theme called `auto` for changes \
Any changes done to this theme (files is `~/.config/pyradio/themes/auto.pyradio-theme`) will be immediately applied to `pyradio` 

This is just a "test" condition for the program; it would normally allow the user to set the file to "watch"

You can use the following script to see all theme :wink: 

```
#!/bin/bash
PYTHON_USER_SITE_PACKAGES=`python -c 'import site; print(site.getusersitepackages())'`

while true
do
    clear
    for n in "$PYTHON_USER_SITE_PACKAGES"/pyradio/themes/*.pyradio-theme
    do
        sleep 3
        echo $(basename "$n")
        \cp "$n" ~/.config/pyradio/themes/auto.pyradio-theme
    done
done
```

This will simulate a mechanism (like `base16`) that will update a given watched pyradio theme

So @edunfelt I hope this would be enough for you to test the creation of a base16 template?

I mean, if  `~/.config/pyradio/themes/auto.pyradio-theme` is set to be the output of a base16 theme based on your template, we can just test the behavior of the whole thing

What do you think?

**Comment by OpenBSDGuy** [comment]
> Yes, I know!
I've also seen your youtube channel!
You got me to try and test OpenBSD on virt-manager wink ; I will tell you how it went when i do it

haha hope you like it :-)

Sorry for replying late, been super busy lately. I've tried the latest changes. It's working on tmux, with a slightly different color (only blue) which is fine, I can fix it later. See below:
![out](https://user-images.githubusercontent.com/96616294/174598166-214fd59c-9414-4443-a5ba-099755189abd.jpg)

But when I press `q` to quit. The app kind of crashes. It stops but doesn't quit. If I do `ps` I see the pyradio process is still there. Haven't tested it on Linux yet. Python 3.9.13

**Comment by OpenBSDGuy** [comment]
Thanks. Let me know once you pushed, I can test it again.

> I seem to have read that virtualization does not work on OpenBSD?

Unfortunately that's correct. Virtualization is not well supported on OpenBSD. Only option besides slow Qemu (without KVM) is [VMM](https://man.openbsd.org/vmm.4) which has limited functionality somewhat. There are also no Docker and Kubernetes.

I don't remember about sound on `virt-manager` but I'm sure I had it on VirtualBox last time I've tried. I'll try it and let you know.

**Comment by s-n-g** [comment]
ok, I got the sound working!

I see the themes as they are rendered, and there are inconsistencies there...
I have fixed the top bar background color, but

- the title and URL text color are all wrong
- when opening the the help window I see the box is not correct, and there are leftover chars displayed. Is it just me (because of `virt-manager`) or do you have it too?

Look at this video: https://mega.nz/file/KgRQHCKR#15rzpa330MHBE8OkIiyauZUNxfEJ2LrwRLBondyXrxI

I have ssh-ed into my linux and you can see the difference...

**Comment by s-n-g** [comment]
Hi guys!

I have just released `0.9.8.21`, publishing the new CSS theming engine along with your themes!

Regarding our tests and such, my repo master branch has also been updated, plus file watch is still enabled for `~/.config/pyradio/themes/auto.pyradio-theme`

Cheers!

**Comment by s-n-g** [comment]
Hi again!

I have just released **0.8.9.22**, which introduces two new changes

1. Themes now have a transparency hint
2. Theme auto update has been implemented

Setting theme transparency to

- 0: means that the theme looks better with no transparency (default)
- 1: means that the theme looks better when transparency in ON
- 2: means that the theme looks good either way, and the global transparency setting (defined in PyRadio config file) can be used.

All themes which have a dark background are currently set to 2 (including **classic_by_obsdg**), all other themes are set to 0.

I will leave this open until @edunfelt has the time to work on a system16 template (or not :wink: )

**Comment by edunfelt** [comment]
Hi again,

Sorry for being slow to get back on this @s-n-g - a couple of things got added to my schedule and it's been a lot to keep up with. :sweat_smile: 

> So @edunfelt I hope this would be enough for you to test the creation of a base16 template?
> 
> I mean, if `~/.config/pyradio/themes/auto.pyradio-theme` is set to be the output of a base16 theme based on your template, we can just test the behavior of the whole thing
> 
> What do you think?

This sounds very interesting! I'm looking into creating a template repo for pyradio right now. Hopefully I can get it done before the week ends. :)


> Themes now have a transparency hint

Good call!

> Theme auto update has been implemented

Not sure I understand it correctly, but I seem to have to re-apply the `auto` theme before changes take effect.

**Comment by edunfelt** [comment]
Hi!

I have set up a template repo and tested everything now [over here](https://github.com/edunfelt/base16-pyradio). Things should work and the themes look pretty good imo :D

I'd love your feedback though, whenever you have time to take a look @s-n-g. One thing I thought about was whether or not there is reason to have different templates for the value of the transparency setting? Right now the default template uses `0`.

When it's ready we could make a PR and add it to the official [un-official template list](https://github.com/base16-project/base16/blob/main/README.md#unofficial-templates)!

**Comment by s-n-g** [comment]
Hi @edunfelt 

I haven't tested anything yet; just got back from a family feast and I'm still a bit under the weather :wink: 

But I've seen the work you've done; it's impressive especially in such short time :astonished:

Just two things...

With v. `0.8.9.22`, the name of the theme can be anything we want... the name `auto` was just a test case... I would propose something like `base16` of `base16_pyradio` or something like that...

To answer your question about the transparency thing, I should be able to understand just how base16 would work...

What I would expect from it is to

1. give it an output filename (for example, `~/.config/pyradio/base16.pyradio-theme`)
2. create the file (or update it if it already exists)...
3. set pyradio to watch `~/.config/pyradio/base16.pyradio-theme`
4. enable a theme, for example `base16 cupcake` from a terminal

and have it (base16, that is) update  `~/.config/pyradio/base16.pyradio-theme` using the base16_pyradio template, which would force pyradio to "reapply" the theme...

Is this what `base16` will do?

**Comment by s-n-g** [comment]
Closing this one...
