### ISSUE TITLE
Feature suggestion - switch back to previously played station

### ISSUE THREAD

**Issue by wturrell** [coderholic/pyradio#161]
Hello,

I have a TV remote control (not that I have time to watch TV any more, obviously) with a button that immediately changes the channel back to the channel you were last one - i.e. you can keep pressing it to go back and forth between two channels.

This seems like it would be quite easy to implement as a keyboard shortcut? (albeit there will be a buffering delay each time you switch.)

Thanks.

**Comment by s-n-g** [comment]
Hi @wturrell 

Yes, why not?
Let me think about it... :wink:

**Comment by s-n-g** [comment]
Implemented in https://github.com/coderholic/pyradio/releases/tag/0.8.9.27

Just play a couple of stations and use "**<**" and "**>**" to go back and forth.
Hope that is satisfactory...

**Comment by wturrell** [comment]
Works really well, thanks!
