### ISSUE TITLE
Unable to add stations

### ISSUE THREAD

**Issue by Bluesquare99** [coderholic/pyradio#165]
Hello, I keep getting an error message upon trying to add stations.  Can someone advise me on how to fix this?
<img width="923" alt="Screen Shot 2022-08-16 at 11 50 42 AM" src="https://user-images.githubusercontent.com/75914260/184935124-0cef187d-e85f-4cea-a755-77b0e09cec87.png">

**Comment by s-n-g** [comment]
I cannot reproduce...

![Στιγμιότυπο στο 2022-08-16 20-25-11](https://user-images.githubusercontent.com/5807638/184941539-fa35e6ee-76d7-49a2-9e96-9e2073ad6fef.png)

Can you try it this way?
Open the program and press `a`
Then insert the station, and save the playlist

**Comment by Bluesquare99** [comment]
That worked!  Thank you.  Marking issue as resolved.
