### ISSUE TITLE
Problem in Mac OSX

### ISSUE THREAD

**Issue by marcoslhc** [coderholic/pyradio#17]
I tried to run the script but I get this exception:

```
    Traceback (most recent call last):
      File "/usr/local/bin/pyradio", line 8, in <module>
        load_entry_point('pyradio==0.5.2', 'console_scripts', 'pyradio')()
      File "/Library/Python/2.7/site-packages/pyradio/main.py", line 54, in shell
        curses.wrapper(pyradio.setup)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/curses/wrapper.py", line 43, in wrapper
        return func(stdscr, *args, **kwds)
       File "/Library/Python/2.7/site-packages/pyradio/radio.py", line 56, in setup
        self.player = player.probePlayer()(self.log)
     TypeError: 'NoneType' object is not callable
```

I'm running OSX Maverics with python 2.7 and vlc 2.10.0
I think pyradio doesn't find the player

**Comment by moeabdol** [comment]
I followed the suggested fix, and it worked; however, I can see the list of radio stations but can't seem to play any of them....I get "No handlers could be found for logger 'pyradio.player'"
any help please.

**Comment by jottr** [comment]
@marcoslhc I am seeing the same error message as @moeabdol: 

`No handlers could be found for logger "pyradio.player"`

I have both mplayer and cvlc installed and available in my PATH: 

```shell
$ which mplayer
/usr/local/bin/mplayer

$ which cvlc
/Users/jottr/.bin/cvlc
```

**Comment by coderholic** [comment]
@jottr It sounds like a logging issue, rather than an issue with finding a player. What version of python are you using? Here's the logger related code: https://github.com/coderholic/pyradio/search?utf8=%E2%9C%93&q=logger&type=

**Comment by jottr** [comment]
It seems my issue was caused by my python environment (using `pyenv`). 
Reinstalling `pyradio` fixed it for me.
