### ISSUE TITLE
Video not surpressed / "quiet"

### ISSUE THREAD

**Issue by lee2sman** [coderholic/pyradio#170]
Hi I'm running Pyradio 0.8.7.2 with mpv. 

I'm on Ubuntu 22.04 with i3 window manager.

In addition to my regular radio stations I have added some bandcamp albums to stream. When I play one of these a separate window in mpv pops open with a video consisting of the static image of the album cover plus the music playing. 

From reading the pyradio repo I thought mpv should run with -quiet mode to suppress this video from opening.

**Comment by s-n-g** [comment]
Well, this is an old release that you are using (2020, March 16)

I would suggest to update to current

The release you are using does not use the `--no-video` mvp parameter; it's not the `--quiet` that's causing the problem... I suppose the stations you have added do provide a video stream as well

If for any reason you cannot upgrade, you can just edit `player.py`, at this point


https://github.com/coderholic/pyradio/blob/570c6a875055739b605c6cf60297b5fc4ac21e8f/pyradio/player.py#L651


and make it like so:

```python
        if playList:
            if newerMpv:
                opts = [self.PLAYER_CMD, '--no-video', '--quiet', '--playlist=' + self._url_to_use(streamUrl), '--input-ipc-server=' + self.mpvsocket]
            else:
                opts = [self.PLAYER_CMD, '--no-video', '--quiet', '--playlist=' + self._url_to_use(streamUrl), '--input-unix-socket=' + self.mpvsocket]
        else:
            if newerMpv:
                opts = [self.PLAYER_CMD, '--no-video', '--quiet', self._url_to_use(streamUrl), '--input-ipc-server=' + self.mpvsocket]
            else:
                opts = [self.PLAYER_CMD, '--no-video', '--quiet', self._url_to_use(streamUrl), '--input-unix-socket=' + self.mpvsocket]
```

**Comment by lee2sman** [comment]
Thank you! On my Void linux system I updated and the current system. When I run it with mplayer it fails to play but when launching and specifying the mpv player it does correctly suppress the video now. Thanks.

For my Regolith/Ubuntu computer I will try to delete and reinstall latest version of pyradio or else follow your steps above. thanks
