### ISSUE TITLE
suggestion: fix typo + move THEMES DISABLED warning dialog to themes section

### ISSUE THREAD

**Issue by lee2sman** [coderholic/pyradio#171]
1. I have updated to the latest pyradio 0.8.9.31. When I open it up I see an immediate TUI dialog box Themes Disabled EVERY TIME I open the app. This warning is not necessary on each launch. Could it be made to only pop up if someone pressed t to change the theme? For what it's worth, I am getting this error on pyradio installed on Void Linux and Regolith in Terminology but Pyradio seems fine in default mode.
2. There is a typo here. The url for the project repo is listed as githug instead of github, so the link doesn't work. Perhaps you could also link [directly](https://github.com/coderholic/pyradio/#virtual-terminal-restrictions) to the relevant section of code.

**Comment by s-n-g** [comment]
Hi again @lee2sman 



> 1. I have updated to the latest pyradio 0.8.9.31. When I open it up I see an immediate TUI dialog box Themes Disabled EVERY TIME I open the app. This warning is not necessary on each launch. Could it be made to only pop up if someone pressed t to change the theme? For what it's worth, I am getting this error on pyradio installed on Void Linux and Regolith in Terminology but Pyradio seems fine in default mode.

Yes, I will probably make a config option for the user to disable this message altogether. The pop up window is already there, so...




> 2\. There is a typo here. The url for the project repo is listed as githug instead of github, so the link doesn't work. Perhaps you could also link [directly](https://github.com/coderholic/pyradio/#virtual-terminal-restrictions) to the relevant section of code.

Thanks for that, I never would have noticed :)

I will have to see about the direct link though; I think I tried it but the window gets too wide...

**Comment by lee2sman** [comment]
Are you saying that there is always a dialog box that appears when launching pyradio now? If so, I wasn't aware of that new behavior since updating. If not, what I would expect to see would be that dialog box to appear when I try to change the theme, not when I launch the program. If that's not possible, a flag to suppress the message would be helpful.

**Comment by s-n-g** [comment]
It should be fixed now with
https://github.com/coderholic/pyradio/releases/tag/0.8.9.32

When you get the window, press `x`, restart `PyRadio` and you won't see it again :wink: 

Please do verify that it is so for you

**Comment by s-n-g** [comment]
Yes, this is true, there is a always a dialog box that appears when launching pyradio with `terminology` et al.
Next time you get it, press `x` and it will not appear again

A pop up dialog box will appear for 1-2 seconds when you press `t`

**Comment by lee2sman** [comment]
Confirming this works. Thanks so much. 

By the way, is there a way to donate to you and/or the pyradio effort somewhere? Thanks for being so responsive.

**Comment by lee2sman** [comment]
Confirming this works. Thanks so much. 

By the way, is there a way to donate to you and/or the pyradio effort somewhere? Thanks for being so responsive.

**Comment by s-n-g** [comment]
> Confirming this works. Thanks so much.

Great!
I'll just go on and close this one!



> By the way, is there a way to donate to you and/or the pyradio effort somewhere? Thanks for being so responsive.

My pleasure!
No there is no donations option about this project; thank you so much for offering though :smile:
