### ISSUE TITLE
[FEATURE REQUEST] Theme Border Color Option

### ISSUE THREAD

**Issue by ghost** [coderholic/pyradio#173]
Can you please add option to change border color around pyradio? Thanks.

**Comment by s-n-g** [comment]
![Mabox_20221223-01-08-11](https://user-images.githubusercontent.com/5807638/209241196-8bdcbf2c-6464-4450-8fea-2c44ff424669.png)

You mean this border?

It comes from
```
# Main foreground and background
Stations            #D0D0D0 #151515
```

So, you are probably referring to the `foreground` color, something like:
```
# Main border foreground
# (background color will come from Stations)
Border            #D0D0D0
```

That would mean:
1. A new color has to be initialized
2. A new color pair has to be populated

PyRadio is already using colors `0-15` and color pairs `1-12`.

The "color pairs" thing does not poise a problem, but initializing color 16 might be a problem with terminals that support 16 colors only...

I guess I could implement it and get it ignored if a terminal supports 16 colors only...

I do have to think about it :wink:

**Comment by s-n-g** [comment]
Hi @tuxy 

I have just pushed the fix to your request on my personal repo. Can you please test it?

Here's the archive you can download
```
curl -L 'https://github.com/s-n-g/pyradio/archive/1a00e78.zip' -o tuxy.zip
```

After you unzip it:

```
unzip tuxy.zip
cd pyradio-1a00e78a9789a4cee816f520a7485258718ed529
./devel/build_install_pyradio
pyradio
```

The documentation:

https://github.com/s-n-g/pyradio/tree/devel#alternative-main-window-border-color:

**Comment by s-n-g** [comment]
Oh, just one thing though, you will have to install `netifaces` for this version to run...

The package name is `python-netifaces` (`python3-netifaces` on debian), or 

```
python -m pip install netifaces
```
