### ISSUE TITLE
Unable to disable notify-send

### ISSUE THREAD

**Issue by troyvit** [coderholic/pyradio#176]
Hello PyRadio, thanks for the awesome app.

A recent update brings a notification on my desktop of what song is playing. I didn't want that and as is usual with PyRadio there's a setting to disable it:

`enable_notifications = -1`

In fact that's supposed to be the default but despite that I'm still seeing notifications.

When I view the setting using `c` it is set to 0. Hitting Enter doesn't toggle it or enable me to change the value. If I delete my config and restart PyRadio my config shows -1 for enable_notifications, but it's still set to 0 in settings. When I quit PyRadio it overwrites the setting to 0 in my config. If I chmod my config to 000 PyRadio of course doesn't change the setting but it ignores it and continues to show notifications.

I also have a config file in:

`~/.local/lib/python3.10/site-packages/pyradio/config`

but enable_notifications is set to -1 there already.

Here's some info about my system:

```pyradio -V
PyRadio version: 0.8.9.35
Python version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
```

```pyradio -scd
PyRadio config dir: "/home/vit/.config/pyradio"
```
I've uploaded a .txt version of my config since github wants a file extension.

Do you know what might be up?
[config.txt](https://github.com/coderholic/pyradio/files/10468721/config.txt)

**Comment by s-n-g** [comment]
Hi @troyvit 

This is a bug in v. `0.8.9.35`

Please update to the latest release: https://github.com/coderholic/pyradio/releases/tag/0.8.9.36
