### ISSUE TITLE
Colors in urxvt

### ISSUE THREAD

**Issue by Knusper** [coderholic/pyradio#177]
Hi,
I use `urxvt` and I never had problems with the colours.
Since version  0.8.9.36 I get a message, that `using themes is disabled` in this terminal because it does not work correctly?
So,  something broke with the update. 😢 
On my side `echo $TERM` displays `rxvt-256color`.
Cheers,
Christian

**Comment by s-n-g** [comment]
Hi Christian!

I am sorry to hear your issue...

I tried it but cannot reproduce it... I am on a Mabox (Manjaro based) system.

Please do have a look at this video


https://user-images.githubusercontent.com/5807638/216791556-a2f9e1d9-4857-47dc-a325-67a12501b480.mp4

I will have a look at a diff tomorrow... What was the last good working version you've had?

**Comment by s-n-g** [comment]
Hi again Christian,

Here's something you can do to help get an understanding on what's going on

```
wget https://github.com/s-n-g/pyradio/archive/refs/heads/devel.zip
unzip devel.zip
cd pyradio-devel
./devel/build_install_pyradio
```

This will install a development package of `pyradio`

Then

```
~/.local/bin/pyradio -d
```

Just exit the program right away and post the file `~/pyradio.log` (it will be created with the `-d` parameter)

**Comment by Knusper** [comment]
OK, with this package it works without problems.

**Comment by s-n-g** [comment]
This is just **v 0.9.0** with a couple of extra debug messages.
Nothing special for your issue...

BTW, how did you previously install `pyradio`?
i suspect it was not installed by code 😉 

(The video plays on both a linux and a windows machine :) )

**Comment by s-n-g** [comment]
Yeah, it's firefox that does not like the video; chrome, edge etc. plays it just fine :)

**Comment by Knusper** [comment]
I used a script a long time ago - in the meantime the new versions were updated automatically from time to time after I started pyradio ... 

I just `grep'ed` through my history, and I used this script:
`https://raw.githubusercontent.com/coderholic/pyradio/master/pyradio/install.py`

**Comment by s-n-g** [comment]
Yes, that's the right way to do it
For a minute I thought you used a snap or something :wink: 

If you have any other problem in the future, don't hesitate to contact me
