### ISSUE TITLE
How can I add a selected or playing Radio-Browser-Station to the playlist?

### ISSUE THREAD

**Issue by Wikinaut** [coderholic/pyradio#179]
It is not clear how a station in the search window can be added to the playlist.

I suggest to use the + button or a(add) for adding a played station to the playlist.

Edit:
See also new issue #180 for `starring`  as favourite using the '*' key.

**Comment by s-n-g** [comment]
Hi again @Wikinaut 

I assume you want to paste a station from **Radio Browser** to your offline playlist.
You are right, it's not clear, but it's there...
Using **+** would not work; it increases the volume.
I like the idea of **a**; I might implement something like it in future versions

So, here's how you do it
1. select the station and press **y** and **ENTER**
2. press **\p** and select the playlist you want to paste to (I assume you only have **stations**, so it's already selected)
3. press **ENTER** to paste it


https://user-images.githubusercontent.com/5807638/218982350-601389b9-5f17-4409-ad7c-4b8fb5d5381a.mp4

**Comment by Wikinaut** [comment]
I would like to have a `single click solution` like favourising `starring`a station. Using the `*` for example to mark (also show in the windows) or unmark stations, and these are automatically added to a favorite playlist.

PS
I coded a similar function into the RadioDroid App.

**Comment by Wikinaut** [comment]
See new #180

**Comment by s-n-g** [comment]
Yes, that is a different thing altogether; that's a different functionality
