### ISSUE TITLE
Starting pyradio on boot on a headless system [work in progress]

### ISSUE THREAD

**Issue by Wikinaut** [coderholic/pyradio#184]
I could not get `pyradio`  running in server mode only.

Edited:
Matter fixed, see below.

**Comment by s-n-g** [comment]
Can you elaborate a bit more?

**Comment by Wikinaut** [comment]
Using pyradio on my `headless` Raspberry (without keyboard/monitor).

Starting up pyradio without any interface stuff.... just only the server part, so that I can control my pyradio via http://192.168.1.xxx:9998/html and/or via the buttons on the Raspberry (=python script scanning the buttons and connecting to pyradio-server via wget/curl when a button is pressed, e.g. volume+/- oder station+/-).
 
![grafik](https://user-images.githubusercontent.com/1151915/219433197-d984ee23-bd2e-42f1-b4f3-2ffa568ed1fa.png)

**Comment by Wikinaut** [comment]
`nohup pyradio &`

does not work, the process does not start perhaps because pyradio.py want to do something with the monitor.

**Comment by s-n-g** [comment]
pyradio is not a multimedia server; the server is just controlling the program remotely.
pyradio needs to start in the foreground and needs a terminal to run.

I think pyradio is not good for what you want to do :(

**Comment by Wikinaut** [comment]
It is perfect. It works now as wanted, controlling a station remotely(or locally via buttons) is exactly what I need.

See https://www.dexterindustries.com/howto/run-a-program-on-your-raspberry-pi-at-startup/

I added file `/lib/systemd/system/pyradio.py`:
```
[Unit]
Description=My Sample Service
After=multi-user.target

[Service]
Type=idle
ExecStart=/usr/bin/python /home/pi/.local/bin/pyradio

[Install]
WantedBy=multi-user.target
```

```
sudo chmod 644 /lib/systemd/system/pyradio.service
sudo systemctl daemon-reload
sudo systemctl enable pyradio
```

Test with `sudo systemctl start pyradio` (the server being enabled via pyradio config).

Works for me! Smoothly

**Comment by s-n-g** [comment]
Wow!
This is great!
I never could have expected that!
Great job!
:clap: :clap: :clap: :clap:

**Comment by Wikinaut** [comment]
oops, currently there's a problem... will try to fix and update here accordingly.

**Comment by Wikinaut** [comment]
oops

did not work as expected, I overlooked something,will try to fix

**Comment by Wikinaut** [comment]
It works from starting in ```.bashrc``` becausing when logging in, a console exists.

When starting as a services, `curses`will complain because it wants to connect to a console, apparently.

**Comment by Wikinaut** [comment]
@s-n-g Perhaps I have to add some code for a "headless" (quiet `-q`) mode of pyradio (support of the server code and control and playing).

**Comment by s-n-g** [comment]
Sure go right ahead, hope you make it!

**Comment by Wikinaut** [comment]
Some reading and thoughts: 

https://forums.raspberrypi.com/viewtopic.php?t=97856

**Comment by s-n-g** [comment]
> curses.cbreak()
> Terminals usually return special keys, such as the cursor keys or navigation keys such as Page Up and Home, as a multibyte escape sequence. While you could write your application to expect such sequences and process them accordingly, curses can do it for you, returning a special value such as curses.KEY_LEFT. To get curses to do the job, you’ll have to enable keypad mode.

From Curses Programming with Python - https://docs.python.org/3/howto/curses.html

Curses **needs** a terminal! :wink:

**Comment by Wikinaut** [comment]
This is fully clear to me, I hoped to overcome it by assigning a kind  of dummy terminal. This appears to be impossible and I close the issue now.

**Comment by aleksandr-sabitov** [comment]
> [1] https://www.dexterindustries.com/howto/run-a-program-on-your-raspberry-pi-at-startup/ [2] https://stackoverflow.com/questions/66725262/how-do-i-start-a-tmux-service-in-the-users-directory-on-user-login-using-system
> 
> I added file `/lib/systemd/system/pyradio.py`:
> 
> ```
> [Unit]
> Description=PyRadio Service
> After=multi-user.target
> 
> [Service]
> Type=Forking
> User=pi
> StandardOutput=append:/home/pi/pyradio.log
> StandardError=append:/home/pi/pyradio.log
> ExecStart=/usr/bin/tmux new-session -d -s pyradio-session /usr/bin/python3 /home/pi/.local/bin/pyradio
> ExecStop=/usr/bin/tmux kill-session -t pyradio-session
> 
> [Install]
> WantedBy=multi-user.target
> ```
> 
> Run
> 
> ```
> $ sudo chmod 644 /lib/systemd/system/pyradio.service
> $ sudo systemctl daemon-reload
> $ sudo systemctl enable pyradio # enabling the autostart on every boot
> ```
> 
> Test with `$ sudo systemctl start pyradio` (the server being enabled via pyradio config).

Nice findings, but for me for some reason service is deactivated immedietly (I just changed names and paths in you scripts).
Any ideas?

```
raspberry@raspberry-media-server:~ $ sudo systemctl status pyradio
○ pyradio.service - PyRadio Service
     Loaded: loaded (/lib/systemd/system/pyradio.service; enabled; preset: enabled)
     Active: inactive (dead) since Tue 2023-11-28 14:45:28 CET; 7s ago
   Duration: 53ms
    Process: 12400 ExecStart=/usr/bin/tmux new-session -d -s pyradio-session /home/raspberry/.local/bin/pyradio (code=exited, status=0/SUCCESS)
   Main PID: 12400 (code=exited, status=0/SUCCESS)
        CPU: 66ms

Nov 28 14:45:28 raspberry-media-server systemd[1]: Started pyradio.service - PyRadio Service.
Nov 28 14:45:28 raspberry-media-server systemd[1]: pyradio.service: Deactivated successfully.
```

**Comment by s-n-g** [comment]
That is very interesting!

On my system it does not work either, but using this:

```
ExecStart=/usr/bin/tmux new-session -d -s pyradio-session /home/pi/.local/bin/pyradio
```

makes it work (paths adjusted for you)

**Comment by s-n-g** [comment]
I have been playing with it for a while, so here's what I;ve got...

This is `/lib/systemd/system/pyradio.service`
```
[Unit]
Description=PyRadio Service
After=multi-user.target

[Service]
Type=forking
User=spiros
StandardOutput=append:/home/spiros/pyradio.log
StandardError=append:/home/spiros/pyradio.log
ExecStart=/usr/bin/tmux new-session -dA -s pyradio-session /home/spiros/.local/bin/pyradio -d -u mplayer
ExecStop=/usr/bin/tmux kill-session -t pyradio-session

[Install]
WantedBy=multi-user.target
```


Status:
```
sudo systemctl status pyradio
● pyradio.service - PyRadio Service
     Loaded: loaded (/usr/lib/systemd/system/pyradio.service; enabled; preset: disabled)
     Active: active (running) since Tue 2023-11-28 20:06:22 EET; 5min ago
    Process: 326539 ExecStart=/usr/bin/tmux new-session -dA -s pyradio-session /home/spiros/.local/bin/pyradio -d (code=exited, status=0/SUCCESS)
   Main PID: 326541 (tmux: server)
      Tasks: 10 (limit: 9395)
     Memory: 53.7M
        CPU: 2.316s
     CGroup: /system.slice/pyradio.service
             ├─326541 /usr/bin/tmux new-session -dA -s pyradio-session /home/spiros/.local/bin/pyradio -d
             ├─326651 /home/spiros/.local/pipx/venvs/pyradio/bin/python /home/spiros/.local/bin/pyradio -d
             ├─326916 mplayer -vo null -profile pyradio http://listen.181fm.com/181-xoldies_128k.mp3
             └─326937 mplayer -vo null -profile pyradio http://listen.181fm.com/181-xoldies_128k.mp3

Nov 28 20:06:22 py systemd[1]: Starting PyRadio Service...
Nov 28 20:06:22 py systemd[1]: Started PyRadio Service.
```

I have the remote control server enabled at `localhost:9998`, so

```
# curl http://localhost:9998/st/11
 Playing station: Lounge (Illinois Street Lounge - SomaFM)


# curl http://localhost:9998/i   
PyRadio 0.9.2.20
Player: mplayer
Playlist: "reversed"
Status: In playback 
  Station (id=11): "Lounge (Illinois Street Lounge - SomaFM)"
Selection (id=11): "Lounge (Illinois Street Lounge - SomaFM)"

# ps ajf
 326541  326651  326651  326651 pts/5     326651 Ssl+  1000   0:00 /home/spiros/.local/pipx/venvs/pyradio/bin/python /home/spiros/.local/bin/pyradio -d
 326651  331146  326651  326651 pts/5     326651 Sl+   1000   0:00  \_ mplayer -vo null -profile pyradio -playlist http://somafm.com/illstreet.pls
 331146  331195  326651  326651 pts/5     326651 S+    1000   0:00  |   \_ mplayer -vo null -profile pyradio -playlist http://somafm.com/illstreet.pls
 326651  331196  326651  326651 pts/5     326651 Z+    1000   0:00  \_ [notify-send] <defunct>

```

Only problem is, I get so sound...  :loud_sound: 

I have tried using `mpv` as a player, but that one just crashes as soon as I start playback, for whatever reason... `mplayer` is up and running, though no sound...

**Comment by s-n-g** [comment]
I have just tried it with an `openbox` system and put the command [1] in the autostart!
It works great!

Do you really have to use a systemd service for it?
Can't you start it another way?

[1]
```
/usr/bin/tmux new-session -d -s pyradio-session /home/spiros/.local/bin/pyradio
```

**Comment by s-n-g** [comment]
After further testing, I conclude that starting `pyradio` through `tmux` at session startup does not work...
It did work once (or I did something stupid and thought it did), but after that, I never managed to work with it again.

This is what happens:

- if `mplayer` is the default player, it just crashes, cannot play a single station

- if `mplayer` is the default player, it starts ok, it "connects" to stations, but there's no sound

- if `vlc` is the default player, it just crashes, cannot play a single station

I'm curious to see the result of your tests

**Comment by aleksandr-sabitov** [comment]
Amazing - I guess this combination of parameters solved my issue: `/usr/bin/tmux new-session -dA -s`
For me all works - also checked after reboot:
- sound is OK
- web-server is OK

Thanks for the support! Even though this amazing radio has not direct headless mode - this workardound is quite acceptable!

I'm running it on Raspberry PI 64bit OS (Debian version: 12, bookworm) with built-on VLC player.

**Comment by s-n-g** [comment]
Which player are you using?

**Comment by s-n-g** [comment]
Hi @Wikinaut  and @aleksandr-sabitov 

"Headles" operation is now officially supported (through `tnux` or `screen`.

Please refer to [Headless operation](https://github.com/coderholic/pyradio/blob/master/docs/headless.md) for more info.

Yo will have to make some changes so you do not have problems in the furure :wink:

**Comment by Wikinaut** [comment]
Thanks for letting me know.
Since last year I developed my own stand-alone radio ( https://github.com/Wikinaut/pinetradio ) from scratch. Perhaps I try once your approach.

**Comment by s-n-g** [comment]
That is great!
I love it when people go on and create solutions for the problems they face when one is not already made!
:clap: :clap: :clap:

**Comment by Wikinaut** [comment]
> That is great! I love it when people go on and create solutions for the problems they face when one is not already made! 👏 👏 👏

...and it has ```[ "Ellinikos 93,2", "http://netradio.live24.gr/orange9320" ],``` as one of the few default stations (see ```pinetradio.py```.

**Comment by Wikinaut** [comment]
![grafik](https://github.com/coderholic/pyradio/assets/1151915/3d7efdec-5458-49ad-b9ad-1d49f1950cea)

**Comment by s-n-g** [comment]
How come?
You speak Greek, or...?

**Comment by Wikinaut** [comment]
> How come? You speak Greek, or...?

Μιλάω λίγα ελληνικά.

**Comment by Wikinaut** [comment]
https://www.youtube.com/watch?v=o2-ucs2bPZk

**Comment by s-n-g** [comment]
> Μιλάω λίγα ελληνικά.
A! Μπράβο!
Με εξέπληξες ευχάριστα!

> https://www.youtube.com/watch?v=o2-ucs2bPZk
:wink:
