### ISSUE TITLE
[not an issue] - I made a cli tool to import m3u files

### ISSUE THREAD

**Issue by LionyxML** [coderholic/pyradio#189]
Hello there!

Pyradio is awesome! And your default playlist is also awesome!

That said. I made  a CLI tool to convert m3u files into the pyradio CSV format playlist. Automatically downloads a huge m3u file from somewhere (it is in the README) and converts it to CSV and even automatically overrides the current `stations.csv` (dangerous I know, but I hope people read the DANGER sign and makes backups).

https://github.com/LionyxML/pyradio-m3u-to-playlist

![image](https://user-images.githubusercontent.com/16169950/227685066-6b6a3a5c-ac40-43c7-ada5-10df350036f0.png)

Please don't be too mean to me :)

**Comment by s-n-g** [comment]
Hi @LionyxML 

Why would I be mean to you? :)
You are a polite guy and you have a very interesting idea plus I really love `junguler`'s repo!

I have forked your repo and made some changes:

1. make sure commas within fields will not break thing, both when parsing and saving the csv file
2. I added a **group** (or **section**) entry to the generated CSV file and added support for it in `pyradio`


This is how your `m3u_to_pyradio -d` looks like in `pyradio`

![Mabox_20230326-00-43-00](https://user-images.githubusercontent.com/5807638/227746116-93efaec3-897d-4b90-ae63-c428a78f500c.png)

To check it out, please get his repo and get to the `devel` branch: https://github.com/s-n-g/pyradio

Also, expect a PR to your repo

**Comment by LionyxML** [comment]
Wooow, this is really nice! Thanks a lot for your PR.

I just uploaded a `0.0.3` version of `m3u-to-pyradio-playlist` to PyPi with your additions and some minor fixes on my setup.py.

I am glad I could help!
