### ISSUE TITLE
[THEMES] Problem with background

### ISSUE THREAD

**Issue by napcok** [coderholic/pyradio#191]
Seems like background is not updated after edit/change theme.
All other elements works fine.

Greetings :)

**Comment by s-n-g** [comment]
Hi @napcok 

What do you mean exactly?


https://github.com/coderholic/pyradio/assets/5807638/3e0452ec-7473-4f4b-a70a-25ae829c7fc8

**Comment by napcok** [comment]
Ok, I got it. Changed global setting use_transparency to False
So seems like only setting from theme is not effective or I misunderstand something :)
```
# Theme Transparency
# Values are:
#   0: No transparency (default)
#   1: Theme is transparent
#   2: Obey config setting
transparency        0
```

**Comment by s-n-g** [comment]
Yes!
When transparency is on, it really beans no background color.
Then you just see the terminal's background color.
Does not work well with light themes :(

**Comment by napcok** [comment]
So 2 (Obey config settings) is a little misleading. Or I wrongly assumed that 0 and 1 do not obey config settings.

**Comment by s-n-g** [comment]
Ok, so here how it goes:
- 0: the theme will not enable transparency by itself; the user can enable it temporarily (press "T") but next time you run pyradio the theme will not have transparency.
- 1: the theme will enable transparency by itself; the user can disable it temporarily (press "T") but next time you run pyradio the theme will have transparency on.
- 2: when you start pyradio (or load the theme) its transparency depends on current setting of transparency.

That's how it's supposed to be, anyway...

**Comment by napcok** [comment]
Ok, anyway for Colorizer PyRadio module and themes it generates transparency makes no sense.
 I have to figure it out. I'm closing issue, as in fact this is not an issue with PyRadio.
