### ISSUE TITLE
Feature Suggestion - Quick add station(s) from station browser

### ISSUE THREAD

**Issue by nikisix** [coderholic/pyradio#193]
Currently my sequence for adding a new station is:
1. 'O' - open browser
2. 'space' - start playing a station
3. 'i' - open station info
4. copy url (and try and remember station name as entered)
5. 'q' - go back to default playlist
6. 'a' - add station
7. enter station name and url

The request is for a key mapping in the browse-mode that adds a station to the current playlist.

**Comment by s-n-g** [comment]
Hi @nikisix 

No need to go into all that trouble.

You just press
1. "y" and ENTER on any station (copy station)
2. "\p" and select a playlist (in this case it's just one: **stations**)
3. ENTER to paste it there

The station will be appended to the playlist

I do hope that's easy and quick :)

https://github.com/coderholic/pyradio/assets/5807638/c6884a21-8feb-4655-9902-9f3764439e3f

**Comment by s-n-g** [comment]
ok, I don't think I'm gonna get a reply...
Closing...

**Comment by nikisix** [comment]
Thanks I'll give this a shot!

**Comment by nikisix** [comment]
Works! Was " not available for register access or something?

Thanks for a great piece of software. This is all I use now. Just bought a orange pi 3lts and am going to turn it into a pyradio player ;)

**Comment by s-n-g** [comment]
Yes, it's sing'e quote

' + a-z : show register
' + '     : open register list

:wink:
