### ISSUE TITLE
Newest Windows install cannot find the path specified.

### ISSUE THREAD

**Issue by amski1** [coderholic/pyradio#196]
Fresh install on a new computer. I think the screenshot says it all. I tried circumnavigating this by manually extracting the pyradio-0.9.2.7.zip and relaunching setup.py, but it deletes all the files in the pyradio-tmp directory. I think the build doesn't even start, it just progresses to MPV. I don't know how to fix this:

![Error](https://github.com/coderholic/pyradio/assets/12321498/fe22a0dc-87a9-4dff-b7b8-9887821d6e50)

**Comment by s-n-g** [comment]
Hi @amski1 

What is your PATH?
Execute `echo %PATH%` (on console) or `echo $Env:Path` (on powershell) and post the result

**Comment by s-n-g** [comment]
Just committed an update to the `install.py` file.

Please download the new file and try the installation again

**Comment by amski1** [comment]
It was middle of the night for me when you did this, so I will test it now. Thank you for such a quick commit.

**Comment by amski1** [comment]
So the install completed. Thank you for the change. But what was wrong?

I did take the screenshot of %PATH% command. I would think it has to do something with empty space in "Program Files"? 

What's your take on that?

![PATH](https://github.com/coderholic/pyradio/assets/12321498/a50188d1-89a9-4934-8308-3fb56dbf69bf)
