### ISSUE TITLE
PyRadio 0.9.2.7 with Python 3.10.4 and 3.11.4 won't connect to any streams using its own MPV install.

### ISSUE THREAD

**Issue by amski1** [coderholic/pyradio#197]
**Please forgive me for creating a new one**, but it just won't play with MPV. I had to manually edit the config file to force PyRadio to use VLC, which plays fine.

Also, when it plays, there's a substantial CPU overhead from Python, around 20%.

![CPU](https://github.com/coderholic/pyradio/assets/12321498/d8d63344-dda0-414b-9611-d0db1171bed4)

I'm attaching the log.

[pyradio.log](https://github.com/coderholic/pyradio/files/11689879/pyradio.log)

**Comment by s-n-g** [comment]
Do not worry about it!
I am happy to look into this

So, it seems `mpv` crashed but I have no clue as to why it did

I see you are trying to open a flack station, so does `mpv` play any of the stations in the original `stations.csv`? (test 1)

To change player on the fly, press "**\m** and select.


Also try to execute:
(test 2)
```
C:\Users\Admin\AppData\Roaming\pyradio\mpv\mpv.exe --no-video --quiet http://hd.stream.frequence3.net/frequence3.flac
```

Does this one play?


If it does, try also this one (test 3)
```
C:\Users\Admin\AppData\Roaming\pyradio\mpv\mpv.exe --no-video --quiet http://hd.stream.frequence3.net/frequence3.flac --input-ipc-server=\\.\pipe\mpvsocket.5284
```

So, three tests :wink:

**Comment by amski1** [comment]
Test 1: no, mp3 streams don't play either

**Comment by s-n-g** [comment]
Yes, try to install any one of the `64bit`, `64bit-v3` versions from:

https://sourceforge.net/projects/mpv-player-windows/files/

This will download a `7z` file.

Create a folder named `mpv` and extract the `7z` file in it.

Then move the `mpv` folder in `C:\Users\Admin\AppData\Roaming\pyradio`

Then try tests 1, 2, 3

Finally try using it with `pyradio`


BTW, this is my experience with `pyradio` on Windows


https://github.com/coderholic/pyradio/assets/5807638/fd6a3b82-03e5-4a17-8b89-686d648d42c8

**Comment by amski1** [comment]
Cool video, I like how your main OS is Linux. By the way, I hope that folks understand the bitrate being reported in the station info is not accurate. It'll say 128kbps, but in reality it's lossless. I don't know what causes the mismatch, but older software used to report it correctly. 

I'll do the manual MPV install and report back.

**Comment by amski1** [comment]
Fixed. Your instructions with manual download and extraction worked perfectly. 

Thank you so much.

**Comment by s-n-g** [comment]
> Even the volume control works better with mpv than with vlc, I just wish it wouldn't reset each time I restart PyRadio

You can press "**v**" to save the volume.

I would suggest you press "**?**" to open the help and see what functionality is there. And then go and read about it in the README :wink:

**Comment by amski1** [comment]
Hate to revive this closed thread, but the _install.py_ pulls some weird type of installation of MPV because once you launch PyRadio it never works, hangs on connection and counts down to zero, then stops. 

I have to always manually go to the MPV [website](https://sourceforge.net/projects/mpv-player-windows/files/) and download from 64bit directory (NOT the 64bit-v3)

**Comment by s-n-g** [comment]
Here's the difference...

https://github.com/shinchiro/mpv-winbuild-cmake/wiki/Difference-between-x86_64-and-x86_64-v3

**Comment by amski1** [comment]
OK, so we know it's instructions-bound according to the CPU. Granted, one of my machines has i7-3820QM. Surely an instruction set is missing.

I guess it's up to you to warn about it or probe for CPU during install and grab the proper version. 🤷‍♂️

But thank you so much for finding it.

**Comment by s-n-g** [comment]
No, I think I will just scrap the latest `x86_64` url in install.py...

I think going for maximum compatibility is the best option

**Comment by amski1** [comment]
So you're going to point the script towards the non-v3? Or will you bundle it with the installer? 

I agree with the max compatibility route.

**Comment by s-n-g** [comment]
I will extract the first 7z file url from 

  https://sourceforge.net/projects/mpv-player-windows/files/64bit/

 and use that to download the "latest" archive, instead of using the url I've been using up until now

 https://sourceforge.net/projects/mpv-player-windows/files/latest/download

which points to the v3 file
