### ISSUE TITLE
SomaFm stations are not connecting thru pyRadio

### ISSUE THREAD

**Issue by lobaluna** [coderholic/pyradio#199]
Hi! I'm a great fan of this application. Thanks so much!

Recently, I'm unable to connect to any SomaFM station thru pyRadio. I already checked that using the same link you have in stations.csv. I can play it thru Audacious or using the SomaFM built-in player, for example, but not using pyRadio.

Other stations are connecting perfectly, as the Lofi group, for example.

Maybe there are some changes for SomaFM, specifically? Or do I have to check some option in my configuration? Just to be clear, I'm using the default config.

**Comment by s-n-g** [comment]
Hi @lobaluna 

As far as I can see, nothing is changed...
Can you please post your log file trying to connect to a couple of SomaFM stations?

```
rm ~/pyradio.log
pyradio -d
```

SomaFM stations connecting

https://github.com/coderholic/pyradio/assets/5807638/2e19ebf5-ddc2-4d1b-8272-ea506cb0bb02

**Comment by lobaluna** [comment]
Hey, @s-n-g!

I screenrecorded the issue, using the Mabox shortcut. 

At first, apparently I could connect to SomaFM the first time I ran `pyradio -d` in terminal, manually (not thru the Mabox shortcut, which, BTW, it calls `pyradio -p`). But the second and following runs, I couldn't connect. My problem is with SomaFM stations, only.

The log: 
[pyradio.log](https://github.com/coderholic/pyradio/files/11877566/pyradio.log)
[rec_20230626_22-05-59.webm]

The recording:
(https://github.com/coderholic/pyradio/assets/10353579/da0ce27a-b479-491f-afa7-1979247dd3ed)

**Comment by s-n-g** [comment]
Does this work every time (from a terminal)?

```
mpv --no-video --quiet http://radio.stereoscenic.com/asp-h \ 
--input-ipc-server=/tmp/mpvsocket.2233707 --profile=pyradio
```

**Comment by lobaluna** [comment]
It worked.
I tried pyRadio in another machine, with Arch Linux instead of Mabox.It fails connecting to SomAFM thru pyRadio, but not thru mpv directly... (see the attached image).
At first, I thought my ISP was the culprit, somehow, but now I don't, with this rapid test.

Celia Palacios.Ego sum in porta limine. 

    El martes, 27 de junio de 2023, 04:55:18 a. m. CST, Spiros Georgaras ***@***.***> escribió:  
 
 


Does this work every time (from a terminal)?
mpv --no-video --quiet http://radio.stereoscenic.com/asp-h \ 
--input-ipc-server=/tmp/mpvsocket.2233707 --profile=pyradio

**Comment by s-n-g** [comment]
ok, let's take it from the begining :)

From your log I see that
1. the player starts
2. in 10 seconds the player stops (connection failure)

Do you **hear any sound** during this period of 10 seconds?

BTW, do you have any mpv lua scripts installed?
If you do, please remove them and try again

In you still have problems, let's try the next debugging step.
Open a terminal and execute:

```
pacman -Ql pyradio | grep player.py | sed 's/.* //'
```

or 
```
pacman -Ql pyradio-git | grep player.py | sed 's/.* //'
```

depending on the package you have installed.

You will get something like this:
```
/usr/lib/python3.11/site-packages/pyradio/player.py
```
which is the location of the file `player.py`

Open this file with `sudo`, for example
```
sudo vim /usr/lib/python3.11/site-packages/pyradio/player.py
```
or 
```
sudo nano /usr/lib/python3.11/site-packages/pyradio/player.py
```
or whatever text editor you are using and make the changes you see in the following image



![player py](https://github.com/coderholic/pyradio/assets/5807638/ac0c837e-80d4-4cb9-8b7a-216ff145ca0a)

Then:

```
cd
rm pyradio.log
pyradio -d
``

Try to play a player which fails and send the log file again ( `pyradio.log` )

**Comment by lobaluna** [comment]
Hi, s-n-g, sorry for the delay. I had many things on my table.

1. While it's trying to connect, those 10 sec, no I do not hear anything at all.

2. No, I haven't installed any `lua` script, nor `mpv lua` script.

3. Here's the new `pyradio.log`, according to your instructions. Just for the record, those lines modified were 1075 and 1093 (in my actual version of pyradio, `/usr/lib/python3.11/site-packages/pyradio/player.py`). It's nothing important, but just to let you know.

[pyradio.log](https://github.com/coderholic/pyradio/files/11943605/pyradio.log)

And to recheck, after modifying the `pyradio.py`, the very first station (in the default `stations.csv` file) starts to play without incident.

**Comment by s-n-g** [comment]
Hi again @lobaluna 

I know...

Does adding 5 or 10 seconds to the timeout value make any difference?

To change it, press "**c**" and then adjust "**Connection timeout**" (with **j**, **k** or left, right arrow) and press "**s**" to save the config file.

**Comment by s-n-g** [comment]
If that does not work, make another change to the code, same file as before.

Around **line 1137**, you will find 

```
                                        elif d['event'] == 'playback-restart':
```

please change it to 

```
                                        elif d['event'] == 'playback-restart' or \
                                                d['event'] == 'start-file':
```

Just make sure that the white-space at the beginning of each line contains spaces only, no tab characters, otherwise it will not work.

![pyradio-code-change](https://github.com/coderholic/pyradio/assets/5807638/29c840c2-ccca-428b-966e-55a5f58cf598)


If that does not work either, please send the **pyradio.log** file again...

**Comment by lobaluna** [comment]
Hi, dear and patient s-n-g!

It worked!! Increasing the connection timeout worked! Funny thing that SomaFM stations need 15 sec in the PyRadio, and not outside of it, but the mystery is no longer!

Thank you very much for your patience and invaluable help.

PyRadio rocks! I love you made it possible to theme it thru Mabox Colorizer. Thanks again, and have a good day.

**Comment by s-n-g** [comment]
I am glad it finally worked! :wink: 

Yes!
Mabox Colorizer is wonderful!
