### ISSUE TITLE
Feature Suggestion - Buffer length setting

### ISSUE THREAD

**Issue by Sinaaaa** [coderholic/pyradio#200]
Hello!

In my experience the best internet radio stations are often overloaded  & as such there are lot of cutouts in music. To deal with this it would amazing if Pyradio (the best radio program right now, since Radiosure is pretty much done) could be set up to allow for really long buffers. (for example 30 seconds, at the cost of the playback starting 30s later, but rarely having to deal with buffer underrun) If the buffer size has to be given in kilobytes that would also be fantastic of course..

Keep up the good work!

**Comment by s-n-g** [comment]
Hi @Sinaaaa 

This is a feature we have discussed here in the past, but did not get to a definite conclusion...

Anyway, for the task at hand, I believe buffering can be achieved using the player's profiles or extra command line parameters.

Let me ask you first of all which player is your default one?

**Comment by Sinaaaa** [comment]
I'm using Arch, the player is mpv.

**Comment by s-n-g** [comment]
ok, great!

here's a test for you... Add this to `~/.config/mpv/mpv.conf`

```
[pyradio_cache]
cache=yes
cache-secs=30
cache-on-disk=yes
```

Then, in a terminal

```
mpv --no-video -v --profile=pyradio_cache URL
```

you may have to use this:
```
mpv --no-video -v --profile=pyradio_cache --playlist=URL
```

Does that makes any difference with one of the overloaded stations?

**Comment by s-n-g** [comment]
BTW, here's the relevant documentation

https://mpv.io/manual/stable/#cache

https://mpv.io/manual/stable/#profiles

**Comment by s-n-g** [comment]
After reading a bit more, this will probably do the job :wink: 

```
[pyradio_cache]
demuxer-readahead-secs=30
demuxer-cache-wait=yes
cache=yes
cache-secs=35
cache-on-disk=yes
```

**Comment by s-n-g** [comment]
So, you can see there are so many options regarding buffering...

You will just have to find the ones best for you and add them to a profile

Then, there are two things you should do to get them to work with PyRadio

1. Instruct the player to use your buffering profile
2. Adjust the playback timeout accordingly, probably setting it to 30?

Do you know how to enable these options?

**Comment by Sinaaaa** [comment]
> 

The second one works, with 'cache-on-disk=no' as well, which is the preferred option. How do I get this stick with Pyradio?  
(mpv --no-video -v --profile=pyradio_cache URL is the winner)

I suppose I could just make script files for all my fav radio stations & call it a day, probably half an hour is enough to get this done, though it would be nice if my family members could use the Pyradio interface.

**Comment by Sinaaaa** [comment]
> Do you know how to enable these options?

Nope, I'm trying to figure it out, but don't see it in the config menu.

**Comment by s-n-g** [comment]
No, just go to the setup

Press `c` and you are there.

Wait, I'll create a video...

**Comment by Sinaaaa** [comment]
>Press c and you are there. 

That's what I call 'config'

**Comment by Sinaaaa** [comment]
Probably I'm blind lol

**Comment by Sinaaaa** [comment]
Ah I think I found it, it's within the player selection.

**Comment by s-n-g** [comment]
https://github.com/coderholic/pyradio/assets/5807638/f71868cd-6213-4483-802d-cf6f3d1cee72

**Comment by Sinaaaa** [comment]
It works with most, but not all stations. Thank you for the immense help!

Minor hiccups I've had: needed to set timeout to buffer+ seconds, and pyradio did not see the the third profile, I suppose I've found a bug.

**Comment by s-n-g** [comment]
ok, I hope that works for you!

When you think you are satisfied, please do close the issue :wink:

**Comment by s-n-g** [comment]
> and pyradio did not see the the third profile

let me check...

**Comment by Sinaaaa** [comment]
https://imgur.com/a/74ETb2i   Pyradio only sees the first two profiles.

https://imgur.com/a/vF7CS6Y

**Comment by s-n-g** [comment]
No, the profiles are not read automatically, you have to insert them by hand in the config.

You also have to set the default profile, after you insert it (press space and s).

**Comment by s-n-g** [comment]
Just a notification...

Version 0.9.2.14 has buffering support, no need to create and edit profiles anymore, and no meddling with the timeout value :)

Just restore the normal profile, and use **\B** to set your buffer (**\b** will toggle buffering)

Feel free to close this one after you've read it, or report any issue, if found

**Comment by Sinaaaa** [comment]
It's working well, thanks a ton!

(It's not important, but I think a 250KB option would be quite useful for some of those really low bitrate stations)

**Comment by s-n-g** [comment]
> It's working well, thanks a ton!
> 
> (It's not important, but I think a 250KB option would be quite useful for some of those really low bitrate stations, 500KB is about 90 seconds with my fav station)

Will do, I am preparing a bug fix release, so... :wink:

**Comment by s-n-g** [comment]
Done in **0.9.2.15** :wink:
