### ISSUE TITLE
PyRadio AM Theme

### ISSUE THREAD

**Issue by amski1** [coderholic/pyradio#202]
A little theme I spent some time creating.

[AM.zip](https://github.com/coderholic/pyradio/files/12664754/AM.zip)

**Comment by s-n-g** [comment]
Nice one!

Renamed it to "**AM_by_amski1**", hope you don't mind.
Will be included in the next release

Here it is with **Calculated color = 0.02**

![Mabox_20230919-21-56-38](https://github.com/coderholic/pyradio/assets/5807638/e19117db-fe9d-4e55-865b-81889d3cf3d5)

**Comment by amski1** [comment]
Don't mind at all. I'd be honored. 

What's a "calculated color"?

The dark green looks slightly different on Windows than it does on Linux, but I guess it depends on the monitor's color profile...

**Comment by s-n-g** [comment]
![Mabox_20230919-22-09-13](https://github.com/coderholic/pyradio/assets/5807638/b391cb98-6502-4be1-b5b7-5693f778ce36)

It's this config setting...

> The dark green looks slightly different on Windows than it does on Linux, but I guess it depends on the monitor's color profile...

Yes...
That sounds right :wink:

**Comment by amski1** [comment]
I see. I left the house, but when I'm back I'll check what's on my side. If the calculated color occurs or not.

It appears easy, but in reality it's pretty hard to pick a good set of colors. I started making the theme and then it hit me... oh, this will take a while 😂

**Comment by s-n-g** [comment]
😂
I know, playing with colors is so fun!

You can make all the changes you think necessary, even after it has been released, we can still update it in a future release 

BTW, why don't you experiment with transparency as well?

```
# Theme Transparency
# Values are:
#   0: No transparency (default)
#   1: Theme is transparent
#   2: Obey config setting
transparency        0
```
Setting **transparency** to 2, and pressing "**T**" will enable it...
I think a "dark" theme (like yours) would look good with transparency ON

**Comment by amski1** [comment]
I think that on Windows it's not possible to get transparency in CMD. Would have to go with the new terminal, which seems... heavy to say the least. 

If it's required then I'll do it. Don't mind it.

**Comment by s-n-g** [comment]
This is on **Window 11, Powershell** (transparency set to 85%, pressing "**T**", after changing **transparency** to 2 in the theme)


https://github.com/coderholic/pyradio/assets/5807638/07d1a1f8-cf7c-4e33-a6bd-ee3c8cf6d93f

And here's the settings

![win11-transparency](https://github.com/coderholic/pyradio/assets/5807638/bf600a57-83fa-4f3a-97dc-3f6d130262d9)

You will get similar result on **Windows 10* with **Powershell**.

Looking into Windows7 as well

**Comment by amski1** [comment]
True, works good on PowerShell

**Comment by s-n-g** [comment]
Have you enabled transparency then?
You are on 10 or 11?
No need to look for a Windows 7 solution?

**Comment by amski1** [comment]
Yes, on PowerShell and it looks fine with the theme set to **2**. When you hold CTRL, SHIFT and scroll the mouse wheel, the transparency changes on the fly.

**Comment by s-n-g** [comment]
Things are a bit different on linux and mac though

With Powershell on windows, you get the transparency because of the window transparency, without having to press "**T**".

If you do press "**T**" on Windows, you will see what a linux (or mac) user will see when transparency is no (well, almost). Do you still think it's ok?

Watch the video above to see what I mean :wink:

**Comment by amski1** [comment]
I know. It doesn't honor transparency with **T**, becomes black. Transparency in CMD and PowerShell on W10 seems to be adjustable on the system GUI level, separate from what's drawn inside the command prompt.

**Comment by amski1** [comment]
How it looks on my end:

https://github.com/coderholic/pyradio/assets/12321498/fc2f14ba-61b7-4a16-9765-6206750ac079

**Comment by amski1** [comment]
Is it possible to have the now-playing station in bold font?

**Comment by s-n-g** [comment]
> Is it possible to have the now-playing station in bold font?

No, not at the moment, and I think it may be too complicated to achieve (not all terminals support bold, I think)
I will have to look into it...

**Comment by s-n-g** [comment]
The theme is part of **Version 0.9.2.14**
Thanks for the contribution!
Closing...

**Comment by amski1** [comment]
😍

**Comment by amski1** [comment]
I apologize to post within this old thread, but I'd rather avoid opening a new one. Please see if this theme is worthy of anything. I called it λambda (Lambda).

[λambda.zip](https://github.com/user-attachments/files/18311295/ambda.zip)

**Comment by s-n-g** [comment]
Tat is very nice!

I have modified it a bit, added a bit of darker background for the secondary windows.
What do you think?
Can I keep this modification?

This is obviously a mockup...
![mockup](https://github.com/user-attachments/assets/b3af7bd7-a639-40ac-88ec-77745eadbe02)



Also, regardless of the change above, can we rename it to `lambda_by_amski1`?
I would like to have ascii only in items bundled withing the package

**Comment by amski1** [comment]
Yes, absolutely. Cool gif, by the way.

**Comment by s-n-g** [comment]
This is still under development, you will get it when the next release is out :wink:

**Comment by amski1** [comment]
Wonderful. Props to whoever came up with it.

**Comment by s-n-g** [comment]
https://github.com/coderholic/pyradio/issues/268

**Comment by amski1** [comment]
😄
