### ISSUE TITLE
The largest README in human history

### ISSUE THREAD

**Issue by webpolis** [coderholic/pyradio#206]
Come on! I loss my finger while scrolling down.

**Comment by s-n-g** [comment]
I know :blush:

What would you recommend, though?

**Comment by webpolis** [comment]
> I know 😊
> 
> What would you recommend, though?

A more compact readme, a summary, and then have a separate docs page. It currently scares me a bit as it seems to be a very complex app.

**Comment by s-n-g** [comment]
Yes, I see what you mean...
I will consider it for the future

It's actually a pretty simple app though...
Select a station, press **ENTER** and you are done
That simple :wink: 

Press "**?**" to get a list of all the keys you need for basic usage...

I never thought that this would be an issue...
I always thought that the manual installation procedure would be the one thing to intimidate people...

**Comment by s-n-g** [comment]
Is this what you had in mind?

https://github.com/s-n-g/pyradio/tree/devel

**Comment by webpolis** [comment]
Looks awesome and more friendly. Thank you for your prompt response.

**Comment by s-n-g** [comment]
> Looks awesome and more friendly. Thank you for your prompt response.

Thank you pointing it out!

Do keep in mind though, this is a personal development repo, the changes will not take effect until pyradio's next release
