### ISSUE TITLE
pyradio times out the connection because status never shows connected

### ISSUE THREAD

**Issue by PhilT001** [coderholic/pyradio#209]
Pyradio always shows "Opening connection" even after it has successfully connected. It then disconnects (gives up) after the time out period. Setting the time out value to zero (0) allows me to listen to my chosen stations, but the status always shows "Opening connection"

I am using pyradio 0.9.2.20 and python 3.11.6 

All the modules were installed using pip so they should be the latest versions.

I am running this in Termux on my cars android head unit.

I'm using mpv for playback and I can play the stations directly in mpv without issue.

**Comment by s-n-g** [comment]
Hi @PhilT001 

This may be a OS / hardware problem.

The thing is that `mpv` uses a socket to communicate with `pyradio` and it would be really hard to debug this on a piece of hardware I do not have at hand.

From the message ("Opening connection") that you have, it seems to me that there is no communication between `mpv` and `pyradio` ; can you adjust the volume at all (pressing **+**/**-**), for example?

Does a file `/tmp/mpvsocket.*` exist while `mpv` is in playback?
If that's the case, execute

```
cd
rm pyradio.log
pyradio -d
```

play a station for a few minutes and exit `pyradio`. Then post here the file `~/pyraio.log`

BTW, have you tried another player?
`pyradio` reads the standard output of both `mplayer` and `vlc`, so chances are you'd have better results with either of them...

**Comment by PhilT001** [comment]
Hi, thanks for your reply.

I'll try your suggestions this coming weekend (I won't have access to the android unit until then)
