### ISSUE TITLE
update error 0.9.2.13 to 0.9.2.20 possibly missing dependency

### ISSUE THREAD

**Issue by lee2sman** [coderholic/pyradio#211]
```
Released version   :  0.9.2.20
Installed version  :  0.9.2.13
Updating PyRadio...
Using directory: "/home/void/.config/pyradio/data/.cache"
Old "/home/void/.config/pyradio/data/.cache" found. Deleting...
Downloading PyRadio source code...
  url: "https://github.com/coderholic/pyradio/archive/0.9.2.20.zip"
  filename: "/home/void/.config/pyradio/data/.cache/pyradio-0.9.2.20.zip"
  ** file found in cache!
Extracting RyRadio source code...
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.12/site-packages/pipx/__main__.py", line 14, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/lib/python3.12/site-packages/pipx/main.py", line 863, in cli
    return run_pipx_command(parsed_pipx_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pipx/main.py", line 214, in run_pipx_command
    return commands.install(
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pipx/commands/install.py", line 30, in install
    package_name = package_name_from_spec(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pipx/commands/common.py", line 332, in package_name_from_spec
    package_name = venv.install_package_no_deps(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pipx/venv.py", line 281, in install_package_no_deps
    old_package_set = self.list_installed_packages()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pipx/venv.py", line 362, in list_installed_packages
    pip_list = json.loads(cmd_run.stdout.strip())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
The installation has failed!!!
Please report this at https://github.com/coderholic/pyradio/issues
```

**Comment by lee2sman** [comment]
Thanks, I''m on void linux and i realized it's related to the change in python packaging upstream. I'm using the packaged pyradio for my distro, but i realize i'm getting prompts to update even though my distro hasn't issued an update yet.

**Comment by s-n-g** [comment]
So, void provides a distro package!

Installing on vm...

**Comment by s-n-g** [comment]
So, there are two things here

1. pyradio 0.9.2.13 is a distro package \
The package is not properly prepared, the packager has not taken into account [PyRadio Packagers' Info](https://github.com/coderholic/pyradio/blob/master/docs/packagers-info.md). \
\
The result is that the pyradio distro premits you to install from a non-distro source, which should not be happening

2. You still cannot install pyradio (using `pythonh install.py) \
\
I have installed void on a vm, and was able to install 0.9.20 with `pipx`. \
\
So I ended up having two pyradio versions installed :1st_place_medal: 

Look at this video


https://github.com/coderholic/pyradio/assets/5807638/b34d0a90-d952-4ae5-9ea9-9eb33fd4976d


So, I don't know, you either stick with the distro package (and inform the packager to fix it, and upgrade it), or you remove the distro package, remove `~/.local/pipx` and follow this: [PyRadio pipx installation on Linux](https://github.com/coderholic/pyradio/blob/master/docs/linux-pipx.md), adjusting commands as necessary for void.

**Comment by lee2sman** [comment]
thanks for looking into this. i'll try the first, and if no response, will try the second. i appreciate it.

**Comment by s-n-g** [comment]
I have just seen your bug report @ void repo and part of it is not true

> pyradio now needs pipx for install so won't be able to update without that

This part is incorrect.

using `pipx` has nothing to do with the auto update feature. Auto update is disabled when the packager declares that the package is a "distro package" (`distro = Void Linux` in the config file, for example). It's all in the packagers' info.

`pipx` is used **only** when building from source (i.e. not in the case of a "distro package"). A distro can use whatever way suitable for it. For example, look at the **PKGBUILD** file for Arch (which is maintained by me):

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pyradio

1. In `prepare()` the auto update is disabled.
2. In `build()` a wheel is created
3. In `package()` the actual installation takes place

This file is in accordance with the latest arch guidelines about installing python programs

**Comment by s-n-g** [comment]
Now, I know nothing about the void linux build system, but I just found this template:

https://github.com/void-linux/void-packages/blob/master/srcpkgs/pyradio/template

If this is the file used to build pyradio for void, there's a couple of additions it should have in order to build 0.9.2.20:

1. dependencies are missing
2. Three out of four man pages are not being installed
3. No `distro = Void Linux` can be added (probably a "prepare" function should be added

Hope that helps

**Comment by s-n-g** [comment]
Nice!
I see you have adopted the package!

If there's any problem in the future, don't hesitate to contact me

**Comment by lee2sman** [comment]
That's not me, but the Void devs (and volunteers) are extremely active! And I'm hopefully going to learn how to package things, from watching this process.
