### ISSUE TITLE
An option to disable update notification?

### ISSUE THREAD

**Issue by amano-kenji** [coderholic/pyradio#212]
If people installed pyradio from linux distribution, they likely don't want to see update notification.

**Comment by s-n-g** [comment]
Can you please give more info?

**Comment by amano-kenji** [comment]
> PyRadio will periodically (once every 10 days) check whether a new version has been released.
>
> If so, a notification message will be displayed, informing the user about it and asking to proceed with updating the program (provided this is not a distribution package).

**Comment by s-n-g** [comment]
There is

Just have a look at [PyRadio Packagers' Info](https://github.com/coderholic/pyradio/blob/master/docs/packagers-info.md)

**Comment by amano-kenji** [comment]
Okay.
