### ISSUE TITLE
Clean up ~/.config/pyradio

### ISSUE THREAD

**Issue by amano-kenji** [coderholic/pyradio#214]
* ~/.config/pyradio/data should go to ~/.local/share/pyradio
  * https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
* What are these for?
  * ~/.config/pyradio/data/cover.png
  * ~/.config/pyradio/data/pyradio.png
* stations.csv is created whenever I delete it. Perhaps, is it better to show `site-packages/pyradio/stations.csv` as `built-in stations` in playlist list? If `default_playlist` is empty in config, then `default_playlist` is the built-in playlist. Instead of copying `stations.csv` to `~/.config/pyradio`, make it unmodifiable. I think users should have explicit control over playlists in ~/.config/pyradio.
* ~/.config/pyradio/recordings does not belong in ~/.config/pyradio. Perhaps, recordings directory should be configurable with a sensible default value like `~/pyradio-recordings`.

**Comment by s-n-g** [comment]
> ~/.config/pyradio/data should go to ~/.local/share/pyradio
>    https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

The data contained in this folder are actually part of the user's configuration; it's containts partly depend on the way the program is used, so...
I would have to think about this one... 

> What are these for?
>    ~/.config/pyradio/data/cover.png
>   ~/.config/pyradio/data/pyradio.png

These are icons needed for Desktop notification and desktop file (pyradio.png) and station recording using `mkvtoolnix` (cover.png). They are there because I've been having problems locating them through various OS (MacOS is the king here), so having them at a predefined location was the solution.

> stations.csv is created whenever I delete it. Perhaps, is it better to show `site-packages/pyradio/stations.csv` as built-in stations in playlist list?

No, that's not the way it would work.
The file is copied to `~/.config/pyradio` so the user can edit it as he wants, even replace all stations with his own.
If he wants to revert to the package provided stations, he can simply delete the file and it will be regenerated (copied).

This has been the behavior for a long time and I would not like to change it; it would just create unnecessary confusion.

> If `default_playlist` is empty in config, then `default_playlist` is the built-in playlist. Instead of copying `stations.csv` to `~/.config/pyradio`, make it unmodifiable. I think users should have explicit control over playlists in `~/.config/pyradio`.

Users do have explicit control over playlists in `~/.config/pyradio`; with the exception of `stations.csv` as explained above.
Other than that, he can create / edit /delete playlists at will and set the default one using `default_playlist` / `default_station`

So, I would be very reluctant to change anything here...

> `~/.config/pyradio/recordings` does not belong in `~/.config/pyradio`. Perhaps, recordings directory should be configurable with a sensible default value like `~/pyradio-recordings`.

I would agree with you here; I have been thinking about it as well; just did not have the time to implement the required config / transfer functionality. Maybe it is time to do that, along with #215

**Comment by amano-kenji** [comment]
It seems to me that you can just keep `cover.png` and `pyradio.png` in `site-packages/pyradio`.

> This has been the behavior for a long time and I would not like to change it; it would just create unnecessary confusion.

Is this behavior documented somewhere?

**Comment by s-n-g** [comment]
> It seems to me that you can just keep `cover.png` and `pyradio.png` in `site-packages/pyradio`.

That's exactly what I intended to do at the beginning, but as I've said I used to have problems locating the files, so I just copied them to `data`. I might revisit this behavior in the future, but for the time being they are there :wink: 

> Is this behavior documented somewhere? I'm not going to fuss about small details, but I want to see details documented.

It's right here: https://github.com/coderholic/pyradio/blob/master/docs/index.md#about-playlist-files

**PyRadio** will by default load the user's stations file (e.g. *~/.config/pyradio/stations.csv*) to read the stations from. If this file is not found, it will be created and populated with a default set of stations.

**Note:** Older versions used to use **~/.pyradio** as default stations file. If this file is found, it will be copied to use's config directory (e.g. **~/.config/pyradio**) and renamed to **stations.csv** or if this file exists, to **pyradio.csv**. In this case, this file will be the default one.

> If contents in `~/.config/pyradio/data` don't correspond to changes in configuration interface, then they are not exactly configuration.

The files in `~/.config/pyradio/data` may not correspond to changes in configuration interface, but they do change program behavior... There's data about last `stations.csv` sync, last version update check, players buffer size, vlc configuration, scheduler configuration (still working on it...), search terms history, etc.

**Comment by amano-kenji** [comment]
Things like search terms history and last version update check usually belong in `~/.local/share/PROGRAM-NAME`.

neovim stores such data in `~/.local/share/nvim`

**Comment by s-n-g** [comment]
Thanks for the heads up!
I will look into it!

**Comment by amano-kenji** [comment]
Upon further inspection, I discovered that `~/.local/share/nvim` contains files that can be reproduced on any computer.

`~/.local/share/nvim` contains neovim packages.

On the other hand, `~/.local/state/nvim` contains application state such as search history.

Thus, I believe image files belong in either  `~/.local/share/pyradio` or `site-package/pyradio` and other files in `~/.config/pyradio/data` belong in `~/.local/state/pyradio`.

**Comment by amano-kenji** [comment]
By the way, what is `vlc.conf` for?

**Comment by s-n-g** [comment]
`vlc.conf` is to save vlc volume; vlc can report the volume but there's a problem here, some versions report with a maximum of 1000 and some versions with a maximum of 512, so... yes...

I've also remembered why I like having all config files in one place. I had to reinstall a pc yesterday at work (changing distro) and wanted to have pyradio also; I just had to tar on folder `~/.config/pyradio` and transfer it to the "new" pc, done :)

**Comment by amano-kenji** [comment]
If vlc, mplayer, and mpv share the same volume, isn't it easier to save the volume as `~/.config/pyradio/volume` and execute `mpv|mplayer|vlc --volume=xxx ...`?

**Comment by amano-kenji** [comment]
Because XDG base directory specification says actions history (logs, history, recently used files, …) belongs to $XDG_STATE_HOME, `pyradio-title.log` should go to `$XDG_STATE_HOME`.

**Comment by amano-kenji** [comment]
I came up with this summary.

* `data/cover.png` and `data/pyradio.png`
  * `$XDG_CACHE_HOME/pyradio`
* `data/last-playlist`, `data/last-sync`, `data/search-playlist.txt`, `data/search-station.txt`, `data/UPDATE_ICON`, `pyradio-titles.log`
  * `$XDG_STATE_HOME/pyradio`
* `data/vlc.conf` (This should become `volume` that stores the volume for every player)
  * `$XDG_STATE_HOME/pyradio/volume`
  * `$XDG_DATA_HOME/pyradio/volume` if you want think this should be portable across machines.
  * `$XDG_CONFIG_HOME/pyradio/volume` if you want this in version control system.
* `recordings`
  * `$HOME/pyradio-recordings`?
  * `$XDG_DATA_HOME/pyradio/recordings`?

**Comment by amano-kenji** [comment]
> /home/spiros/.local/share/pyradio/pyradio.png
> /home/spiros/.local/share/pyradio/cover.png
> /home/spiros/.local/state/pyradio/UPDATE_ICON

I think those belong to `$XDG_CACHE_HOME/pyradio` because they look like cache files. They are not user-specific data. They are not application state. They shouldn't even exist..

> /home/spiros/.local/state/pyradio/vlc.conf

`vlc.conf` should become `volume` which is volume for every player.

> pyradio-recording.txt
> search-theme.txt
> search-group.txt
> search-station.txt
> search-playlist.txt

These files don't seem to be created by pyradio.

> /home/spiros/pyradio-titles.log

I am not sure that I want to see `pyradio-title.log` in `$HOME`.

**Comment by s-n-g** [comment]
>> /home/spiros/.local/share/pyradio/pyradio.png
>> /home/spiros/.local/share/pyradio/cover.png
> > /home/spiros/.local/state/pyradio/UPDATE_ICON
> 
> I think those belong to $XDG_CACHE_HOME/pyradio because they look like cache files. They are not user-specific data.
 > They are not application state. They shouldn't even exist..

Granted; their purpose has already been explained...

>> /home/spiros/.local/state/pyradio/vlc.conf
>
> `vlc.conf` should become `volume` which is volume for every player.

That is not the case; `mpv` and `mplayer` support **profiles**; their default volume is part of a profiles - `vlc` does not support profiles, so this file is for `vlc lolume` only.

>> pyradio-recording.txt
>> search-theme.txt
>> search-group.txt
>> search-station.txt
>> search-playlist.txt
>
> These files don't seem to be created by pyradio.

You are partly right... 

`pyradio-recording.txt` is not created by pyradio; it contains my notes regarding the implementation of the recording functionality...

The other `txt` files are the search terms history files and are created when a search has been performed

>> /home/spiros/pyradio-titles.log
>
> I am not sure that I want to see `pyradio-title.log` in `$HOME`.

I think that's just where it should be; this file is the output of the "**Titles logging**" functionality. It is only created when the user enables it, or when he "likes"/"tags" a title, which means he would want it to be easily accessible

**Comment by amano-kenji** [comment]
> That is not the case; mpv and mplayer support profiles

I want pyradio to keep its own data inside its own folders. It took a while to figure out that pyradio saved its volume level in `~/.config/mpv/mpv.conf`.

mpv supports `--volume` option. mplayer supports `-volume` option. Both options interpret 0 as silence and 100 as full volume.

By passing volume as a command line option, one can have cross-player volume level in pyradio.

**Comment by s-n-g** [comment]
Done in 0.9.3

Please refer to
https://github.com/coderholic/pyradio/blob/master/docs/packaging.md

**Comment by amano-kenji** [comment]
The amount of change seems daunting.

**Comment by s-n-g** [comment]
> The amount of change seems daunting.

Well, yes...
That's why it took so much time and I am expecting bugs to be present for a long time, or at least until users discover them :wink:
