### ISSUE TITLE
Delete playlist in playlist mode

### ISSUE THREAD

**Issue by amano-kenji** [coderholic/pyradio#216]
![2023-12-28 15:43:12](https://github.com/coderholic/pyradio/assets/106365348/662bfd80-b6e9-4650-a0e6-10239e64d0f1)

* `a` to add a playlist in playlist list
* `e` for editing playlist name
* `x` for deleting playlist with confirmation.

**Comment by s-n-g** [comment]
> `a` to add a playlist in playlist list

This one is already implemented; press `\n` to add an empty playlist

This shortcut works both on station mode and playlist mode, I suppose I could add `a` for playlist mode only, but I'm hesitant it might create confusion 


> `e` for editing playlist name

The functionality is already there; open a playlist and you can:

1. add a station (`a` / `A`)
2. delete a station (`x` / `DEL`)
3. edit a station (`e`)


> `x` for deleting playlist with confirmation

I haven't implemented this one intentionally; at the time I thought it would be an overkill; not hard to implement, I could do it at some point...

**Comment by amano-kenji** [comment]
Okay. It took some time to find `\n` from `Playlist Help` triggered by `?` key.

I also discovered that `\r` is for renaming a playlist.

Playlist deletion could be implemented later.

**Comment by s-n-g** [comment]
already in `devel`

**Comment by amano-kenji** [comment]
:+1:
