### ISSUE TITLE
Show stream `Title` metadata when `icy-title` metadata is missing.

### ISSUE THREAD

**Issue by amano-kenji** [coderholic/pyradio#217]
Many radio streams don't advertise `icy-title`. Instead, they advertise `Title` according to `mpv`.

pyradio doesn't show me `Title`.

An example radio stream that advertises `Title` instead of `icy-title` is https://radio.wownero.com/wow.ogg

**Comment by s-n-g** [comment]
Hi again!

I have had a quick look at it, and 

1. `mpv` seems to be able to report the title
2. `mplayer` kind of does it, but I need more data to be able to parse it. Can you provide a couple more similar stations?
3. `vlc` does not seem to report it back at all

**Comment by amano-kenji** [comment]
That's the only radio station I have for now.

**Comment by s-n-g** [comment]
I have tested a couple of the other stations from  https://radio.wownero.com and the only player that reports back the `Title` is mpv.

mplayer seems to be reporting only the first `Title`; I would need much more testing for this one to be sure on how to proceed, but since I don't have at least a couple of stations to test, I cannot go on.

vlc does not report back anything.

 So I have implemented this one for mpv only

**Comment by amano-kenji** [comment]
That's good enough for me.

**Comment by amano-kenji** [comment]
I found another unique station that replaces `icy-title` with other metadata tags.

* https://listen.moe/stream

**Comment by amano-kenji** [comment]
```
$ mpv https://listen.moe/fallback
 (+) Audio --aid=1 (mp3 2ch 44100Hz)
File tags:
 icy-title: toku - 「或るヒマワリ」feat. 石原夏織
AO: [pipewire] 44100Hz stereo 2ch floatp
```
```
$ mpv 'https://listen.moe/stream'
 (+) Audio --aid=1 '「或るヒマワリ」feat. 石原夏織' (vorbis 2ch 48000Hz)
File tags:
 Artist: toku
 Album: bouquet
 Date: 2021
 Title: 「或るヒマワリ」feat. 石原夏織
 Track: 2/10
AO: [pipewire] 48000Hz stereo 2ch floatp
```
```
$ mpv 'https://listen.moe/opus'
 (+) Audio --aid=1 '「或るヒマワリ」feat. 石原夏織' (opus 2ch 48000Hz)
File tags:
 Artist: toku
 Album: bouquet
 Date: 2021
 Title: 「或るヒマワリ」feat. 石原夏織
 Track: 2/10
AO: [pipewire] 48000Hz stereo 2ch floatp
```
It seems that mp3 streams advertise `icy-title` and ogg streams advertise artist, album, date, title, and track. ogg streams convey rich metadata.

**Comment by s-n-g** [comment]
Also in `devel`

**Comment by amano-kenji** [comment]
https://listen.moe/stream (ogg vorbis)
```
$ echo '{ "command" : ["get_property", "metadata"] }' | socat - /tmp/mpvsocket.7592
{"data":{"track":"1","genre":"Anime","comment":"#NIPPONSEI @ IRC.RIZON.NET","title":"Bravely You","artist":"Lia","year":"2015","date":"2015","album":"Bravely You / Yake Ochinai Tsubasa","ENCODER":"Liquidsoap/2.1.4 (Unix; OCaml 4.14.0)","icy-br":"256","icy-description":"Delivering the best Japanese and Anime music around the globe!","icy-genre":"Anime,Jpop,Japan,Asia,Asian","icy-name":"LISTEN.moe","icy-pub":"1","icy-url":"https://listen.moe"},"request_id":0,"error":"success"}
```
https://stream.moe/fallback (mp3)
```
$ echo '{ "command" : ["get_property", "metadata"] }' | socat - /tmp/mpvsocket.7592
{"data":{"icy-br":"256","icy-description":"Delivering the best Japanese and Anime music around the globe!","icy-genre":"Anime,Jpop,Japan,Asia,Asian","icy-name":"LISTEN.moe","icy-pub":"1","icy-url":"https://listen.moe","icy-title":"ClariS - reunion"},"request_id":0,"error":"success"}
```
mpv playing a local file
```
$ echo '{ "command" : ["get_property", "metadata"] }' | socat - /tmp/mpvsocket.test
{"data":{"TITLE":"River Of Crystals (feat. Kimiko Itoh)","ALBUM":"Ghost In The Shell 2: Innocence","DATE":"2004","track":"04","GENRE":"Anime","album_artist":"Kenji Kawai","ARTIST":"Kimiko Itoh"},"request_id":0,"error":"success"}
```

**Comment by amano-kenji** [comment]
It turns out that icecast is a poorly documented protocol.

It supports only title.

mp3 stream doesn't convey metadata, but ogg stream can convey its own metadata.

Since mp3 stream doesn't convey its own metadata, icecast has to convey title for mp3 streams.

For ogg streams, icecast doesn't have to convey song metadata.

**Comment by s-n-g** [comment]
Both the vorbis streams work great for me at this point

The `fallback` one does not even load, this is my log

```
2024-01-02 11:00:48,905 - pyradio.player:play():1924 - INFO: Executing command: mpv --no-video --quiet https://stream.moe/fallback --input-ipc-server=/tmp/mpvsocket.11794 --profile=pyradio
2024-01-02 11:00:48,905 - pyradio.player:updateMPVStatus():1227 - DEBUG: MPV updateStatus thread started.
2024-01-02 11:00:48,906 - pyradio.player:play():2027 - DEBUG: playback detection thread started
2024-01-02 11:00:48,906 - pyradio.player:play():2038 - INFO: ----==== mpv player started ====----

2024-01-02 11:00:48,982 - pyradio.player:updateMPVStatus():1267 - ERROR: DE Received: "b'{"request_id":0,"error":"success"}\n'"
2024-01-02 11:00:48,982 - pyradio.player:updateMPVStatus():1267 - ERROR: DE Received: "b'{"request_id":100,"error":"property unavailable"}\n'"
2024-01-02 11:00:48,985 - pyradio.player:updateMPVStatus():1267 - ERROR: DE Received: "b'{"request_id":200,"error":"property unavailable"}\n{"request_id":300,"error":"property unavailable"}\n{"request_id":400,"error":"property unavailable"}\n{"event":"property-change","id":1,"name":"metadata"}\n'"
2024-01-02 11:00:49,007 - pyradio.player:updateMPVStatus():1267 - ERROR: DE Received: "b'{"event":"start-file","playlist_entry_id":1}\n'"
2024-01-02 11:00:50,827 - pyradio.player:updateMPVStatus():1267 - ERROR: DE Received: "b'{"event":"end-file","reason":"error","playlist_entry_id":1,"file_error":"loading failed"}\n'"
2024-01-02 11:00:50,827 - pyradio.player:updateMPVStatus():1267 - ERROR: DE Received: "b''"
2024-01-02 11:00:50,827 - pyradio.player:updateMPVStatus():1337 - INFO: ----==== MPV disappeared! ====----
2024-01-02 11:00:50,827 - pyradio.radio:stopPlayerFromKeyboard():2319 - ERROR: stopPlayerFromKeyboard()!!!!!
2024-01-02 11:00:50,839 - pyradio.player:_kill_process_tree():2158 - DEBUG: PID 14936 (and its children)  killed...
2024-01-02 11:00:50,843 - pyradio.player:updateMPVStatus():1346 - INFO: MPV updateStatus thread stopped.
```

Local playback is not applicable with `pyradio`, so...

**Comment by amano-kenji** [comment]
I gave you a wrong URL for fallback.

It was https://listen.moe/fallback, but I gave you https://stream.moe/fallback

**Comment by s-n-g** [comment]
ok, this one works as well

**Comment by amano-kenji** [comment]
I installed the latest version. I can see artist and title. Is it a bad idea to show album and date as well?

**Comment by s-n-g** [comment]
No, it's not a bad idea, there's no such thing as TMI here :)

Does that look good to you?

![2024-01-06_11-40](https://github.com/coderholic/pyradio/assets/5807638/30522674-8a63-4572-837d-f39609ebec2d)

**Comment by s-n-g** [comment]
It gets truncated when there are a lot of characters, but I think it's ok...
Your thoughts?

![2024-01-06_12-05](https://github.com/coderholic/pyradio/assets/5807638/905cc468-cb40-4ab0-ba9e-d1cb83444d77)

**Comment by amano-kenji** [comment]
What is the format? Is it artist - title [album, date]?

**Comment by s-n-g** [comment]
Yes, exactly!
I think so too

**Comment by amano-kenji** [comment]
I think it's possible for either album or date to be null. Did you think about that?

**Comment by s-n-g** [comment]
What do you mean null?

Right now we can have either [album, date] or [album] if date does not exist

There is the possibility that `album: ""` or `date: ""` (the field is there, but the value is null). I suppose this is what you mean... I can check this one too, no problem

**Comment by amano-kenji** [comment]
listen.moe often gives me incomplete metadata. Often, it gives me no metadata.

When a new song gives me no metadata, pyradio just shows me the previous song from listen.moe.

**Comment by s-n-g** [comment]
> listen.moe often gives me incomplete metadata. Sometimes, date is `ate`. I think it's possible for either album or date to be absent, null, or empty, given listen.moe's incomplete metadata management.

If it gives `ate` or anything malformed, it won't be parsed

> Often, it gives me no metadata.

I think sometimes it provides metadata but no `title`, `artist`, etc

> When a new song gives me no metadata, pyradio just shows me the previous song from listen.moe.

Well, yes, there's no way for pyradio to know that the song has changed, unless it receives the metadata. If no metadata is received, pyradio will just display the last title that was ever received, there's no way to fix this, it's a station error

BTW, have you received the actual string `null` for any ot the parsed strings?
Have you seen pyradio display "`Atrist Name` - `Title Song` [`null`, 2020]" for example?

**Comment by amano-kenji** [comment]
> BTW, have you received the actual string null for any ot the parsed strings?

No. I haven't actually seen null. null is a concept in my mind. Sometimes, icy-title from listen.moe mp3 stream is empty.

**Comment by amano-kenji** [comment]
This is just an idea. What about clearing metadata if metadata hasn't been sent for a while?

I think song metadata are sent on regular intervals?

**Comment by s-n-g** [comment]
> I think song metadata are sent on regular intervals?

No, they are sent whenever a change has occurred, i.e. song changes = title change

> Or, if players clear metadata, pyradio can also clear metadata

This one may be logical: if title is empty, we may / could get back to the station's name
I do not know how easy it is right now with pyradio, though

**Comment by s-n-g** [comment]
For example, I just fired up **LISTEN.moe**

It started playing and the server sent a valid metadata update (song title displayed in pyradio) this is song No1

About 15 seconds later the song finished and a new one started (song No2). The server sent no metadata update (pyradio is still displaying wht it got from song No1). Actually nothing was sent by the server...

When song No2 finished, a new song started (song No3). The server sent a valid metadata update (song No3 title displayed in pyradio)

So you see, pyradio was displaying song No1 title while song No2 was playing. pyradio has no way of knowing that the song has changed, unless the server tells it so (pyradio does not monitor audio, for silence, for example; the player is a different program, as long as its pid exists, pyradio is happy)

Subsequent song changes seem to be ok (metadata update sent every time)

Receiving a malformed (i.e. empty title) metadata update is a different thing; it can be detected and acted upon...

**Comment by s-n-g** [comment]
BTW, you can monitor these by starting `pyradio -d`

An on a new terminal: `tail -f ~/pyradio.log`
