### ISSUE TITLE
Save only configuration options that differ from defaults.

### ISSUE THREAD

**Issue by amano-kenji** [coderholic/pyradio#220]
Because pyradio writes all options to configuration files, when option defaults change, users are stuck with previous default values.

To automatically migrate users to new option defaults, pyradio should save only configuration options that differ from defaults.

Since not all configuration options are going to be in configuration files, pyradio will have to document all configuration options with their default values somewhere else for people who want to configure options manually. For example, pyradio could show all configuration options with their default values in a text box when user presses a keyboard shortcut. Or, `pyradio --show-option-defaults` could print a full configuration file to standard output.

* I also think `SEARCH_TERM` in radio_browser_config should be put in a separate config file because it is not configured in radio browser configuration interface.
* `SEARCH_TERM` should be documented for people who want to edit configuration by hand? I think people will not want to edit this manually, though.

**Comment by s-n-g** [comment]
Yes, I see what you mean about the default options changes... but that rarely happens... I'll think about it though

The `SEARCH_TERM` part should probably be in a `json` file; these should not be changed manually

**Comment by amano-kenji** [comment]
This is also good for putting configuration files in git repository.

I want to track which configuration options differ from the defaults in my git repository of configuration files.

**Comment by amano-kenji** [comment]
I think `SEARCH_TERM` belongs in something like `$XDG_DATA_HOME/pyradio/radiobrowser_search_term`.

**Comment by s-n-g** [comment]
It will probably end up in a json file, something like `radiobrowser.json`...

Too many things to do, too little time to spare :)

**Comment by amano-kenji** [comment]
At least, I clearly defined what should be done.
