### ISSUE TITLE
Support pagination in radio browser.

### ISSUE THREAD

**Issue by amano-kenji** [coderholic/pyradio#221]
This is hopefully the last improvement suggestion. In the future, I will report rendering bugs.

Because pyradio radio browser doesn't support pagination, I can't browse all available search results.

For example, pyradio could fetch as many lines as those visible lines. When a user tries to go outside the visible page boundary, fetch a new page that is as tall as the visible lines.

Or, fetch as many lines as `DEFAULT_LIMIT` in radio_browser_config. When a user tries to go beyond the boundary of the fetched items, fetch `DEFAULT_LIMT` items, and replace the current items with the newly fetched items.

**Comment by s-n-g** [comment]
> Or, fetch as many lines as DEFAULT_LIMIT in radio_browser_config. When a user tries to go beyond the boundary of the fetched items, fetch DEFAULT_LIMT items, and replace the current items with the newly fetched items.

Interesting!
I think radiobrowser supports this one...

**Comment by s-n-g** [comment]
already in `devel`

**Comment by amano-kenji** [comment]
:1st_place_medal:
