### ISSUE TITLE
[FEAT] Save currently playing song title 

### ISSUE THREAD

**Issue by iodream** [coderholic/pyradio#226]
**Is your feature request related to a problem? Please describe.**

Often i have pyradio running in the background and want to save the currently playing song but it can take a long time to locate the pyradio window, manually copy the song name, open the file where i want to save it and paste it, especially if i'm doing work or in a game.

**Describe the solution you'd like**

Would it be possible to have a command line option, which when executed, contacts the pyradio daemon and appends the currently playing song title to a text file? Would be nice if they're grouped by station name or genre but i can understand if that's harder to implement. The text file path is either supplied as an argument or saved in the pyradio config to some default location. This way we could make a global keyboard shortcut in our desktop environments. Maybe have it also fire a notification that the write was successful, perhaps with the song title, so there are no doubts.  

**Describe alternatives you've considered**

Alternatively it would also be useful to have pyradio just save the song name the same way but only be triggered when done by a key press when the interface has focus. This would also be useful but not as much as the background solution in my opinion. 

**Additional context**

I've had my own bash script trying to mimic this functionality with mpris and dbus but if there is video/audio file opened after pyradio it will reset the song title globally and write the wrong name.

I also saw the --log-titles option but as far as i understand it logs everything, which can be confusing if you want just one song. 

Thank you for this program.

**Comment by s-n-g** [comment]
Hi @iodream 

The functionality you've requested is already there, it's called [Tagging a title](https://github.com/coderholic/pyradio/blob/master/docs/index.md#tagging-a-title).

1. When in **PyRadio** press "**w**"
2. If **PyRadio** is to be in the background, enable the [Remote Control Server](https://github.com/coderholic/pyradio/blob/master/docs/server.md) beforehand; then use `curl` to "*like*" a song, as I will explain below.


Once you have enabled the **Remote Control Server** (get into the config, pressing "**c**"), you can verify it using:

```
# pyradio --addr

PyRadio Remote Control Server
  Server
    Text address: http://127.0.0.1:9998
    HTML address: http://127.0.0.1:9998/html
```

Now, all you have to do is execute the following command to tag / like a song:

```
curl http://127.0.0.1:9998/like
```

This will create an entry in `~/.config/pyradio/pyradio-titles.log`

```
Feb 06 (Tue) 11:49 | === Logging started
Feb 06 (Tue) 11:49 | >>> Station: Lounge (Illinois Street Lounge - SomaFM)
Feb 06 (Tue) 11:49 |     David Carroll And His Orchestra - Would You Like To Take A Walk
Feb 06 (Tue) 11:49 |     David Carroll And His Orchestra - Would You Like To Take A Walk (LIKED)
Feb 06 (Tue) 11:49 | === Logging stopped
```

The only thing that's missing to 100% satisfy your request, is a desktop notification to inform you that the file is tagged; I suppose this would not be hard to implement

**Comment by iodream** [comment]
hm, no idea how i missed the tagging functionality. Thank you for the detailed guide!

Question: is the log file persistent and never cleared? or should i regularly backup songs out of it.

**Comment by s-n-g** [comment]
Please refer to [Title Logging](https://github.com/coderholic/pyradio/blob/master/docs/index.md#title-logging) to get the answer :wink: 

I haven't tested this behavior though...

**Comment by s-n-g** [comment]
Another thing more...

The location of the files are bound to be changed... I will keep this issue open until things change, and will inform you of the changes

**Comment by s-n-g** [comment]
In version 0.9.3, the **titles log** file(s) are moved in the recording directory.

This will be `~/pyradio-recordings`
