### ISSUE TITLE
[BUG] Crash when $HOME/.mplayer directory does not exist

### ISSUE THREAD

**Issue by rafacouto** [coderholic/pyradio#229]
**Describe the bug**

After setup, when executing pyradio:
```
Traceback (most recent call last): Opening connection...
  File "/home/caligari/.local/lib/python3.9/site-packages/pyradio/player.py", line 414, in _configHasProfile
    with open(self.config_files[0], 'a', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/caligari/.mplayer/config'
```
I solved this error with:
```
mkdir ~/.mplayer
```

**To Reproduce**
1. Install pyradio from tar.gz release from repository on Debian 11
2. Execute pyradio
3. See the error 'FileNotFoundError'

**Expected behavior**
It shoud be test if the directory exists or create it before trying to open the config file.

**System (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - **Python** version: 3.9.2
 - `pipx` version: 20.3.4
 - `pipx` installation method: System dependent
 - **PyRadio** Version: 0.9.2.25

**Comment by s-n-g** [comment]
fixed in `devel`

**Comment by rafacouto** [comment]
Good job! Thanks for pyradio :)
