### ISSUE TITLE
[BUG] self.xdg.xdg_compliant = False

### ISSUE THREAD

**Issue by amano-kenji** [coderholic/pyradio#232]
**Describe the bug**

pyradio prints
```
self.xdg.xdg_compliant = False
```
But, I have xdg_compliant = True in pyradio/config.

**System (please complete the following information):**
 - OS: Gentoo Linux
 - **Python** version: 3.11
 - **PyRadio** Version: 0.9.3

**Additional context**

By the way, I like all the new changes in 0.9.3. Now, it can compete with ncmpcpp.

**Comment by s-n-g** [comment]
This is just a debug message I forgot to remove...
It prints the value  of `xdg_compliant` **before** setting it to True.
Nevertheless, `xdg_compliant` is set to True, and XDG dirs are being used

> By the way, I like all the new changes in 0.9.3. Now, it can compete with ncmpcpp.

:+1:

**Comment by s-n-g** [comment]
fixed in **0.9.3.1**
