### ISSUE TITLE
[BUG] Move ~/.config/pyradio/.registers to ~/.local/state/pyradio/registers

### ISSUE THREAD

**Issue by amano-kenji** [coderholic/pyradio#233]
**Describe the bug**

Registers are not config. It is rightly application state.

**System (please complete the following information):**
 - OS: Gentoo Linux
 - **Python** version: 3.11
 - **PyRadio** Version: 0.9.3

**Comment by s-n-g** [comment]
You are so right... I forgot all about `.registers` :laughing: 

It will be done in 0.9.3.1

**Comment by s-n-g** [comment]
Done in 0.9.3.2

**Comment by amano-kenji** [comment]
I just tested it. It is good now.
