### ISSUE TITLE
[FEAT] Adding support for radio from youtube

### ISSUE THREAD

**Issue by FarParticul** [coderholic/pyradio#238]
**Is your feature request related to a problem? Please describe it.**
one problem that when adding a radio station from YouTube, a small window opens where the video is, which if you close, it is clear that the player will close.

**Describe the solution you would like to receive**.
Add youtube radio to the player without the window appearing

**Describe the alternatives you have considered**.
Don't know

**Additional Context**.
None

![изображение](https://github.com/coderholic/pyradio/assets/157636018/b762b57c-0f6b-4e5e-a681-4233a8416fe1)

I myself was surprised that the videos work in pyradio because it was clear when vlc enabled videos with url

**Comment by FarParticul** [comment]
I think the idea is a good one because there aren't some radio stations with the right subject matter, but there are some on youtube that I/other people want (hello NCS, lofi girl).

**Comment by s-n-g** [comment]
Hi again @FarParticul 

I really am not interested in supporting youtube, but if it works without too many changes, so be it...

Can you provide a couple of URLs you have tried and worked?

**Comment by s-n-g** [comment]
I have added `--no-video` command line parameter for **VLC**

You can test it by issuing the following commands:

```
cd 
rm install.py
curl -L \
    https://raw.githubusercontent.com/coderholic/pyradio/master/pyradio/install.py \
    -o install.py
python3 install.py --sng-devel
```

**Comment by FarParticul** [comment]
oh yeah, I forgot to post the links to the broadcasts,
(1) Lofi girl - https://www.youtube.com/watch?v=jfKfPfyJRdk
I don’t see any point in throwing others because it will be the same
(2) NCS - https://www.youtube.com/watch?v=oWW5TLrrbNo

**Comment by s-n-g** [comment]
> And also, I wanted to know if there is any way to change the color of the station names? It is necessary to create a space between stations. It turned out like this

Can you post the playlist?

**Comment by FarParticul** [comment]
[stations.csv](https://github.com/coderholic/pyradio/files/15049136/stations.csv)

**Comment by s-n-g** [comment]
Try this format

[FarParticul.csv](https://github.com/coderholic/pyradio/files/15049185/FarParticul.csv)


![image](https://github.com/coderholic/pyradio/assets/5807638/26d12328-ed9e-4fcf-a39f-8d205c3b8a85)

**Comment by s-n-g** [comment]
I think I can close this one now, right?

**Comment by FarParticul** [comment]
Okay. Thanks. There are no more questions for you!
