### ISSUE TITLE
Support for VLC installed as a Flatpak

### ISSUE THREAD

**Issue by Tractor777** [coderholic/pyradio#244]
Thanks for the project, I really like PyRadio. I initially had VLC installed as a Flatpak and PyRAdio did not find it and exited with an error. I changed to installing the deb version of VLC (I am using Ubuntu) and PyRadio is happy. I know that flatpak path can be given to run vlc or cvlc e.g. flatpak run --command=cvlc org.videolan.VLC ... and I was wondering if it would be possible to either configure PyRadio to be able to find this? do I need to change something in config or is this something that would need a code change?

**Comment by FarParticul** [comment]
> Thanks for the project, I really like PyRadio. I initially had VLC installed as a Flatpak and PyRAdio did not find it and exited with an error. I changed to installing the deb version of VLC (I am using Ubuntu) and PyRadio is happy. I know that flatpak path can be given to run vlc or cvlc e.g. flatpak run --command=cvlc org.videolan.VLC ... and I was wondering if it would be possible to either configure PyRadio to be able to find this? do I need to change something in config or is this something that would need a code change?

It seems that flatpak packages are in containers and it is possible to try to make pyradio define this directory where vlc itself is located. I understand pyradio looks initially at vlc, mpd, etc directories and then only uses them.

**Comment by s-n-g** [comment]
pyradio will check for the following executables in you PATH

- mpv
- mplayer
- cvlc

In your case, if the command `cvlc --help` is successful, the player is ready to be used by pyradio 

So, this is what you can do; no need to change anything in pyradio:

~~ Commands executed in a terminal, shell is bash ~~

```
[ -e ~/.local/bin ] && echo ok || echo "not ok"
```

If you get `not ok`  execute:

```
mkdir -p ~/.local/bin
```

Then
```
cat << END > ~/.local/bin/cvlc
#!/bin/bash
flatpak run --command=cvlc org.videolan.VLC "\$@"

END

chmod +x ~/.local/bin/cvlc
```

At his point you can use the **faltpack** version of `vlc` from your terminal:

```
~/.local/bin/cvlc --help
```

Final step: make sure `~/.local/bin` is the first directory in your **PATH**

```
echo $PATH
```

I get

```
/home/spiros/.local/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin

```

If the first directory is not `~/.local/bin` : 

```
echo 'export PATH=~/.local/bin:"$PATH"' >> ~/.bashrc
source ~/.bashrc
```

That is all

**Comment by s-n-g** [comment]
Please keep in mind that I do not have flatpack installed; it's up to you to provide the **flatpack command** to execute the cli version of vlc

**Comment by Tractor777** [comment]
Jackpot that sorted it out. I can now use the Flatpak version of VLC. Thanks

**Comment by Tractor777** [comment]
Thanks
