### ISSUE TITLE
Feature Suggestion - Ability to populate stations.csv directly from the Radio Browser UI

### ISSUE THREAD

**Issue by kmart9001** [coderholic/pyradio#245]
I'm trying to edit stations.csv into a custom station list of the music I enjoy listening to.  How I am doing this right now is running pyradio in one window, then opening an editor with stations.csv pulled up in another window.  In pyradio I invoke O to go to the radio browser and search for stations that interest me.  I then find a station and press I to get the URL for the station.  Then I must copy the URL and paste it into the csv in the other window.  Sometimes, though, the URL will bleed onto a second line in the info popup and then now i have to copy and paste a second bit to get the full url over in the csv.  Sometimes I accidentally hit control+c instead of control+shift c and have to reopen the radio browser UI.

**Describe the solution you'd like**
Within the Radio Browser UI include a hot key that will add the station directly to the stations.csv file.

**Comment by s-n-g** [comment]
You are really torturing yourself there :(

There are two quick ways to achieve what you want to do

1. with `v. 0.9.3.9`, Open **RadioBrowser** select a station and press "`*`" \
The station will be appended in the `favorites.csv` file \
Then when you are done, press "`\o`", select **Config Directory** to get to the file

2. use **registers**; imagine you are browsing the results for blues, select a station and press "`yb`", to save the station in `register_b.csv` in the STATE folder \
Then when you are done, press "`\o`", select **State Directory** to get to the file
If you want to append the stations collected, open a terminal, and 

1. open a terminal in the CONFIG folder and execute:
```
cat favorites.csv >> stations.csv
```

2. open a terminal in the STATE folder and execute:

```
cat register_b.csv >> ~/.config/stations.csv
```

If pyradio is already running, return to `stations`, and press "`R`" to reload the playlist.

The you can delete the original files (`favorites.csv` or `register_b.csv`
