### ISSUE TITLE
[FEAT] directory change configs

### ISSUE THREAD

**Issue by FarParticul** [coderholic/pyradio#246]
**Is your feature request related to a problem? Please describe.**
No, it has nothing to do with

**Describe the solution you'd like**
change directories in the pyradio config itself, or in the settings.

**Describe alternatives you've considered**
I don't know yet.

**Additional context**
No

**Comment by s-n-g** [comment]
Hello @FarParticul 

I am afraid I haven't understood what exactly the request is...

Which directories would you like to be able to change through the config?

**Comment by FarParticul** [comment]
Sorry for not answering for a long time, I had a friend and he was very interested in the program, he wanted the directory with configs and playlist was in a different place. Now he doesn't need it. I'll close the issue
