### ISSUE TITLE
Port Haiku os

### ISSUE THREAD

**Issue by FarParticlar** [coderholic/pyradio#248]
Good afternoon, this is FarParticul, I lost access to my account so I'm writing from this one. I started to get interested in haiku and wanted to run pyradio, I installed almost all python packages via pip but here's the problem, psutil is not available in haiku, in pip when installing it says that the system is not supported. There is a psutil port, but it must be a bit different. I would like you to help with pyradio working in haiku os, because only psutil doesn't work, and vlc, mpv are ported to haiku.

PS - You can port the program and I can package it and send pull request to haiku ports so that other people can use pyradio in haiku.

![image](https://github.com/coderholic/pyradio/assets/173531145/25a89a25-dd34-403f-b957-8e572dfaa05c)

**Comment by FarParticlar** [comment]
psutil https://github.com/haikuports/haikuports/tree/master/dev-python/psutil (while I'm digging for information on psutil)

**Comment by s-n-g** [comment]
Hi there @FarParticlar 

I know, I have a haiku VM and I've run into the same problem, but did not look into it...
Let me have a look at the link and we'll be in touch

**Comment by s-n-g** [comment]
![image](https://github.com/coderholic/pyradio/assets/5807638/31ed054a-63be-4e06-9ac7-fa369f67468a)


I cannot build it...

**Comment by FarParticlar** [comment]
> annot build it...



> ![image](https://private-user-images.githubusercontent.com/5807638/342090459-31ed054a-63be-4e06-9ac7-fa369f67468a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MjExODUsIm5iZiI6MTcxOTQyMDg4NSwicGF0aCI6Ii81ODA3NjM4LzM0MjA5MDQ1OS0zMWVkMDU0YS02M2JlLTRlMDYtOWFjNy1mYTM2OWY2NzQ2OGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjZUMTY1NDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWE4NDE5NGEzMTc5MjRmNjJiMWQ0ZTI3MDMxMTIwNDUzYThiZmQ0NDE1YmU2NTg5ZGM1NTljOGQwZDMwMGNlZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SX8LhNSfGCwG81VhUhAx8fkFMeNW76N9kuILw3SV6qY)
> 
> I cannot build it...

### **Hello s-n-g!**

**I also tried to build psutil but without success, I asked on the haiku forum about this problem, I just now remembered about it, sorry) I had some things to do, now I'll see if someone answered. 

I accidentally deleted the haiku from the pk , so I will put it up tomorrow and see. Maybe there's something I can do.**

**Comment by FarParticlar** [comment]
Now I looked on the forum what was written, I was thrown a link to an issue where there is the same error. I'll check it out now.

https://github.com/haikuports/haikuporter/issues/58

**Comment by FarParticlar** [comment]
I'm gonna close it because I don't have time for haiku os right now. As soon as I start doing it, I'll post here
