### ISSUE TITLE
[BUG] MPV Volume resets to 0% when trying to increase beyond maximum

### ISSUE THREAD

**Issue by wturrell** [coderholic/pyradio#251]
**Describe the bug**
If you increase a station beyond maximum volume it goes back to zero,.

**To Reproduce**
Press `.` repeatedly, station volume increases to 130%, then goes back to 0 on next press.

**Expected behavior**
Just stops at 130.

**System (please complete the following information):**
 - OS: macOS Sonoma 14.6.1
 - **Python** version:
 - `pipx` version: 1.2.0

PyRadio version: 0.9.2.25
Python version: 3.11.9 (main, Apr  2 2024, 08:25:04) [Clang 15.0.0 (clang-1500.3.9.4)]

 - Player used: mpv

**Comment by s-n-g** [comment]
I will look into it

**Comment by s-n-g** [comment]
fixed in `devel`
