### ISSUE TITLE
[BUG] Can't update stations.csv

### ISSUE THREAD

**Issue by pixelglade** [coderholic/pyradio#260]
**Describe the bug**
I cannot manually copy a new stations.csv file to the pyradio directory with stations.csv because it causes a write-error as stations.csv is read-only.

I also cannot update stations.csv with the command line because it causes errors.

**To Reproduce**
When typing:
`pyradio -s /home/USER/Documents/Linux/Custom-theme/stations.csv`
The following error appears:
```
Reading config...
Reading playlist...
Traceback (most recent call last):
  File "/snap/pyradio/672/bin/pyradio", line 33, in <module>
    sys.exit(load_entry_point('pyradio==0.8.9.2', 'console_scripts', 'pyradio')())
  File "/snap/pyradio/672/lib/python3.6/site-packages/pyradio/main.py", line 276, in shell
    ret = pyradio_config.read_playlist_file(stationFile=args.stations)
  File "/snap/pyradio/672/lib/python3.6/site-packages/pyradio/config.py", line 1904, in read_playlist_file
    return super(PyRadioConfig, self).read_playlist_file(stationFile=stationFile, is_register=is_register)
  File "/snap/pyradio/672/lib/python3.6/site-packages/pyradio/config.py", line 486, in read_playlist_file
    with eval(self._open_string[self._open_string_id]) as cfgfile:
  File "<string>", line 1, in <module>
PermissionError: [Errno 13] Permission denied: '/home/USER/Documents/Linux/Custom-theme/stations.csv'

```
Alternatively:
`sudo pyradio --stations "/home/USER/Documents/Linux/Custom-theme/stations.csv"`
Leads to:
```
Reading config...
Reading playlist...
Error: Specified playlist not found
```
Trying to copy the file directly:
`sudo cp /home/USER/Documents/Linux/Custom-theme/stations.csv /snap/pyradio/672/lib/python3.6/site-packages/pyradio/stations.csv`
Gives this error:
`cp: cannot create regular file '/snap/pyradio/672/lib/python3.6/site-packages/pyradio/stations.csv': Read-only file system`

Trying to use --update-stations while in the directory with the desired stations.csv:
`pyradio --update-stations stations.csv`
Error:
```
usage: pyradio [-h] [-s STATIONS] [-p [PLAY]] [-u USE_PLAYER] [-a] [-ls] [-l]
               [-t THEME] [-scd] [-ocd] [-ep EXTRA_PLAYER_PARAMETERS]
               [-ap ACTIVE_PLAYER_PARAM_ID] [-lp] [-U] [--user] [-R]
               [--unlock] [-d] [-V]
pyradio: error: unrecognized arguments: --update-stations stations.csv
```
Trying the short version:
`pyradio -us stations.csv`
Error:
```
usage: pyradio [-h] [-s STATIONS] [-p [PLAY]] [-u USE_PLAYER] [-a] [-ls] [-l]
               [-t THEME] [-scd] [-ocd] [-ep EXTRA_PLAYER_PARAMETERS]
               [-ap ACTIVE_PLAYER_PARAM_ID] [-lp] [-U] [--user] [-R]
               [--unlock] [-d] [-V]
pyradio: error: unrecognized arguments: stations.csv
```
Trying with the full path:
`pyradio -us "/home/USER/Documents/Linux/Custom-theme/stations.csv"`
Error:
```
usage: pyradio [-h] [-s STATIONS] [-p [PLAY]] [-u USE_PLAYER] [-a] [-ls] [-l]
               [-t THEME] [-scd] [-ocd] [-ep EXTRA_PLAYER_PARAMETERS]
               [-ap ACTIVE_PLAYER_PARAM_ID] [-lp] [-U] [--user] [-R]
               [--unlock] [-d] [-V]
pyradio: error: unrecognized arguments: /home/USER/Documents/Linux/Custom-theme/stations.csv
```

**Expected behavior**
I am expecting that the arguments should work as written in the documentation. However it does not work, yet PyRadio is installed and can be run from the command line. As a fall back I would like to be able to overwrite it with sudo and cp but that isn't happening either.
To make the CSV I copied the original CSV and then edited it in LibreOfficeCalc so I expect since it is in CSV format it should work.

**System (please complete the following information):**
 - OS: Ubuntu
`pyradio -V`
Gives:
```
PyRadio version: 0.8.9.2
Python version: 3.6.9 (default, Jan 26 2021, 15:33:00)  [GCC 8.4.0]
```
However...
`sudo pyradio -U`
Gives:
```
Released version   :  0.9.3.11.1
Installed version  :  0.8.9.2
Updating PyRadio...
Using directory: "/tmp/tmp-pyradio"
Downloading PyRadio source code...
Extracting RyRadio source code...
/bin/sh: 1: sudo: Permission denied


PyRadio updated to the latest release!
Thank you for your continuous support to this project!
Cheers!

```
Despite the "updated to the latest release" message, the sudo: Permission denied error basically indicates it didn't update and when I check the version on the command line the result is the same. 

`lsb_release -a`
Gives:
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.5 LTS
Release:	22.04
Codename:	jammy
```

**Additional context**
I tried updating with snap: `sudo apt update` and `sudo snap refresh` and `sudo snap refresh pyradio` but nothing really changes.

**Comment by s-n-g** [comment]
There are so many issues here, I do not know where to begin...

Let's start with the `stations.csv` you are trying to use.

Can you execute the following commands (as a normal user) in a terminal

```
cd
pwd
python --version
ls -la ~/.config/pyradio
```

and post anything that you get?

Then there this:

> Trying to copy the file directly:
> sudo cp /home/USER/Documents/Linux/Custom-theme/stations.csv /snap/pyradio/672/lib/python3.6/site-packages/pyradio/stations.csv
> Gives this error:
> cp: cannot create regular file '/snap/pyradio/672/lib/python3.6/site-packages/pyradio/stations.csv': Read-only file system

You have a snap pyradio installation (the `/snap/pyradio` part of the target directory), which uses python 3.6 (way too old).  Then, I do not know much about snaps, but I do not think you can just copy files within the snap installation directories. But let's just forget about his one for a while.

Just run the commands and post the result and we'll take it from there

**Comment by pixelglade** [comment]
When opening a new terminal window with the shortcut Ctrl+Alt+T, here are the results of those commands. Just btw I've replaced my user directory with "USER" in case that wasn't obvious.
cd works okay though not specifying a directory doesn't make it move anywhere.
`pwd`
returns: `/home/USER`

`mount`
returns:
```
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=8053976k,nr_inodes=2013494,mode=755,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1621880k,mode=755,inode64)
/dev/nvme1n1p5 on / type ext4 (rw,relatime,errors=remount-ro)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=17125)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
none on /run/credentials/systemd-sysusers.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
/var/lib/snapd/snaps/code_174.snap on /snap/code/174 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/bare_5.snap on /snap/bare/5 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core18_2846.snap on /snap/core18/2846 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core20_2434.snap on /snap/core20/2434 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core22_1663.snap on /snap/core22/1663 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/gnome-42-2204_176.snap on /snap/gnome-42-2204/176 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/gnome-mahjongg_174.snap on /snap/gnome-mahjongg/174 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/gtk-common-themes_1535.snap on /snap/gtk-common-themes/1535 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/kf6-core22_39.snap on /snap/kf6-core22/39 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/kiten_99.snap on /snap/kiten/99 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/opentoonz_147.snap on /snap/opentoonz/147 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/pyradio_672.snap on /snap/pyradio/672 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/snapd_21759.snap on /snap/snapd/21759 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/wine-platform-3-stable_14.snap on /snap/wine-platform-3-stable/14 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/wine-platform-runtime_390.snap on /snap/wine-platform-runtime/390 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/dev/nvme0n1p1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=1621876k,nr_inodes=405469,mode=700,uid=1000,gid=1000,inode64)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
portal on /run/user/1000/doc type fuse.portal (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
```
`python --version`
returns:
`Python 3.10.12`

`ls -la ~/.config/pyradio`
returns:
`ls: cannot access '/home/USER/.config/pyradio': No such file or directory`
What directory should I be in for calling the ~/.config?

**Comment by s-n-g** [comment]
Ok, let's fix the first problem; update `pyradio` to the latest version (and get rid of the snap installation)

I have installed ububtu 22.04 on a VM, so these commands are tested and verified :wink: 

Open a terminal and execute these commands:

```
snap remove pyradio
   
sudo apt-get install \ 
    python3 \ 
    python-is-python3 \
    pipx \
    python3-full \
    python3-pip \
    python3-rich \
    python3-requests \
    python3-netifaces \
    libpython3-all-dev \
    python3-dnspython \
    python3-psutil \
    python3-netifaces \
    python3-dateutil

pipx ensurepath
```

Close the terminal; this is important so that from this point on you work with the updated PATH.

Open a new terminal and execute these commands:


```
wget https://github.com/coderholic/pyradio/archive/refs/tags/0.9.3.11.1.tar.gz
tar xvzf 0.9.3.11.1.tar.gz && rm 0.9.3.11.1.tar.gz
cd pyradio-0.9.3.11.1
./devel/build_install_pyradio
cd ..
rm -rf pyradio-0.9.3.11.1
```

Finally install mpv

```
sudo apt install mpv
```

Now you have the latest pyradio, execute it

```
pyradio
```

**Comment by pixelglade** [comment]
Following your instructions I was able to reinstall pyradio. 
After this, loading the station playlist temporarily works:
`pyradio -s "/home/USER/Documents/Linux/Custom-theme/stations.csv"`
This loads the specified playlist into pyradio and I can play the stations.

However
`pyradio -us "/home/USER/Documents/Linux/Custom-theme/stations.csv"`
Returns:
```
Usage: pyradio \[-h] \[-c CONFIG_DIR] \[-p \[STATION_NUMBER]] \[-u PLAYER] \[-l]
               \[-lt] \[-sds] \[-sd] \[-od] \[-pc] \[-d] \[-ul] \[-us] \[-U] 
\[-R] \[-V]
               \[-ls] \[-s PLAYLIST] \[-tlp] \[-t THEME] \[--show-themes]
               \[--no-themes] \[--write-theme IN_THEME OUT_THEME,]
               \[--terminal TERMINAL] \[--terminal-param TERMINAL_PARAM] \[-oc]
               \[-sc] \[-cc] \[-gc] \[-r] \[-or] \[-lr] \[-mkv MKV_FILE]
               \[-scv PNG_FILE] \[-srt] \[-ach] \[--headless IP_AND_PORT]
               \[--address] \[-fd]

pyradio: error: unrecognized arguments: /home/USER/Documents/Linux/Custom-theme/stations.csv
```
It does the same with the --update-stations argument. So once closing pyradio I would need to reload the custom playlist every time I want to use it rather than loading it as the default.
To do the same as I did previously...
`pwd`
`/home/USER`

While:
`mount`
returns:
```
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=8053976k,nr_inodes=2013494,mode=755,inode64)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1621880k,mode=755,inode64)
/dev/nvme1n1p5 on / type ext4 (rw,relatime,errors=remount-ro)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev,inode64)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k,inode64)
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate,memory_recursiveprot)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
bpf on /sys/fs/bpf type bpf (rw,nosuid,nodev,noexec,relatime,mode=700)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=29,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=27680)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,nosuid,nodev,noexec,relatime)
tracefs on /sys/kernel/tracing type tracefs (rw,nosuid,nodev,noexec,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,nosuid,nodev,noexec,relatime)
configfs on /sys/kernel/config type configfs (rw,nosuid,nodev,noexec,relatime)
none on /run/credentials/systemd-sysusers.service type ramfs (ro,nosuid,nodev,noexec,relatime,mode=700)
/var/lib/snapd/snaps/bare_5.snap on /snap/bare/5 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/code_174.snap on /snap/code/174 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core18_2846.snap on /snap/core18/2846 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core20_2434.snap on /snap/core20/2434 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/core22_1663.snap on /snap/core22/1663 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/gnome-42-2204_176.snap on /snap/gnome-42-2204/176 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/gnome-mahjongg_174.snap on /snap/gnome-mahjongg/174 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/gtk-common-themes_1535.snap on /snap/gtk-common-themes/1535 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/kf6-core22_39.snap on /snap/kf6-core22/39 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/kiten_99.snap on /snap/kiten/99 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/opentoonz_147.snap on /snap/opentoonz/147 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/snapd_21759.snap on /snap/snapd/21759 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/wine-platform-3-stable_14.snap on /snap/wine-platform-3-stable/14 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/var/lib/snapd/snaps/wine-platform-runtime_390.snap on /snap/wine-platform-runtime/390 type squashfs (ro,nodev,relatime,errors=continue,x-gdu.hide)
/dev/nvme0n1p1 on /boot/efi type vfat (rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=iso8859-1,shortname=mixed,errors=remount-ro)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=1621876k,nr_inodes=405469,mode=700,uid=1000,gid=1000,inode64)
gvfsd-fuse on /run/user/1000/gvfs type fuse.gvfsd-fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
portal on /run/user/1000/doc type fuse.portal (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
tmpfs on /run/snapd/ns type tmpfs (rw,nosuid,nodev,noexec,relatime,size=1621880k,mode=755,inode64)
```
`python --version`
`Python 3.10.12`

`ls -la ~/.config/pyradio`
```
total 28
drwxrwxr-x  5 USER USER 4096 Nov  8 16:21 .
drwxr-xr-x 50 USER USER 4096 Nov  8 16:19 ..
-rw-rw-r--  1 USER USER 2220 Nov  8 16:21 2024-11-08_16-21-32_stations.csv
drwxrwxr-x  2 USER USER 4096 Nov  8 16:18 data
drwxrwxr-x  2 USER USER 4096 Nov  8 16:18 .registers
-rw-rw-r--  1 USER USER 3329 Nov  8 16:18 stations.csv
drwxrwxr-x  2 USER USER 4096 Nov  8 16:18 themes
```

**Comment by s-n-g** [comment]
ok, this is great!

We did all that for two reasons: a) you are now using the latest version, and will be getting updates, and b) you now have a **writable directory** where you can save your `stations.csv`

So

```
cp /home/USER/Documents/Linux/Custom-theme/stations.csv ~/.config/pyradio
```

will fix your problem.

Now every time you open pyradio you will see your list of stations, not the default one.

The purpose of
```
pyradio -us
```

(no arguments) is not going to do what you are trying to do.

That is my bad, the documentation may not be clear about this one, but the purpose is to sync changes made to the upstream `stations.csv` into the local `stations.csv`.

Finally, since we have installed pyradio from code (no debian / ubuntu pyradio package exists), both the configuration and the installation files are under your home directory.

This means that you do not use `sudo` with pyradio.

If you ever miss an update, just execute `pyradio -U` and this will do the trick.

I hope that fixes everything for you so we can close this issue.

**Comment by pixelglade** [comment]
`cp /home/USER/Documents/Linux/Custom-theme/stations.csv ~/.config/pyradio`
This command worked now so I have my custom playlist now. (Horray!)

> That is my bad, the documentation may not be clear about this one, but the purpose is to sync changes made to the upstream stations.csv into the local stations.csv.
I wish I could say I understand what you mean but I don't. If you could give examples in the documentation for what the upstream stations.csv is and what the downstream one is and how to use the argument it would make more sense. Does it mean that if I had used "-s stations.csv" to temporarily load a playlist into PyRadio like I did before that by then using -us it will overwrite the default stations.csv with the new one currently loaded instead?

Anyway I am very appreciative of your help, I really love this program the interface is very elegant and simple and that's all a radio player should be (I think) so you can go ahead and close this issue.

**Comment by s-n-g** [comment]
> I wish I could say I understand what you mean but I don't. If you could give examples in the documentation for what the upstream stations.csv is and what the downstream one is and how to use the argument it would make more sense. Does it mean that if I had used "-s stations.csv" to temporarily load a playlist into PyRadio like I did before that by then using -us it will overwrite the default stations.csv with the new one currently loaded instead?

So, when using `pyradio -s /home/USER/Documents/Linux/Custom-theme/stations.csv` the command line parameter is `-s` and its argument is `/home/USER/Documents/Linux/Custom-theme/stations.csv` (the parameter to the command line parameter, sort of).

Now, `-us` does not need an argument (in fact it will not work if one is provided). You just type `pyradio -us` and it does its thing.

As to what all this upstream / downstream mean. Upstream in this case means the `stations.csv` that comes with pyradio; downstream is the `stations.csv` you have in `~/.config/pyradio`. When I update the upstream file and upload a new release, there is no way to get the changes done to that file into your `stations.csv` (in `~/.config/pyradio`).

This is what `-us` does; it will add / remove / update the stations found in `~/.config/pyradio/stations.csv` based on the changes done in the package's `station.csv`.

In your case, since you have overwritten the file placing your own stations there, it would be better not to use `-us` (and refuse to use it if prompted by pyradio).

Hope that clears this up.

Anyhow, I'm glad everything worked; closing this one!
