### ISSUE TITLE
PyRadio snap does not find vlc

### ISSUE THREAD

**Issue by papioara** [coderholic/pyradio#263]
When I do "snap run pyradio -u vlc", pyradio complains that it cannot find it on my system although it is installed. Can I do something about this?

Thank you for troubleshooting me

**Comment by s-n-g** [comment]
Is `vlc` installed as a **snap** as well?
I suspect it is, but just to be certain...

**Comment by papioara** [comment]
No, it is in /usr/bin and does not exist in other form on my system.

**Comment by s-n-g** [comment]
Can you post your `PATH`?

Execute

```
echo "$PATH"
```
and post the result

Also, what does `cvlc --version` return?

**Comment by papioara** [comment]
Here you go:

` cvlc --version
VLC media player 3.0.16 Vetinari (revision 3.0.13-8-g41878ff4f2)
VLC-Version 3.0.16 Vetinari (3.0.13-8-g41878ff4f2)
Kompiliert von buildd auf lcy02-amd64-108.buildd (Mar 13 2022 08:00:10)
Kompiler: gcc version 11.2.0 (Ubuntu 11.2.0-18ubuntu1)
`

and:

`echo $PATH
/home/falter/Desktop/:/media/falter/Musikbibliothek2/Music:/media/falter/ReserveIntern250/Musik2:/home/falter/.cargo/bin:/media/falter/Musikbibliothek2/Music:/media/falter/ReserveIntern250/Musik2:/home/falter/adb-fastboot/platform-tools:/home/falter/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:./:/usr/lib/surfraw:/usr/lib/surfraw:/home/falter/.local/bin:/home/falter/.cargo/bin/navi:/home/falter/.cargo/bin/`

**Comment by s-n-g** [comment]
Ok, so...

Vlc is in your **PATH**, and you can execute it from the terminal.

This tells me that **snap** does not load/use the PATH environment variable.

Please keep in mind i do not use **snap** and i know nothing about it, so i am afraid i cannot help you with this one...

Having said that, a google search returned this

https://forum.snapcraft.io/t/how-to-make-snap-use-system-environment-variables/26045

So, this is a **snap*" problem...

The only solution i can think of is : uninstall the snap release and install **pyradio** [from source](build it from source)

What distro are you using?

**Comment by papioara** [comment]
I was afraid it was a snap problem. From your words I conclude that you have nothing to do with the PyRadio snap, but that it has been built by someone else.
I have followed your advice and I have purged my system carefully of all the snap leftovers after removing the snap. Then I have followed your great installation instructions ( I have Linux Mint 21.3 Virginia Cinnamon here, btw). The script has worked perfectly, and afterwards, on running PyRadio, I could see that in the snap there is an outdated version of pyradio, which also may explain certain other flaws like hard to explain mpv crashes when I tried to play certain radio stations, even from the default list.

It was also interesting to see that PyRadio seems to have evolved a lot after that version in the snap (0.8 something, if I remember correctly).

The newly installed version is more elaborate, the user experience is smooth and even if you do not know your way around, there are helpful and easily understandable instructions - in other words: a really nice app which is fun to run.

Big Thank You and compliments for your work.

**Comment by s-n-g** [comment]
> I was afraid it was a snap problem. From your words I conclude that you have nothing to do with the PyRadio snap, but that it has been built by someone else.
:+1: 

I have followed your advice and I have purged my system carefully of all the snap leftovers after removing the snap. Then I have followed your great installation instructions ( I have Linux Mint 21.3 Virginia Cinnamon here, btw). The script has worked perfectly, and afterwards, on running PyRadio, I could see that in the snap there is an outdated version of pyradio, which also may explain certain other flaws like hard to explain mpv crashes when I tried to play certain radio stations, even from the default list.
:+1: 

> It was also interesting to see that PyRadio seems to have evolved a lot after that version in the snap (0.8 something, if I remember correctly).

Yes, the **snap** release is way outdated; unfortunately people keep using it without knowing this, I guess because it's easier to install?

> The newly installed version is more elaborate, the user experience is smooth and even if you do not know your way around, there are helpful and easily understandable instructions - in other words: a really nice app which is fun to run.
>
> Big Thank You and compliments for your work.

Thank you very mush for your king words!
I am glad to hear you like the experience!
I always thought a terminal app should be easy to use :wink: 

Closing this one!

**Comment by s-n-g** [comment]
Closing this one!
