### ISSUE TITLE
Some radio stations on the default list do not work

### ISSUE THREAD

**Issue by papioara** [coderholic/pyradio#264]
This is not exactly an issue with the program, just some feedback and maybe a reason to review that list:
On my machine in my (German) environment it's the following items: Nos. 5, 16,18, 19, 33, and 34. When I try to play them, I always get: mpv terminated abnormally.
Or does this have to do with the fact that some stations are not broadcasting 24 hours a day? And the error message is only a consequence of the station not being available at that moment?

**Comment by s-n-g** [comment]
https://github.com/user-attachments/assets/08c5d237-3758-4534-92b9-6f13e8b3bd2a



All stations play ok for me, except No 16 at "Wed Dec 11 **12:44:39** PM **UTC** 2024" from **Greece**, so I don't know, maybe some stations are not broadcasting 24 hours a day, or some are only available to users from specific countries or regions?

**Comment by papioara** [comment]
Thank you for checking as well - it's not the end of the world anyway, because
you can always throw out the ones which do not work for you and add others (which probably almost
everyone will do anyway).
Where do you get your stream urls from?

Am Wed, Dec 11, 2024 at 04:50:16AM -0800 schrieb Spiros Georgaras:

**Comment by s-n-g** [comment]
> Thank you for checking as well - it's not the end of the world anyway, because
you can always throw out the ones which do not work for you and add others (which probably almost
everyone will do anyway).

I suppose that's true :smiley: 

> Where do you get your stream urls from?

I really do not remember....
Most of these stations were there when I started working on the project (this is true for all somafm station); some were added after a user request, so...

**Comment by s-n-g** [comment]
So, I guess I will close this one ...
