### ISSUE TITLE
[BUG] DMT FM Psytrance playlist unsupported

### ISSUE THREAD

**Issue by taoteh1221** [coderholic/pyradio#265]
**Describe the bug**
This internet radio URL works in chrome web browser, but not in PyRadio:
DMT FM Psytrance
https://dc1.serverse.com/proxy/ywycfrxn/live

**To Reproduce**
1. Add to stations list
2. Run station from list in the UI
3. See error message at bottom of UI: 'Failed to connect'

**Expected behavior**
Plays the stream

**System (please complete the following information):**
 - OS: Raspbian GNU/Linux 11 (bullseye)
 - **Python** version: 3.9.2
 - `pipx` version (if applicable): NONE
 - `pipx` installation method: NONE
 - **PyRadio** Version: 0.9.3.11.1
 - Player config used: mplayer,vlc,mpv

**Additional context**
NONE

**Comment by s-n-g** [comment]
`mplyer` will play it if you force to use "http" instead of "https"
You can change it at the config window (if that works), or press "**z**", change to `True` and press "**s**"

**Comment by taoteh1221** [comment]
Yeah, I kinda figured it was an mplayer incompatibility. I finally got pyradio to use vlc and persist changes to the config, and all playlists work now: https://github.com/coderholic/pyradio/issues/266#issuecomment-2558525436

So I will close this issue. Thanks for the quick response. :)
