### ISSUE TITLE
[BUG]  Config files does not save update to preferred player (config is overwritten with default config on pyradio restart)

### ISSUE THREAD

**Issue by taoteh1221** [coderholic/pyradio#266]
**Describe the bug**
Changing the default player config to only use vlc does not save (it's OVERWRITTEN on pyradio restart)

**To Reproduce**
1. type C to get setting UI
2. Change player config to only use vlc
3. type S, 2 or 3 times, to exit settings and save the config change
4. Restart pyradio, type C to review settings

**Expected behavior**
Config should only have vlc as the player

**System (please complete the following information):**
 - OS: Raspbian GNU/Linux 11 (bullseye)
 - **Python** version: 3.9.2
 - `pipx` version (if applicable): NONE
 - `pipx` installation method: NONE
 - **PyRadio** Version: 0.9.3.11.1
 - Player config used: mplayer,vlc,mpv

**Additional context**
I also edited /home/taoteh1221/.config/pyradio/config MANUALLY to only use vlc, but it is also OVERWRITTEN with the old default config, on pyradio restart. ADDITIONALLY, I confirmed vlc is already installed on my system.

**Comment by s-n-g** [comment]
Hi @taoteh1221 


I cannot reproduce unfortunatelly (I have installed 0.9.3.11.1 to test)
I am on a linux box thought and do not have a Pi to test

![image](https://github.com/user-attachments/assets/8859fc68-912c-4f09-a56b-60537af61471)

I imagine you do get this screen when saving your new config

Does "**\m**" works? can you change the session's player?

**Comment by taoteh1221** [comment]
I just realized that everything actually works OK if I call pyradio directly from CLI, BUT calling it in my app https://github.com/taoteh1221/Bluetooth_Internet_Radio , for some reason it keeps overwriting the config calling it that way? Is there an additional parameter I should add in my script, to allow updating of pyradio's config?

**Comment by s-n-g** [comment]
probably it's this one... :wink: 
```
                sed -i 's/player = .*/player = mplayer, vlc, mpv/g' ~/.config/pyradio/config > /dev/null 2>&1
```
line 1786

**Comment by taoteh1221** [comment]
Yeah, I just realized that running pyradio from my bash script ALWAYS resets my pyradio config, even after successfully changing it to only use vlc directly from CLI (no bash script). Ooops, thanks, I was just starting to review the code now too. Looks like a bug fix release is due. :)

**Comment by taoteh1221** [comment]
Closing the issue, thanks for the help! :)
