### ISSUE TITLE
Add search and jump feature?

### ISSUE THREAD

**Issue by gotbletu** [coderholic/pyradio#29]
Say if you had a super long list of stations.

search = /
jump = #[enter]

**Comment by coderholic** [comment]
Page up/down lets you jump a screen already.

**Comment by gotbletu** [comment]
yea im aware of those hotkeys, just seems less efficient to scroll thur 100s of stations if you know the station number already

**Comment by s-n-g** [comment]
I have just added a search function.
Can you please have a look?

**Comment by s-n-g** [comment]
The search function is now complete since https://github.com/coderholic/pyradio/commit/a8cac9719a12b315f6381b88c255ce9e256b52c7 so I'm considering this one closed
