### ISSUE TITLE
UnboundLocalError with Python 3 on Archlinux x64

### ISSUE THREAD

**Issue by gojun077** [coderholic/pyradio#31]
Traceback (most recent call last):
      File "/usr/bin/pyradio", line 9, in <module>
        load_entry_point('pyradio==0.5.2', 'console_scripts', 'pyradio')()
      File "/usr/lib/python3.4/site-packages/pyradio/main.py", line 78, in shell
        pyradio = PyRadio(stations, play=args.play)
    UnboundLocalError: local variable 'stations' referenced before assignment

I am running Linux kernel 4.1.6-1-ARCH on an Intel Atom netbook

I tried copying the default `stations.csv` to `~/.pyradio/stations.csv` but that doesn't remove the error.

**Comment by willemw12** [comment]
It seems like an else-statement is missing:

    diff --git a/pyradio/main.py b/pyradio/main.py                                                                                                     
    index ae4bb8d..05b8444 100644
    --- a/pyradio/main.py
    +++ b/pyradio/main.py
    @@ -59,6 +59,7 @@ def shell():
                 writter.writerow(params)
                 sys.exit()
     
    +    else:
             with open(args.stations, 'r') as cfgfile:
                 stations = []
                 for row in csv.reader(filter(lambda row: row[0]!='#', cfgfile), skipinitialspace=True):

**Comment by martynjy** [comment]
Same problem on Arch using Python 3.5.  But it did work on Python 3.4!
python (3.4.3-3 -> 3.5.0-2)

**Comment by p1tt1** [comment]
+1

**Comment by coderholic** [comment]
Can those with this problem confirm if @willemw12 's suggested else patch fixes it?

**Comment by martynjy** [comment]
Now I am suddenly getting:

Traceback (most recent call last):
  File "/usr/bin/pyradio", line 9, in <module>
    load_entry_point('pyradio==0.5.2', 'console_scripts', 'pyradio')()
  File "/usr/lib/python3.5/site-packages/pyradio/main.py", line 45, in shell
    name, url = [s.strip() for s in row]
ValueError: too many values to unpack (expected 2)

**Comment by mschaeuble** [comment]
Works perfectly well again for me on Archlinux after applying @willemw12 's suggested fix.

**Comment by coderholic** [comment]
Committed a fix
