### ISSUE TITLE
stations.csv location

### ISSUE THREAD

**Issue by nyboer** [coderholic/pyradio#38]
Not really an issue, but it's worth noting that, on a Debian install (specifically, an NTC C.H.I.P.), once pyradio is installed, you can edit the stations with 

```
sudo nano /usr/local/lib/python2.7/dist-packages/pyradio-0.5.2-py2.7.egg/pyradio/stations.csv 
```

Mostly I'm putting this here so a less-experienced user can find the station.csv file to edit! A lot of the stations seem to have dropped support for non-app use, so I wanted to delete them from the list.
I like the script - thanks for sharing it!

**Comment by anastiel** [comment]
thanks so much

**Comment by cdw** [comment]
Adding the following to the README would be quite helpful.
## Stations file

The stations are stored in a CSV where each line contains two columns, the first being the station name and the second being the stream URL. 
---
PyRadio looks for the station settings CSV in the following places in the following order:
- ~\.pyradiostations.csv
- ~\.pyradio
- $INSTALLATIONPATH\stations.csv

Where $INSTALLATIONPATH is the folder that PyRadio is installed into and contains the default list of stations distributed with PyRadio.

**Comment by s-n-g** [comment]
I'm closing this one; it's way too old

If you want to see where the stations file is, you just:

```
pyradio -scd
```
You will get something like:
```
PyRadio config dir: "/home/user/.config/pyradio"
```
Even easier, just open the config dir:
```
pyradio -ocd
```
