### ISSUE TITLE
Volume defaults to max on every station change

### ISSUE THREAD

**Issue by j10sanders** [coderholic/pyradio#41]
It would be great if the volume of this player persisted throughout changing stations.  The Pocket CHIP's max volume is too loud to listen to on standard earbuds... so it's annoying to have to remove them before changing the station.  I'm going to see if I can figure out how the volume is handled, although if you can point me in the right direction, Ben, that would be much appreciated :).  I'll make a pull request as soon as I can.

**Comment by coderholic** [comment]
We restart a new instance of mplayer when you change the station, so I think the volume gets reset as a side effect of that. Not sure if there are any mplayer flags to get it to store the default.

**Comment by j10sanders** [comment]
A default volume can be set in the mplayer config file (~/.mplayer):

volume=<0..100>
    (default 100)
[http://manpages.ubuntu.com/manpages/trusty/man1/mplayer.1.html](url)

I recommend Pocket CHIP users set their volume to something like:
volume=30

I'm not sure how to make this edit possible through pyradio.  I may work into it at some point, since it would be nice!

**Comment by s-n-g** [comment]
Saving the volume has been implemented (well, for mpv and mplayer only), so this issue should be closed now...

**Comment by nesingho** [comment]
Hi,

> Saving the volume has been implemented (well, for mpv and mplayer only), so this issue should be closed now...
> 
> After saving the volume, whenever the player will be restarted, it will used the saved value, so...

Doesn't work here. pyradio says "Volume saved" but volume is at 100% again at station change.
Version is pyradio 0.7.5 on Manjaro.

**Comment by s-n-g** [comment]
Can you please upgrade to 0.7.6.2, check and report back?

**Comment by nesingho** [comment]
0.7.6.2 works perfect in this way! Thanks. :)

**Comment by s-n-g** [comment]
Thank you for reporting.
I'm glad it works, you got me worried there for a moment... :)
Cheers!
