### ISSUE TITLE
Can't run pyradio on debian

### ISSUE THREAD

**Issue by brainvision** [coderholic/pyradio#44]
Hi there! I find your project from a command line useful app reviews and I decided I want it! :D
So I cloned the project into my PC, run pip install pyradio and the output was right, but I'm not able to run pyradio: command not found :(
I'm on debian stretch, Python 2.7, pip 8.1.2.
The output of pip install pyradio was:

```
pip install pyradio
Collecting pyradio
Downloading pyradio-0.5.2.tar.gz
Building wheels for collected packages: pyradio
Running setup.py bdist_wheel for pyradio ... done
Stored in directory: /home/brainvision/.cache/pip/wheels/05/42/2f/d6508b80798e7ed1acac13462d933f6d3ba69a5f58a551bad0
Successfully built pyradio
Installing collected packages: pyradio
Successfully installed pyradio
```

Do you have any clue about that, please?
Thanks a lot, see you! ;)

**#EDIT:** well, maybe I had to install via pip by root because I found that it installed pyradio in /home/account/.local/etc... But now that I found I'm able to manage it.

I also noticed that the 70% of the radio are not working; don't know if it depends from the fact that I'm in Italy, but all SKY and Digitally Imported radios only transmit a loop message about how to listen the radio via web or mobile apps.. :(

BTW I think this issue could be closed, just if someone could tell me if I can delete the .local pyradio folders and install it using root or if I have to uninstall via pip (which i never did before)
Thanks, see you!

**Comment by s-n-g** [comment]
I have been testing pyradio on debian 9.x for a long time, it works great.

Yes, you should uninstall via pip (pip has a very old version) and just 'git clone' and follow installation instructions.

Most of the stations are always available; some of them broadcast at certain times, but overall no problem here too.

Considering it closed
