### ISSUE TITLE
pyradio just stopped working on Ubuntu 16.04

### ISSUE THREAD

**Issue by tinfoilhatter** [coderholic/pyradio#45]
pyradio was working fine for me, and I really enjoyed it. Then suddenly, as of today, I can see and select stations, and pyradio will display a lot of diagnostic text including "Starting playback..." but **no sound is played**.

To try to fix this, I have upgraded pip and uninstalled and reinstalled pyradio. I have mplayer and vlc/cvlc both installed. I use cvlc separately every day. I just tested mplayer and cvlc on a number of stations in my .csv. When called from the command line, mplayer couldn't play any of them, and cvlc could play only one. (Then why did they work for all of my stations when called from pyradio previously?)

Thanks for your time.

**Comment by 2E0PGS** [comment]
Works fine for me on 16.04 and 17.10. Try comment out one of the player sub classes in the players.py file to see which player is the problem

**Comment by omnesia0rg** [comment]
Thanks for the tip @2E0PGS. Commenting out MpPlayer did the trick for me

**Comment by s-n-g** [comment]
Modifying the code is not needed anymore...
If you have a problem with the auto detected player, try to specify one. 
Also, try to reinstall pyradio (from git) in case of a python update.

Considering it closed.
