### ISSUE TITLE
icy-title overrides volume too quickly when I change volume consecutively.

### ISSUE THREAD

**Issue by crocket** [coderholic/pyradio#65]
An existing thread for re-displaying icy title must be delayed or killed if volume changes again before the thread executes.

**Comment by s-n-g** [comment]
Sure, this is the way it should be.
But for the time being, I'm tweaking current behavior...

**Comment by s-n-g** [comment]
ok, i think this is it...

**Comment by crocket** [comment]
A simpler trick would be to make a dedicated space for volume. For example, `cmus` makes room for volume.

**Comment by s-n-g** [comment]
Yes, I just found out too...
It seems that on my home pc I was running the program from some kind of cache, or something
Now, on my laptop, everything is just screwed up.
I will revert and start over...

**Comment by s-n-g** [comment]
Issue fixed with https://github.com/coderholic/pyradio/pull/71
