### ISSUE TITLE
Connecting to 'Hip Hop (Hot 97 NYC)' and then another station breaks rendering.

### ISSUE THREAD

**Issue by crocket** [coderholic/pyradio#74]
![2018-11-17_sat_00 18 57](https://user-images.githubusercontent.com/748856/48653612-d44b0a80-ea49-11e8-88b5-2c2dd10f32e6.png)

**Comment by s-n-g** [comment]
Well, ok, we already are in an abnormal situation...
Please refer to #75

**Comment by crocket** [comment]
You may not be able to fix #75, but you can fix this issue.

**Comment by s-n-g** [comment]
Sure, I could try, if you told me how to reproduce it

**Comment by crocket** [comment]
1. Connect to `Hip Hop (Hot 97 NYC)`
2. Wait until the connection fails
3. Connect to another radio station
4. See that the rendering broke.

**Comment by s-n-g** [comment]
Sorry, I cannot reproduce it
I just did exactly as you told me, but everything is ok

Can you please update to latest ``coderholic/pyragio.git`` and send me your **pyradio.log** when it breaks?

**Comment by crocket** [comment]
![2018-11-18_sun_02 00 02](https://user-images.githubusercontent.com/748856/48667770-2743c100-eb21-11e8-9d04-c272e47641fd.png)

[pyradio.log](https://github.com/coderholic/pyradio/files/2592456/pyradio.log)

**Comment by s-n-g** [comment]
ok, can you check ``s-n-g/pyradio`` please?

**Comment by crocket** [comment]
I'm not sure if that's the best way to handle the issue, but it fixes the issue.

**Comment by s-n-g** [comment]
Yes, this is exactly what I intend to do

**Comment by s-n-g** [comment]
When connecting to 'Hip Hop (Hot 97 NYC)' fails, the player is stopped, no layout breakage anymore.

Considering it closed
