### ISSUE TITLE
metadata-update event breaks rendering.

### ISSUE THREAD

**Issue by crocket** [coderholic/pyradio#76]
[pyradio.log](https://github.com/coderholic/pyradio/files/2592747/pyradio.log)

![2018-11-18_sun_12 32 01](https://user-images.githubusercontent.com/748856/48672469-8cc39c00-eb79-11e8-8cb2-2398a787de56.png)

Where does this event come from? Should you silence every command just in case?

**Comment by s-n-g** [comment]
I really do not know
It happened to me too on a MX linux VBox, running python 3.5.3 (trying to get as close as possible to your 3.5.6)
I suspect that it has something to do with changing the value at the exact time a icy-title arrives, but then again I cannot understand who is writing to stdout / stderror...

**Comment by crocket** [comment]
If you don't know what is writing to stdout and stderr, you can silence everything.

**Comment by s-n-g** [comment]
Can you please check ``s-n-g/pyradio`` on this one?

**Comment by crocket** [comment]
I tested https://github.com/s-n-g/pyradio/commit/e2cc1f4f9f01e3e7c94aed4d924f048d985dd606

It seems to fix the issue, but I'm not totally sure since I don't know what triggered the issue.

How did you fix the issue?

**Comment by s-n-g** [comment]
I suspected it was because of both threads trying to update the status bar, so I introduced a lock in the function which performs the actual update

**Comment by crocket** [comment]
Why do you not try https://en.wikipedia.org/wiki/Software_transactional_memory#Python? I tried STM in clojure, and it was a good mechanism for mediating multi-thread variable updates.

**Comment by s-n-g** [comment]
I think it's safe to close this one; it seems version 0.7.0 addresses this issue successfully (we had no update on such errors, since)
