### ISSUE TITLE
Add station via Hotkey

### ISSUE THREAD

**Issue by nesingho** [coderholic/pyradio#81]
Suggestion: I would like to have one more feature: Add a station quickly (e.g. as pls link) via keycode (e.g. "a") without having to edit stations.csv.

But then the comfort functions are over! :)
Big Thanks for your work!

Yours sincerely
Alex

**Comment by s-n-g** [comment]
Hi again Alex
Thank you for the suggestion. It is already in my TODO list :)
As well as a search function, online playlists, theme editing (working on it right now)
I am also moving to a new apartment at the moment, so time is limited, but we'll get there (hopefully)
Cheers!

**Comment by nesingho** [comment]
All right.
You do this in your spare time and it's scarce, as everyone knows.
So thank you for your work and the info and install it as soon as you have time and leisure! :)

Alex
***

**Comment by s-n-g** [comment]
Please do check 0.8.0 station editing / addition.
If all is ok, we can close this issue

**Comment by s-n-g** [comment]
I believe this can be closed after 0.8.6 is out
