### ISSUE TITLE
Pyradio is not able to use the player you specified.

### ISSUE THREAD

**Issue by Darival** [coderholic/pyradio#82]
PyRadio 0.7.5

 Rypadio is not able to use the player you specified. 
 This means that either this particular player is not supported by PyRadio, or that you have simply misspelled its name. 
PyRadio currently supports three players: mpv, mplayer and vlc, automatically detected in this order.

 Player "mpv" not available. Press any key to exit....

Ubuntu 19.04
mpv 0.29.1 installed

**Comment by Darival** [comment]
I installed Pyradio using snap.
i removed pyradio (snap remove) and built it from source (0.7.7) and now it works.

**Comment by s-n-g** [comment]
Glad you sorted it out!

Putting aside the fact that the snap package was not working, it was outdated too...

**Comment by remlap** [comment]
I am suffering the same problem with 0.7.9 built from source. I have VLC installed but would prefer to use mpv.

**Comment by s-n-g** [comment]
Have you installed socat?

**Comment by remlap** [comment]
That was to simple thanks.

Sorry for the confusion/trouble.

**Comment by s-n-g** [comment]
No prob.
Cheers!
