### ISSUE TITLE
Can not switch to another station

### ISSUE THREAD

**Issue by toogad** [coderholic/pyradio#84]
I am using version 0.8.3 on Manjaro Linux 18.
Pyradio starts fine and plays the first station that I picked from the list. But it was not able to switch to another station. The log file:

[pyradio.log](https://github.com/coderholic/pyradio/files/3827801/pyradio.log)

Any idea what might have happened?

Thanks.
KZ

**Comment by s-n-g** [comment]
ok I think I got it

Can you please build from sources, following these instructions?

Open a terminal
```
git clone https://github.com/s-n-g/pyradio
cd pyradio
git fetch origin
git branch toogad origin/toogad
git checkout toogad
devel/build_install_pyradio
```

If this works, I will push it to master

**Comment by toogad** [comment]
Thanks Spiros,

That solved the problem for me.

Regards,

KZ
web: www.github.com/toogad
twitter: @poopylab

**Comment by s-n-g** [comment]
Ok, closing this one
Committed at https://github.com/coderholic/pyradio/commit/54595a77fd8b00c27ea5e041966357ee7e8e845c (version 0.8.4)
