### ISSUE TITLE
url format

### ISSUE THREAD

**Issue by kermitdafrog8** [coderholic/pyradio#86]
Is there a specific format for the urls to streaming radio's for PyRadio to work?  Any specific format?  Trying to use a local station but they use mp3's and pyradio doesn't want to work correctly with that format.

**Comment by s-n-g** [comment]
Can you please provide the url?

**Comment by kermitdafrog8** [comment]
https://ice.zradio.org/h/high.mp3

**Comment by s-n-g** [comment]
It's the https that's making it go crazy.
Try http://ice.zradio.org/h/high.mp3 (works here)

**Comment by kermitdafrog8** [comment]
I removed it from one of the stations.csv files in the source dir which is what root looked like it was using. I changed the one in the python3 site directory and works fine now.  Thanks.
