### ISSUE TITLE
What ports are needed by PyRadio?

### ISSUE THREAD

**Issue by mihai-catalin** [coderholic/pyradio#87]
I tried to run PyRadio (on Windows) from company network and doesn't work, most probably because some ports are closed. Just changing to an open network solved the issue. Even more, switching back to company network didn't interrupt the streaming.
What ports are needed by PyRadio (or MPlayer?) to work?
Is it possible to change those ports?
Thanks

**Comment by s-n-g** [comment]
I really cannot help you here...
I have tested this on a windows 10 vbox and saw random ports opening in the range of 50,000-50,500 but that's all I can say right now...

Sorry I cannot be of any more help

**Comment by coderholic** [comment]
I think the actual playlists and streaming happens over standard web ports (80, 443), so I don't think it'd be port blocking.

**Comment by s-n-g** [comment]
Hm, maybe not always...

On linux I get
```
ss -tnp| grep mplayer
ESTAB        32772    0            192.168.1.2:54972     184.164.135.70:8259     users:(("mplayer",pid=18110,fd=4),("mplayer",pid=18104,fd=4))
```

**Comment by coderholic** [comment]
What's the port 8259 station, and what's the port 80 station? Looks like a good test case to confirm if it's port blocking or not :)

**Comment by s-n-g** [comment]
CALM RADIO - BIG BAND - Sampler,http://yp.shoutcast.com/sbin/tunein-station.m3u?id=1338594

Lounge (Illinois Street Lounge - SomaFM),http://somafm.com/illstreet.pls

**Comment by coderholic** [comment]
No I don't think the local ports should be an issue - they're not privileged ports, they're just random free ports that are the used to open the connection to the server. You'd see the same thing when making a request to a website. 

It might be that there's content filtering on the network, so streams are being blocked, or it could be that those domains are explicitly blocked, but yeah seems unlikely port 80 is being blocked.

**Comment by s-n-g** [comment]
@mihai-catalin can you play this one
   **http://somafm.com/illstreet.pls**
on your company network?

This is the **Lounge (Illinois Street Lounge - SomaFM)** station on your station's playlist.

This one uses port 80, which should not be blocked, as it's the port normally used for http (i.e. web pages). If this port was blocked, you wouldn't be able to "get on the internet".

If you cannot play this one, your company's network infrastructure is somehow blocking your request (e.g. using content filtering, as @coderholic has suggested), in which case there's nothing you can do about it.

**Comment by mihai-catalin** [comment]
I tried all the links on the playlist but I get an error as below. You are write, it is port 80 which isn't blocked.

C:\Users\....>mplayer http://somafm.com/illstreet.pls
MPlayer sherpya-r38152+gcc50d113c8-8.3-win32 (C) 2000-2019 MPlayer Team

Playing http://somafm.com/illstreet.pls.
Resolving somafm.com for AF_INET...
Connecting to server somafm.com[74.217.192.206]: 80...

Read failed.
STREAM_ASF, URL: http://somafm.com/illstreet.pls
Resolving somafm.com for AF_INET...
Connecting to server somafm.com[74.217.192.206]: 80...
read: No such file or directory

Failed, exiting.
Resolving somafm.com for AF_INET...
Connecting to server somafm.com[74.217.192.206]: 80...

Read failed.
No stream found to handle url http://somafm.com/illstreet.pls


Exiting... (End of file)

**Comment by s-n-g** [comment]
Well, this is a playlist, so
```
mplayer -playlist http://somafm.com/illstreet.pls
```
This is done automatically by pyradio...

So, you can play some of the stations, but not all, right?
