### ISSUE TITLE
Installing via snap. unrecognized backend (mplayer and vlc)

### ISSUE THREAD

**Issue by bnsv** [coderholic/pyradio#88]
I installed pyradio via terminal, and it is offer me install with "sudo snap install pyradio" and done succesfully.The app wont start (error starting player) and complaining that no supported player installed (cant find?), eventough i have vlc and mplayer installed. i even try experimentally manually change from vlc to /usr/bin/vlc in theconfig file. but Still not working. My machine is kubuntu 18.04.3. Thank you

**Comment by s-n-g** [comment]
hi @bnsv 

I do not have snap and do not know why things do not work using it.

Please do try to install pyradio from [https://github.com/coderholic/pyradio/blob/master/build.md](source ), and see if that works.

If you want to use mpv, please make sure you have socat installed as well

**Comment by bnsv** [comment]
thank you for the quick response. I already remove the snap version and reinstalling from source. Unfortunately i got no lucky when trying to build install the stable version 0.8.5:
`
$ devel/build_install_pyradio
running build
running build_py
copying pyradio/radio.py -> build/lib/pyradio
running egg_info
writing pyradio.egg-info/PKG-INFO
writing dependency_links to pyradio.egg-info/dependency_links.txt
writing entry points to pyradio.egg-info/entry_points.txt
writing top-level names to pyradio.egg-info/top_level.txt
reading manifest file 'pyradio.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '*.pyc'
warning: no previously-included files found matching '*.orig'
writing manifest file 'pyradio.egg-info/SOURCES.txt'
copying pyradio/__pycache__/__init__.cpython-37.pyc -> build/lib/pyradio/__pycache__
***** installing...
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

`

**Comment by s-n-g** [comment]
From the docs: 

> Use your distribution method to install python-setuptools, git, sed and any one of MPV, MPlayer and/or VLC

You are missing python-setuptools

**Comment by bnsv** [comment]
I already have python-setuptools set by anaconda, when i try to instal via pip:
```
(base) user $ pip install setuptools
Requirement already satisfied: setuptools in /home/username/anaconda3/lib/python3.7/site-packages (41.4.0)
```

**Comment by s-n-g** [comment]
Yes, I think you should install ubuntu's setuptools

I know nothing about anaconda, so I cannot help you there.

It's obvious that pyradio setup.py is looking for the system-wide installation of setuptools. So, installing your distro setuptools (**sudo apt-get install python-setuptools** or **sudo apt-get install python3-setuptools**, should be the right command, not through pip) should get you up and running.

**Comment by bnsv** [comment]
alright, still got no luck. I install setuptools system wide:
```
$ sudo apt-get install python3-setuptools
Reading package lists... Done
Building dependency tree
Reading state information... Done
python3-setuptools is already the newest version (39.0.1-2).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
```
Still the same error, weird, setuptools is already newest version:
```
$ devel/build_install_pyradio
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools

```
event after i remove the original pyradio directory and try from the scratch, re cloning from git and build install it.

**Comment by s-n-g** [comment]
Try this one
```
devel/build_install_pyradio 3
```

ubuntu's default python version is python2, you are (should be) trying to build a python3 package

**Comment by bnsv** [comment]
Alright! now it's working. Thank you very much Mr. Georgaras. It's a great app.

One problem is that I must run it using sudo. If i dont sudo it, it will throws this error:
```
$ pyradio -p 15
Traceback (most recent call last):
  File "/usr/local/bin/pyradio", line 11, in <module>
    load_entry_point('pyradio==0.8.5', 'console_scripts', 'pyradio')()
  File "/usr/local/lib/python3.6/dist-packages/pyradio-0.8.5-py3.6.egg/pyradio/main.py", line
73, in shell
    pyradio_config = PyRadioConfig()
  File "/usr/local/lib/python3.6/dist-packages/pyradio-0.8.5-py3.6.egg/pyradio/config.py", line 704, in __init__
    PyRadioStations.__init__(self)
  File "/usr/local/lib/python3.6/dist-packages/pyradio-0.8.5-py3.6.egg/pyradio/config.py", line 114, in __init__
    self._check_stations_csv(self.stations_dir, self.root_path)
  File "/usr/local/lib/python3.6/dist-packages/pyradio-0.8.5-py3.6.egg/pyradio/config.py", line 172, in _check_stations_csv
    copyfile(root, path.join(usr, 'stations.csv'))
  File "/usr/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/home/bnsvk18/.config/pyradio/stations.csv'
```

**Comment by s-n-g** [comment]
You are welcome.
It was a bumpy ride, but we got it right!
Cheers!
S.
