### ISSUE TITLE
Feature request: Genre menu

### ISSUE THREAD

**Issue by kermitdafrog8** [coderholic/pyradio#90]
Any possibility to add menus for genre?

**Comment by s-n-g** [comment]
Sorry, I did not get you...
What do you mean?

**Comment by kermitdafrog8** [comment]
Instead of a huge list of radio stations. Have it menu based. Select a genre and radio stations are grouped.

**Comment by s-n-g** [comment]
So you have a huge playlist and would like to display a subset of stations based on genre.
Did I get it right?

It could be done, but that would mean changing the playlist format...
Then you would have to insert the genre(s) for each station... I don't know...

You could achieve something similar though, by organizing stations by genre in playlists.
For example, "rock" playlist (file "rock.csv"), "blues" playlist (file "blues.csv").
I think that would work.
What do you think?

**Comment by kermitdafrog8** [comment]
Could it connect to a pre-sorted online database to get radio station urls?

**Comment by s-n-g** [comment]
Do you mean like a station's directory service?
I am working on this with www.radio-browser.info
But it will take some time

**Comment by kermitdafrog8** [comment]
Need help? Don't have any experience with python but have a little bit of experience with C/C++.

**Comment by s-n-g** [comment]
Sure.
Just fork this https://github.com/s-n-g/pyradio
get to the **debel** branch
and see if **browser.py** makes any sense to you.
python is very different to C

**Comment by RaeedAhmed** [comment]
@kermitdafrog8 You could do what s-n-g suggested and write some sort of wrapper to switch out the playlist .csv files depending on the genre. Have your program switch out the stations.csv file in the appropriate directory from an external list of csv files, then launch pyradio (you can use subprocess or whatever)

**Comment by s-n-g** [comment]
@RaeedAhmed Not necessary. It's much easier than that.

Once the playlists are by genre, you can just press "**o**" and open the one you want, provided they are stored in the config folder (run **pyradio -scd** to find it)

**Comment by baruchiro** [comment]
Hi @coderholic , Can you please update the title?

Every time I want to open a new issue I need to open this to see if my issue already created.

Thanks.
