### ISSUE TITLE
Feature Request: Station info

### ISSUE THREAD

**Issue by naryfa** [coderholic/pyradio#91]
Would love to see some live info (time, volume, codec, channels, bitrate, etc.)

Thank you.

**Comment by s-n-g** [comment]
Thank you for the suggestion.
I will look into it
S.

**Comment by kls0e** [comment]
Thanks for this great app. I had installed the ubuntu 19.10 snap in the first place but it contains some old version so I built from source and pyradio runs great. I'd also like to see some technical stats, like codec info, bitrate, total kbytes transferred, perhaps in the main interface in the upper or lower bar or in a separate box.

**Comment by s-n-g** [comment]
Can you please check 0.8.8-beta1 #94 ?

When installed, "**i**" will display station's info.

**Comment by baruchiro** [comment]
See https://github.com/coderholic/pyradio/issues/90#issuecomment-743992222
