### ISSUE TITLE
changing bitrate

### ISSUE THREAD

**Issue by astier** [coderholic/pyradio#92]
Hi. Is it possible to change the bitrate? I have not much bandwidth and would like to reduce the bitrate. Thank you.

**Comment by s-n-g** [comment]
Hi
Well, that depends on the station itself.

Take for example [Radio Paradise](https://radioparadise.com/listen/stream-links).
This station provides streaming feeds with bitrate ranging from 24k to 320k, so you could edit the station within pyradio and use the one that works best for you.

So, if the station in question provides alternative (or multiple) streams, yes you can edit any station and change its url to it.

The thing is, not all stations provide alternative (or multiple) streams, and even if one does, there is no practical way to automatically replace one url with another. In other words, you have to know the reduced bitrate url and insert it manually.

Other than that, I don't think you can do much more.

**Comment by astier** [comment]
Thank you very much!
