### ISSUE TITLE
radio-browser support

### ISSUE THREAD

**Issue by segler-alex** [coderholic/pyradio#93]
Hi,

thank you for adding support of radio-browser.info
i am the admin of radio-browser, if you have any questions or suggestions, feel free to ask them at
https://github.com/segler-alex/radiobrowser-api-rust

i added pyradio to the linklist on www.radio-browser.info

greetings from vienna/austria

**Comment by segler-alex** [comment]
one thing
it would be nice if you would call the following after a station click, so the click will get counted:

http://www.radio-browser.info/webservice/v2/xml/url/stationuuid
example:
http://www.radio-browser.info/webservice/v2/xml/url/9617a958-0601-11e8-ae97-52543be04c81

always use "stationuuid" instead of "id" field

**Comment by s-n-g** [comment]
Hi there Alex

We have already talked via email, as I have been working on this for some time now, but I'm currently waiting for the new REST scheme to be ready and server sync gets completed, so I've put the whole thing on hold.

I have a couple of thought about the new servers but I will contact you at https://github.com/segler-alex/radiobrowser-api-rust

Greetings from Corfu/Greece

**Comment by segler-alex** [comment]
the api will not change anymore, you can already use it. 
is there a special thing you are waiting for?

**Comment by s-n-g** [comment]
No, just that.
That's good to know!
I will have a look and get back to you with any questions.
Thanks!

**Comment by s-n-g** [comment]
Closed in https://github.com/coderholic/pyradio/releases/tag/0.9.0
