### ISSUE TITLE
Help needed: 0.8.8-beta1

### ISSUE THREAD

**Issue by s-n-g** [coderholic/pyradio#94]
Hi all

I just pushed a beta branch (_0.8.8-beta1_) implementing **registers** (copy, paste), **station info**, connection **timeout counter**, alternative modes, etc. Some of those features are not fully implemented, but I would like you to give it a try and report back here any issues you encounter.

For more info, read **PyRadio’s Modes** and **Copying and pasting - Registers** in ```index.html``` or the man page.

To get it, execute the following commands:

```
git clone https://github.com/coderholic/pyradio
cd pyradio
git fetch origin
git checkout -b 0.8.8-beta1 origin/0.8.8-beta1
```

Finally, install it
```
devel/build_install_pyradio
```
or if ```python 2``` is the default one used by your distro
```
devel/build_install_pyradio 3
```

If you do test it, please report back even if no issues found

**Comment by naryfa** [comment]
Hi, 

Thank you so much for implementing this. I checked out on my Linux Mint VM and the only problem I get is that when the terminal window is too small, it'll tell me so:

https://i.paste.pics/edefb533040fa5a91368c0696ea56cf5.png

Otherwise it seems to work nicely. 

The rename function is cool too.

I guess, in a perfect world, that info could live in the status bar at the bottom, but I'm thankful you found the will to implement this. 

P.S. how come you don't have a donate button anywhere?

**Comment by s-n-g** [comment]
> Hi,
> 
> Thank you so much for implementing this. I checked out on my Linux Mint VM and the only problem I get is that when the terminal window is too small, it'll tell me so:
> 
> https://i.paste.pics/edefb533040fa5a91368c0696ea56cf5.png
> 
> Otherwise it seems to work nicely.
> 
> The rename function is cool too.
> 

Well, that is not a problem, it's a precaution.
You see, this is supposed to be run on an 80x24 terminal window, which is the default for many of them, so messages are made to fit those dimensions. If the window is smaller, the interface would just break, hence the "Window too small..." message.


> I guess, in a perfect world, that info could live in the status bar at the bottom, but I'm thankful you found the will to implement this.

There's moo much data to display on the status bar; even when we have a wide window, displaying some or all of them at the status bar would mean some kind of scrolling should take place, which would make the whole thing too complicated. It could be done, but that's something for the future, maybe.

> 
> P.S. how come you don't have a donate button anywhere?

Well, there's no need for it. 
I'm glad I'm able to give something back to the community; I've gotten so much all these years.

**Comment by OverfloError** [comment]
Currently testing using a kisslinux based distro. So far no great disasters.
The only Error type messages I have so far been able to find seem benign but ill paste them anyways.

The environment was as follows:
python 3.8.1
rxvt-unicode 9.22
ncurses 6.1

Log start:

2020-02-05 16:44:19,107 - pyradio.themes - ERROR - DE _do_init_pairs:
{'Stations': [7, 0], 'Status Bar': [0, 2], 'Normal Cursor': [0, 5], 'Active Cursor': [0,2], 'Active Station': [2, 0], 'PyRadio URL': [4, 0], '
Messages Border': [3, 0], 'Edit Cursor': [7, 5], 'Colors': 8, 'Name': 'dark', 'Path': ''}
2020-02-05 16:44:19,107 - pyradio.player - INFO - Probing available multimedia players...
2020-02-05 16:44:19,107 - pyradio.player - INFO - Implemented players: mpv, mplayer, cvlc
2020-02-05 16:44:19,108 - pyradio.player - INFO - <class 'pyradio.player.MpvPlayer'> supported.
2020-02-05 16:44:19,108 - pyradio.radio - ERROR - DE ===== _put:startPos -> 0, force = False
2020-02-05 16:44:19,110 - pyradio.radio - DEBUG - detectUpdateThread: starting...
2020-02-05 16:44:19,110 - pyradio.log - DEBUG - Status: "Selected player: mpv"
2020-02-05 16:44:19,110 - pyradio.log - DEBUG - Status right: "Press ? for help"


If i can add any other information please tell me so.
This was produced without testing anyithing new yet.
Will update when I have tested the other features.

**Comment by s-n-g** [comment]
Hi @OverfloError 

Thank you so much for helping out!

Don't worry about any ERRORs found in the log file at this point.
Just look for any breakages or strange behavior while testing the new features.

**Comment by filipzeman** [comment]
OS: MacOS Mojave 10.14.6
Terminal: iTerm 2 3.3.1

For me this build works perfect, will update next week.
