### ISSUE TITLE
 Unable to use mpv as player due to parsing commandline option playlist.

### ISSUE THREAD

**Issue by HawaiinPizza** [coderholic/pyradio#95]
When using mpv as the player, it fails to connect to SOFM stations/rainwave. When checking the debug, I see this line:
```
2020-01-30 17:09:13,063 - pyradio.player - DEBUG - User input: Error parsing commandline option 
playlist: option requires parameter
```
I remember this error happen before when using youtube-dl, but I'm not sure what to do to fix it.  
[pyradio.log](https://github.com/coderholic/pyradio/files/4136474/pyradio.log)
Mplalyer works however, but it can't play youtube videos.

The version of mpv I have is 0.32.0
 Youtube-dl version is 2020.01.24

**Comment by s-n-g** [comment]
Yes, something changed there...
Can you please test this one?

In ```pyradio/player.py```
replace
```"--playlist", http_url```
with
```"--playlist=" + http_url```

Build by and tell me if it's ok for you too

**Comment by s-n-g** [comment]
ok, tested it with 0.29.0 and 0.31.0 and released it here:

https://github.com/coderholic/pyradio/releases/tag/0.8.7.1

**Comment by HawaiinPizza** [comment]
I came to conform this works! thank you so much.
