### ISSUE TITLE
Themes not working

### ISSUE THREAD

**Issue by Antavatech** [coderholic/pyradio#99]
Hello:

I just installed the latest version 0.8.7.2 and it works fine except for the themes.  When I press "t" it only lists dark, light, brown, pink, and purple.  Only dark and light work, selecting any of the colors produces an error "Error loading selected theme".  Any help would be appreciated, thanks.

Anthony

**Comment by s-n-g** [comment]
Hi Anthony,

Can you please execute ```pyradio -d``` and send the ```~/pyradio.log``` file?
It seems to me that your terminal supports 8 colors only, but let's see the log...

What platform are you on?
What terminal do you use?

**Comment by Antavatech** [comment]
Hello, thanks for responding.  Please see the attached log file.  This is running on a raspberry pi zero wireless, Raspbian buster lite (no desktop), and I followed the install instructions from your github.  I tried this using DietPi on the RpiZW and it didn’t work either.

Anthony Castiglia
CEO - ANTAVATECH LLC
M 973-818-0608
anthony@antavatech.com<mailto:anthony@antavatech.com>
www.antavatech.com<http://www.antavatech.com>
[cid:image001.png@01D61425.FE44B730]

**Comment by s-n-g** [comment]
Hi again!
Have you attached the log?
Maybe put it on pastebin or something and provide a link...

**Comment by Antavatech** [comment]
Sorry, it was in the email.  Now here.
[pyradio.log](https://github.com/coderholic/pyradio/files/4490227/pyradio.log)

**Comment by s-n-g** [comment]
Ok, look at line 2:
```
2020-04-16 19:26:53,796 - pyradio.radio - INFO - Terminal supports 8 colors
```

This is why only dark and light themes are actually working; they are 8 color themes.
All the other themes are 256 color themes; so they give an error.
I know it's not clear, it should just say something like "theme not supported" or the like, or even not display them at all. Maybe something for the future?

The bottom line is, you are stuck with 2 8-color themes, unless you install a teminal that supports 256 colors.

A quick way to check how many colors a terminal supports is the following script ()

```
#!/usr/bin/env python
import curses

def main(stdscr):
    curses.start_color()
    curses.use_default_colors()
    stdscr.addstr('Number of supported colors: {}\n'.format(curses.COLORS))
    stdscr.getch()
    curses.endwin()

curses.wrapper(main)

```

Save it as ```term_colors.py``` (or whatever), make it executable and you can quickly check any terminal you may have

I hope that helps...
S.

**Comment by Antavatech** [comment]
Ok great, the error message could use some work :).  I appreciate the response, I really like pyradio.  I'm working on incorporating it into an internet radio project.  Thanks again.

**Comment by s-n-g** [comment]
Welcome!
I'll just leave this one open to remind me of the messages...

**Comment by s-n-g** [comment]
Fixed in https://github.com/coderholic/pyradio/commit/18cd1f031ec47d1edb03435b4e65db712a3e42bf
